const fireAbilities = [
    {
      id: 'fire_initiate_flame_ward',
      name: 'Flame Ward',
      description: 'You have advantage on saving throws against being frightened or charmed while within 10 feet of a source of fire or heat.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_initiate_searing_gaze',
      name: 'Searing Gaze',
      description: 'When you focus intently on a creature for 1 minute, you can attempt an Intimidation check. If successful, the creature is unsettled and has disadvantage on saving throws against being frightened or charmed by you for 1 hour.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_initiate_ember_strike',
      name: 'Ember Strike',
      description: 'When you hit a creature with a weapon attack, you can expend a spell slot to deal an additional 1d12 fire damage per level of the spell slot expended.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_initiate_flame_lash',
      name: 'Flame Lash',
      description: 'You can use your action to create a whip-like tendril of fire that extends up to 15 feet. Make a melee spell attack against a creature within range. On a hit, the target takes fire damage equal to 1d6 + your spellcasting ability modifier. The intense heat also causes the target to become dazzled, giving them disadvantage on their next attack roll. This ability’s damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_initiate_inferno_disengage',
      name: 'Inferno Disengage',
      description: 'When you use the Disengage action, you create a burst of fire around you. Each creature within 5 feet of you must make a Dexterity saving throw. On a failed save, a creature takes 1d6 fire damage and catches fire. On a successful save, a creature takes half damage The damage increases by 1d6 at 5th Adept level (2d6), 9th Master level (3d6), 13th Grandmaster level (4d6), and 17th Great-grandmaster level (5d6).',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_adept_blazing_presence',
      name: 'Blazing Presence',
      description: 'Your fiery aura gives you a commanding presence. You can use your action to create a burst of heat and light, giving you advantage on Intimidation checks and causing those who fail a Wisdom saving throw to be frightened until the end of your next turn.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_adept_flame_kinship',
      name: 'Flame Kinship',
      description: 'You gain the ability to communicate with creatures of fire, such as Fire Elementals and Magmin, as if you shared a common language. This does not grant you the ability to control or command them but allows for basic communication and understanding.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_adept_embers_resilience',
      name: 'Ember\'s Resilience',
      description: 'You can channel the residual heat around you to bolster your own resistance. When you fail a saving throw, you can choose to succeed instead taking 2d6 of fire damage.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_adept_blazing_trail',
      name: 'Blazing Trail',
      description: 'When you take the dash action, you can leave a trail of fire in your wake. For the duration of the movement, any creature that moves through or ends its turn in a 10-foot-wide line you create takes fire damage equal to twice your spellcasting ability modifier. This trail lasts for 1 minute or until you choose to end it.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'fire_adept_scorched_ground',
      name: 'Scorched Ground',
      description: 'As an action, you can cause a 20-foot radius area on the ground to become superheated within 120 feet of you for 1 minute. Creatures that start their turn in this area take fire damage equal to 2d6 + your spellcasting ability modifier. The area is difficult terrain, and the fire persists even if you move away from it. This ability’s damage increases by 1d6 when you reach 9th Master level (3d6), 13th Grandmaster level (4d6), and 17th Great-grandmaster level (5d6).',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
   ];
  
   const fireCantrips = [
    {
      id: 'fire_cantrip_control_flames',
      name: 'Control Flames',
      description: 'https://5e.tools/spells.html#control%20flames_xge',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'fire_cantrip_create_bonfire',
      name: 'Create Bonfire',
      description: 'https://5e.tools/spells.html#create%20bonfire_xge',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'fire_cantrip_fire_bolt',
      name: 'Fire Bolt',
      description: 'https://5e.tools/spells.html#fire%20bolt_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
     {
      id: 'fire_cantrip_green_flame_blade',
      name: 'Green-Flame Blade',
      description: 'https://5e.tools/spells.html#green-flame%20blade_tce',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'fire_cantrip_produce_flame',
      name: 'Produce Flame',
      description: 'https://5e.tools/spells.html#produce%20flame_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
   ];
  
   const fireSpells = [
    {
      id: 'fire_1st_level_burning_hands',
      name: 'Burning Hands',
      description: 'https://5e.tools/spells.html#burning%20hands_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_1st_level_hellish_rebuke',
      name: 'Hellish Rebuke',
      description: 'https://5e.tools/spells.html#hellish%20rebuke_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_2nd_level_aganazzars_scorcher',
      name: 'Aganazzar\'s Scorcher',
      description: 'https://5e.tools/spells.html#aganazzar\'s%20scorcher_xge',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_2nd_level_continual_flame',
      name: 'Continual Flame',
      description: 'https://5e.tools/spells.html#continual%20flame_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_2nd_level_flame_blade',
      name: 'Flame Blade',
      description: 'https://5e.tools/spells.html#flame%20blade_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_2nd_level_flaming_sphere',
      name: 'Flaming Sphere',
      description: 'https://5e.tools/spells.html#flaming%20sphere_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_2nd_level_scorching_ray',
      name: 'Scorching Ray',
      description: 'https://5e.tools/spells.html#scorching%20ray_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_3rd_level_fireball',
      name: 'Fireball',
      description: 'https://5e.tools/spells.html#fireball_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_3rd_level_flame_arrows',
      name: 'Flame Arrows',
      description: 'https://5e.tools/spells.html#flame%20arrows_xge',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_4th_level_fire_shield',
      name: 'Fire Shield',
      description: 'https://5e.tools/spells.html#fire%20shield_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'fire_4th_level_wall_of_fire',
      name: 'Wall of Fire',
      description: 'https://5e.tools/spells.html#wall%20of%20fire_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
   ];