const metalAbilities = [
    {
      id: 'metal_initiate_metalcrafting',
      name: 'Metalcrafting',
      description: 'Gain proficiency with smith\'s tools if you don\'t already have it.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_initiate_magnetic_attraction',
      name: 'Magnetic Attraction',
      description: 'You can use a bonus action to pull or push a metal object weighing up to 10 pounds up to 10 feet towards or away from you. This can be used to manipulate weapons, tools, or similar objects in combat or to solve puzzles.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_initiate_metal_sense',
      name: 'Metal Sense',
      description: 'You can detect the presence of metal within 30 feet of you. You sense the type and general location of metal objects, including hidden compartments or concealed weapons.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_initiate_keen_edge',
      name: 'Keen Edge',
      description: 'As a bonus action, you can temporarily sharpen a weapon, granting it a +1 bonus to attack and damage rolls for the next hour.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_initiate_magnetic_focus',
      name: 'Magnetic Focus',
      description: 'As a bonus action, you can magnetically attract a metal weapon you can see within 30 feet of you to your hand. This weapon does not provoke opportunity attacks while being drawn.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_initiate_metallic_echo',
      name: 'Metallic Echo',
      description: 'When you strike a metallic object with a melee weapon, you can create a ringing sound that echoes in a 10-foot radius. Creatures in the area must succeed on a Constitution saving throw or be deafened until the end of their next turn.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_adept_enhanced_armor',
      name: 'Enhanced Armor',
      description: 'You can spend 10 minutes to reinforce any armor. For the next hour, you gain resistance to one type of damage (chosen when you use this ability) while wearing armor.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_adept_magnetic_manipulation',
      name: 'Magnetic Manipulation',
      description: 'You can use an action to exert magnetic force on a metal object or creature within 30 feet. You can move the object or creature up to 10 feet in any direction, or cause the object to be attracted or repelled by a metal surface.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_adept_gemsight',
      name: 'Gemsight',
      description: 'You gain proficiency in Perception checks to locate hidden gemstones or precious minerals. When you find such items, you can appraise their value with a successful Intelligence (Investigation) check.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_adept_magnetic_shield',
      name: 'Magnetic Shield',
      description: 'As a reaction when you are hit by an attack, you can create a magnetic field that reduces the damage by 1d10 + your Constitution modifier. If the attacker is wielding a metal weapon, they must make a Strength saving throw or be disarmed.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'metal_adept_steel_tornado',
      name: 'Steel Tornado',
      description: 'As an action, you can create a whirlwind of metallic shards in a 10-foot radius and 30-foot tall cylinder centered on you. Creatures within the cylinder must make a Dexterity saving throw. On a failed save, a creature takes 2d6 slashing damage, or half as much damage on a successful save. The damage increases to 3d6 at 9th Master level, 4d6 at 13th Grandmaster level, and 5d6 at Great-grandmaster 17th level.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
   ];
  
   const metalCantrips = [
    {
      id: 'metal_cantrip_blade_ward',
      name: 'Blade Ward',
      description: 'https://5e.tools/spells.html#blade%20ward_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'metal_cantrip_sword_burst',
      name: 'Sword Burst',
      description: 'https://5e.tools/spells.html#sword%20burst_tce',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
   ];
  
   const metalSpells = [
    {
      id: 'metal_2nd_level_cloud_of_daggers',
      name: 'Cloud of Daggers',
      description: 'https://5e.tools/spells.html#cloud%20of%20daggers_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'metal_2nd_level_heat_metal',
      name: 'Heat Metal',
      description: 'https://5e.tools/spells.html#heat%20metal_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'metal_4th_level_fabricate',
      name: 'Fabricate',
      description: 'https://5e.tools/spells.html#fabricate_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
   ];