const waterAbilities = [
    {
      id: 'water_initiate_echoes_of_the_deep',
      name: 'Echoes of the Deep',
      description: 'You can communicate with aquatic creatures or spirits of water, allowing you to understand their language and gain information about underwater locations or hidden treasures.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_initiate_ice_form',
      name: 'Ice Form',
      description: 'As a bonus action, you can turn your body into ice for 1 minute. You gain resistance to cold and fire damage and your movement speed is reduced by 10 feet.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_initiate_raincaller',
      name: 'Raincaller',
      description: 'You can call forth a light rain within a 20-foot radius centered on you for 10 minutes. This rain lightly obscures the area, granting disadvantage on Perception checks relying on sight and extinguishing small fires.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_initiate_restorative_rain',
      name: 'Restorative Rain',
      description: 'As an action, you create a 20-foot radius of gentle rain centered on you that lasts for a number of rounds equal to your maximum Water essences. At the end of each of their turns while in the rain, they regain 1 hit point.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_initiate_aqua_agility',
      name: 'Aqua Agility',
      description: 'Your swimming speed equals your walking speed. Additionally, you gain the ability to breathe underwater and move through water at your normal speed without penalty.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_adept_tide_of_emotions',
      name: 'Tide of Emotions',
      description: 'By channelling the ebb and flow of water, you can influence the emotions of others within a 30-foot radius. Choose one emotion (calm, fear, or joy); affected creatures must succeed on a Wisdom saving throw or be overwhelmed by that emotion for 1 hour.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_adept_tidal_surge',
      name: 'Tidal Surge',
      description: 'You can summon a powerful wave of water that heals and revitalizes. As an action, you create a wave that washes over allies in a 30-foot radius, restoring hit points equal to 3d8 + your spellcasting ability modifier. This wave also removes one condition affecting allies (charmed, frightened, or poisoned). This ability’s healing increases by 1d8 when you reach 9th Master level (4d8), 11th Grandmaster level (5d8), and 17th Great-Grandmaster level (6d8).',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_adept_frozen_insight',
      name: 'Frozen Insight',
      description: 'You can temporarily turn your thoughts into ice, allowing you to gain deep insight into a complex problem or puzzle. For 1 hour, you gain advantage on Intelligence checks related to solving mysteries or understanding arcane knowledge.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_adept_rain_of_revelation',
      name: 'Rain of Revelation',
      description: 'You can summon a gentle, magical rain that grants clarity and insight to those who stand in it. Allies within a 20-foot radius can ask one question about their future or destiny, and you provide a vague but helpful answer based on your understanding of the world.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_adept_glacial_shield',
      name: 'Glacial Shield',
      description: 'As a reaction, you can spend one spell slot and encase yourself in a barrier of ice, granting you temporary hit points equal to twice your spellcasting ability modifier + your spell level. This lasts for 1 minute.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_adept_hydroportation',
      name: 'Hydroportation',
      description: 'As a bonus action, you can teleport up to 60 feet to a space you can see within a body of water or mist. You must be in contact with the water or mist to use this ability.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'water_adept_surface_strider',
      name: 'Surface Strider',
      description: 'You can walk on the surface of water and you gain advantage on Dexterity (Acrobatics) checks to maintain your balance while walking on slippery or unstable surfaces.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
   ];
  
   const waterCantrips = [
    {
      id: 'water_cantrip_acid_splash',
      name: 'Acid Splash',
      description: 'https://5e.tools/spells.html#acid%20splash_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'water_cantrip_frostbite',
      name: 'Frostbite',
      description: 'https://5e.tools/spells.html#frostbite_xge',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'water_cantrip_ray_of_frost',
      name: 'Ray of Frost',
      description: 'https://5e.tools/spells.html#ray%20of%20frost_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'water_cantrip_shape_water',
      name: 'Shape Water',
      description: 'https://5e.tools/spells.html#shape%20water_xge',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
   ];
  
   const waterSpells = [
    {
      id: 'water_1st_level_create_or_destroy_water',
      name: 'Create or Destroy Water',
      description: 'https://5e.tools/spells.html#create%20or%20destroy%20water_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_1st_level_detect_poison_and_disease',
      name: 'Detect Poison and Disease',
      description: 'https://5e.tools/spells.html#detect%20poison%20and%20disease_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_1st_level_fog_cloud',
      name: 'Fog Cloud',
      description: 'https://5e.tools/spells.html#fog%20cloud_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_1st_level_grease',
      name: 'Grease',
      description: 'https://5e.tools/spells.html#grease_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_1st_level_ice_knife',
      name: 'Ice Knife',
      description: 'https://5e.tools/spells.html#ice%20knife_xge',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_2nd_level_melfs_acid_arrow',
      name: 'Melf\'s Acid Arrow',
      description: 'https://5e.tools/spells.html#melf\'s%20acid%20arrow_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_2nd_level_protection_from_poison',
      name: 'Protection from Poison',
      description: 'https://5e.tools/spells.html#protection%20from%20poison_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_2nd_level_snillocs_snowball_swarm',
      name: 'Snilloc\'s Snowball Swarm',
      description: 'https://5e.tools/spells.html#snilloc\'s%20snowball%20swarm_xge',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_2nd_level_misty_step',
      name: 'Misty Step',
      description: 'https://5e.tools/spells.html#misty%20step_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_3rd_level_sleet_storm',
      name: 'Sleet Storm',
      description: 'https://5e.tools/spells.html#sleet%20storm_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_3rd_level_tidal_wave',
      name: 'Tidal Wave',
      description: 'https://5e.tools/spells.html#tidal%20wave_xge',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_3rd_level_wall_of_water',
      name: 'Wall of Water',
      description: 'https://5e.tools/spells.html#wall%20of%20water_xge',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_3rd_level_water_breathing',
      name: 'Water Breathing',
      description: 'https://5e.tools/spells.html#water%20breathing_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_3rd_level_water_walk',
      name: 'Water Walk',
      description: 'https://5e.tools/spells.html#water%20walk_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_4th_level_control_water',
      name: 'Control Water',
      description: 'https://5e.tools/spells.html#control%20water_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_4th_level_ice_storm',
      name: 'Ice Storm',
      description: 'https://5e.tools/spells.html#ice%20storm_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
     {
      id: 'water_4th_level_vitriolic_sphere',
      name: 'Vitriolic Sphere',
      description: 'https://5e.tools/spells.html#vitriolic%20sphere_xge',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'water_4th_level_watery_sphere',
      name: 'Watery Sphere',
      description: 'https://5e.tools/spells.html#watery%20sphere_xge',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
   ];