export const acidAbilities = [
    {
      id: 'acid_initiate_caustic_bomb',
      name: 'Caustic Bomb',
      description: 'As an action, you can create a powerful, improvised explosive from available materials. It deals 4d6 acid damage in a 10-foot radius on a failed Dexterity saving throw, or half as much on a successful save.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_initiate_chaos_manipulation',
      name: 'Chaos Manipulation',
      description: 'Once per long rest, you can cause a minor chaotic effect within 30 feet, such as causing objects to tremble, flicker, or shift unpredictably. The effect lasts for 1 minute and can create distractions or disorient opponents.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_initiate_alchemy_proficiency',
      name: 'Alchemy Proficiency',
      description: 'Gain proficiency in Alchemist’s Supplies. You can craft basic alchemical substances, such as acid flasks, potions of healing, and other simple concoctions.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_initiate_acidic_insight',
      name: 'Acidic Insight',
      description: 'You have developed a keen understanding of acidic substances and their effects. You gain advantage on Intelligence (Arcana) and Wisdom (Nature) checks related to acids, alchemical reactions, and chemical processes. This knowledge allows you to identify and analyse unknown substances or toxins with ease.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_initiate_acidic_precision',
      name: 'Acidic Precision',
      description: 'Your expertise with corrosive substances has honed your skill in turning everyday objects into deadly weapons. You gain proficiency with all thrown weapons and improvised thrown weapons.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_adept_chemical_expertise',
      name: 'Chemical Expertise',
      description: 'You can create more advanced alchemical mixtures, such as potent acid flasks or alchemical fire. You gain a +2 bonus to checks involving Alchemist’s Supplies and can create these mixtures in half the usual time.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_adept_explosive_savant',
      name: 'Explosive Savant',
      description: 'When you use an explosive device or alchemical flask, its damage increases by an additional damage dice. Additionally, you can use such devices as a bonus action instead of an action.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_adept_miasmic_cloud',
      name: 'Miasmic Cloud',
      description: 'You can create a cloud of acidic mist in a 10-foot radius around you. Any creature that starts its turn within the cloud must make a Constitution saving throw or take 6d6 acid damage and be blinded until the end of its next turn.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_adept_acidic_embrace',
      name: 'Acidic Embrace',
      description: 'You can magically coat a weapon or object in a layer of corrosive acid. The weapon deals an additional 2d4 acid damage on a successful hit, and the object corrodes any non-magical material it touches. This effect lasts for 1 minute',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'acid_adept_expanded_explosion',
      name: 'Expanded Explosion',
      description: 'Your expertise in crafting explosives has improved the effectiveness of your bombs. When you create or use an explosive device, you increase its radius by 10 feet. For example, a bomb that normally affects a 10-foot radius now affects a 15-foot radius. This increased radius applies to all explosive effects you create, including those from your Improvised Explosives and any similar abilities.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
   ];
  
   export const acidCantrips = [
    {
      id: 'acid_cantrip_acid_splash',
      name: 'Acid Splash',
      description: 'https://5e.tools/spells.html#acid%20splash_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'acid_cantrip_primal_savagery',
      name: 'Primal Savagery',
      description: 'https://5e.tools/spells.html#primal%20savagery_xge',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
   ];
  
   export const acidSpells = [
    {
      id: 'acid_1st_level_absorb_elements',
      name: 'Absorb Elements',
      description: 'https://5e.tools/spells.html#absorb%20elements_xge',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_1st_level_chromatic_orb',
      name: 'Chromatic Orb',
      description: 'https://5e.tools/spells.html#chromatic%20orb_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_1st_level_chaos_bolt',
      name: 'Chaos Bolt',
      description: 'https://5e.tools/spells.html#chaos%20bolt_xge',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_2nd_level_melfs_acid_arrow',
      name: 'Melf\'s Acid Arrow',
      description: 'https://5e.tools/spells.html#melf\'s%20acid%20arrow_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_2nd_level_dragons_breath',
      name: 'Dragon\'s Breath',
      description: 'https://5e.tools/spells.html#dragon\'s%20breath_xge',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_3rd_level_elemental_weapon',
      name: 'Elemental Weapon',
      description: 'https://5e.tools/spells.html#elemental%20weapon_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_3rd_level_glyph_of_warding',
      name: 'Glyph of Warding',
      description: 'https://5e.tools/spells.html#glyph%20of%20warding_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
     {
      id: 'acid_3rd_level_hunger_of_hadar',
      name: 'Hunger of Hadar',
      description: 'https://5e.tools/spells.html#hunger%20of%20hadar_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_4th_level_vitriolic_sphere',
      name: 'Vitriolic Sphere',
      description: 'https://5e.tools/spells.html#vitriolic%20sphere_xge',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_4th_level_elemental_bane',
      name: 'Elemental Bane',
      description: 'https://5e.tools/spells.html#elemental%20bane_xge',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_5th_level_wall_of_force',
      name: 'Wall of Force',
      description: 'https://5e.tools/spells.html#wall%20of%20force_xphb',
      tier: '5th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_5th_level_synaptic_static',
      name: 'Synaptic Static',
      description: 'https://5e.tools/spells.html#synaptic%20static_xphb',
      tier: '5th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'acid_6th_level_disintegrate',
      name: 'Disintegrate',
      description: 'https://5e.tools/spells.html#disintegrate_xphb',
      tier: '6th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
  {
    id: 'acid_7th_level_prismatic_spray',
    name: 'Prismatic Spray',
    description: 'https://5e.tools/spells.html#prismatic%20spray_phb',
    tier: '7th',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'acid_8th_level_antimagic_field',
    name: 'Antimagic Field',
    description: 'https://5e.tools/spells.html#prismatic%20spray_phb',
    tier: '8th',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'acid_9th_level_prismatic_wall',
    name: 'Prismatic Wall',
    description: 'https://5e.tools/spells.html#prismatic%20wall_phb',
    tier: '9th',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'acid_9th_level_storm_of_vengeance',
    name: 'Storm of Vengeance',
    description: 'https://5e.tools/spells.html#storm%20of%20vengeance_phb',
    tier: '9th',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
    {
    id: 'acid_9th_level_blade_of_disaster',
    name: 'Blade of Disaster',
    description: 'https://5e.tools/spells.html#blade%20of%20disaster_tce',
    tier: '9th',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },

];
