export const airAbilities = [
  {
    id: "wind_initiate_mistbound_step",
    name: "Mistbound Step",
    description: "The Misty Step spell does not consume a spell slot if you begin or end your movement in a heavily obscured area.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_initiate_thunderous_roar",
    name: "Thunderous Roar",
    description: "You can let out a powerful roar that creates a shockwave, forcing all creatures within 10 feet to make a Constitution saving throw or be pushed 10 feet away from you and become deafened for 1 minute.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_initiate_whispers_of_the_gale",
    name: "Whispers of the Gale (Laura)",
    description: "When you miss with a ranged attack roll (including spell attacks), you can use your reaction and expend a spell slot of 1st level or higher to reroll the attack. You must use the new roll, and the spell slot is expended regardless of the outcome.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_echoing_footsteps",
    name: "Echoing Footsteps",
    description: "You can move with such speed and silence that your footsteps echo faintly. You gain advantage on Stealth checks, and creatures within 100 feet of you have disadvantage on Wisdom (Perception) checks to hear you. This effect lasts for 10 minutes.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_thunderstep",
    name: "Thunderstep",
    description: "You can use an action to make a sudden, loud noise, creating a brief but intense thunderclap that can be heard up to 300 feet away. Creatures within 30 feet of you must make a Constitution saving throw or be stunned until the end of your next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_calm_breeze",
    name: "Calm Breeze",
    description: "You can use a bonus action to create a soothing breeze that relaxes and calms creatures within a 30-foot radius, providing them with advantage on saving throws against being frightened or charmed. This effect lasts for 10 minutes.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_misty_escape",
    name: "Misty Escape",
    description: "When you take damage, you can use your reaction to turn into a cloud of mist, causing the attack to miss. You must spend a spell slot of 1st level or higher to use this ability.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_whispering_winds",
    name: "Whispering Winds",
    description: "You can use your action to send a message carried by the wind to any creature within 1 mile of you. The message is heard as a whisper by the intended recipient. This ability allows for secret communications or covert information exchange.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_wind_barrier",
    name: "Wind Barrier",
    description: "As a reaction to being targeted by an attack or harmful spell, you can summon a barrier of wind around you. You gain a +2 bonus to AC and saving throws until the start of your next turn. Additionally, attacks against you have disadvantage.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_cyclone_step",
    name: "Cyclone Step",
    description: "When you use the Dash action, you can create a swirling vortex of wind around you. Creatures within 10 feet of your path must make a Strength saving throw or be knocked prone. The wind dissipates at the end of your movement.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_wind_sprint",
    name: "Wind Sprint",
    description: "You can double your movement speed for a number of rounds equal to your total of wind essences.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_sound_analysis",
    name: "Sound Analysis",
    description: "You can accurately determine the source and direction of any sound within 300 feet of you. This ability can be used to track creatures or detect hidden enemies. It provides you advantage on Wisdom (Perception) checks related to sound.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_gale_force_strike",
    name: "Gale Force Strike",
    description: "When you hit a creature of your size or smaller, or any creature one size category larger than you, with an attack or spell, you can create a gust of wind that forces the creature to make a Strength saving throw. On a failed save, the creature is pushed 10 feet in any direction you choose.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_adept_fortune_favors_the_swift",
    name: "Fortune Favors the Swift",
    description: "Whenever you expend a spell slot, you gain a d6 “wind die”. You can add it to one d20 roll before the end of your next turn.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_master_essence_liberations_gale",
    name: "Liberation’s Gale",
    description: "A cleansing wind sweeps from you to creatures within 60 feet. Choose up to six targets; each immediately ends one of the following conditions: Blinded, Charmed, Deafened, Frightened, Grappled, Paralyzed, Petrified, Poisoned, Restrained, or Stunned. For 1 minute, those creatures also have advantage on saves against those same conditions.For 1 minute, you become an unyielding force. You can’t be knocked prone, grappled, restrained, paralyzed, stunned, or moved against your will. Whenever you hit a creature with a melee attack, you may push it 10 feet or knock it prone. The ground cracks beneath your steady steps.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_master_essence_just_passing_by",
    name: "Just Passing By",
    description: "As a reaction, you dissolve into wind until the start of your next turn, passing through solid objects, becoming immune to nonmagical slashing, piercing, and bludgeoning damage and resistant to magical slashing, piercing, and bludgeoning damage.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_master_essence_lunar_wind_spiral",
    name: "Lunar Wind Spiral",
    description: "As an Action, you target a point within 150 feet; a cylinder of swirling, moonlight-infused winds erupts in a 30-foot radius and 60-foot height. When the spiral appears, each creature in the area must make a Constitution saving throw against your essence ability save DC, taking 6d8 Radiant damage on a failed save and being lifted 20 feet into the air until the start of its next turn. On a successful save, they take half damage and are not lifted. The effect lasts for 1 minute. Any creature that starts its turn in the area or enters it for the first time on a turn must make the saving throw, taking 3d6 Radiant damage on a failed save, or half on a successful one, but it is not lifted. You can use a Bonus Action on a subsequent turn to move the area of effect by up to 30 feet.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "wind_master_essence_waning_moon_sabers",
    name: "Waning Moon Sabers",
    description: "As a bonus action, launch up to three crescent-shaped energy blades that travel 150 feet. Each saber makes a ranged spell attack for 1d4 + 1 Radiant damage. On a hit, the target must make a Constitution saving throw or be blinded until the end of their next turn as moonlight sears their vision. On a critical hit, the target automatically fails the saving throw. The sabers curve around cover, ignoring half and three-quarters cover.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  }
];

export const airCantrips = [
  {
    id: "wind_cantrip_gust",
    name: "Gust",
    description: "https://5e.tools/spells.html#gust_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "wind_cantrip_thunderclap",
    name: "Thunderclap",
    description: "https://5e.tools/spells.html#thunderclap_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "wind_cantrip_air_bubble",
    name: "Air Bubble",
    description: "https://5e.tools/spells.html#air%20bubble_eepc",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "wind_cantrip_retrieve",
    name: "Retrieve",
    description: "https://5e.tools/spells.html#retrieve_obojimatallgrass",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const airSpells = [
  {
    id: "wind_1st_level_fog_cloud",
    name: "Fog Cloud",
    description: "https://5e.tools/spells.html#fog%20cloud_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_1st_level_feather_fall",
    name: "Feather Fall",
    description: "https://5e.tools/spells.html#feather%20fall_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_1st_level_jump",
    name: "Jump",
    description: "https://5e.tools/spells.html#jump_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_1st_level_thunderwave",
    name: "Thunderwave",
    description: "https://5e.tools/spells.html#thunderwave_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_1st_level_warding_wind",
    name: "Warding Wind",
    description: "https://5e.tools/spells.html#warding%20wind_xge",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_2nd_level_misty_step",
    name: "Misty Step",
    description: "https://5e.tools/spells.html#misty%20step_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_2nd_level_dust_devil",
    name: "Dust Devil",
    description: "https://5e.tools/spells.html#dust%20devil_xge",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_2nd_level_gust_of_wind",
    name: "Gust of Wind",
    description: "https://5e.tools/spells.html#gust%20of%20wind_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_2nd_level_shatter",
    name: "Shatter",
    description: "https://5e.tools/spells.html#shatter_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_2nd_level_silence",
    name: "Silence",
    description: "https://5e.tools/spells.html#silence_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_fly",
    name: "Fly",
    description: "https://5e.tools/spells.html#fly_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_gaseous_form",
    name: "Gaseous Form",
    description: "https://5e.tools/spells.html#gaseous%20form_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_stinking_cloud",
    name: "Stinking Cloud",
    description: "https://5e.tools/spells.html#stinking%20cloud_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_wind_wall",
    name: "Wind Wall",
    description: "https://5e.tools/spells.html#wind%20wall_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_haste",
    name: "Haste",
    description: "https://5e.tools/spells.html#haste_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_5th_level_cloudkill",
    name: "Cloudkill",
    description: "https://5e.tools/spells.html#cloudkill_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_5th_level_cone_of_cold",
    name: "Cone of Cold",
    description: "https://5e.tools/spells.html#cone%20of%20cold_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_5th_level_control_winds",
    name: "Control Winds",
    description: "https://5e.tools/spells.html#control%20winds_xge",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_6th_level_investiture_of_wind",
    name: "Investiture of Wind",
    description: "https://5e.tools/spells.html#investiture%20of%20wind_xge",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_6th_level_otilukes_freezing_sphere",
    name: "Otiluke's Freezing Sphere",
    description: "https://5e.tools/spells.html#otiluke's%20freezing%20sphere_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_6th_level_wind_walk",
    name: "Wind Walk",
    description: "https://5e.tools/spells.html#wind%20walk_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_7th_level_etherealness",
    name: "Etherealness",
    description: "https://5e.tools/spells.html#etherealness_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_7th_level_reverse_gravity",
    name: "Reverse Gravity",
    description: "https://5e.tools/spells.html#reverse%20gravity_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_7th_level_whirlwind",
    name: "Whirlwind",
    description: "https://www.dandwiki.com/wiki/Whirlwind_(5e_Spell)",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_8th_level_incendiary_cloud",
    name: "Incendiary Cloud",
    description: "https://5e.tools/spells.html#incendiary%20cloud_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_8th_level_control_weather",
    name: "Control Weather",
    description: "https://5e.tools/spells.html#control%20weather_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_9th_level_storm_of_vengeance",
    name: "Storm of Vengeance",
    description: "https://5e.tools/spells.html#storm%20of%20vengeance_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_1st_level_cacophonic_shield",
    name: "Cacophonic Shield",
    description: "https://5e.tools/spells.html#cacophonic%20shield_obojimatallgrass",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_freedom_of_the_winds",
    name: "Freedom of the Winds",
    description: "https://5e.tools/spells.html#freedom%20of%20the%20winds_tdcsr",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_5th_level_mass_levitate",
    name: "Mass Levitate",
    description: "https://5e.tools/spells.html#mass%20levitate_obojimatallgrass",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  }
];
