export const airAbilities = [
  {
    id: 'air_initiate_gale_force_strike',
    name: 'Gale Force Strike',
    description: 'When you hit a creature of your size or smaller, or any creature one size category larger than you, with a weapon, you can create a gust of wind that forces the creature to make a Strength saving throw. On a failed save, the creature is pushed 10 feet away from you. The distance increases by an additional 10 feet at 5th Adept level (20 feet), 9th Master level (30 feet), 13th Grandmaster level (40 feet), and 17th Great-grandmaster level (50 feet). This effect can be used once per turn.',
    tier: 'initiate',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_initiate_misty_escape',
    name: 'Misty Escape',
    description: 'When you take damage, you can use your reaction to turn into a cloud of mist, causing the attack to miss. You must spend a spell slot of 1st level or higher to use this ability.',
    tier: 'initiate',
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_initiate_mistbound_step',
    name: 'Mistbound Step',
    description: 'The Misty Step spell does not consume a spell slot if you begin or end your movement in a heavily obscured area.',
    tier: 'initiate',
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_initiate_misty_veil',
    name: 'Misty Veil',
    description: 'You can create a shroud of mist around you that obscures your appearance, granting advantage on Stealth checks to hide and disadvantage on Insight checks to discern your true intentions. This effect lasts for 1 hour.',
    tier: 'initiate',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_initiate_wind_sprint',
    name: 'Wind Sprint',
    description: 'You can double your movement speed for 1 minute.',
    tier: 'initiate',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_initiate_thunderous_roar',
    name: 'Thunderous Roar',
    description: 'You can let out a powerful roar that creates a shockwave, forcing all creatures within 10 feet to make a Constitution saving throw or be pushed 10 feet away from you and become deafened for 1 minute.',
    tier: 'initiate',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_initiate_sound_analysis',
    name: 'Sound Analysis',
    description: 'You can accurately determine the source and direction of any sound within 300 feet of you. This ability can be used to track creatures or detect hidden enemies. It provides you advantage on Wisdom (Perception) checks related to sound.',
    tier: 'initiate',
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_adept_echoing_footsteps',
    name: 'Echoing Footsteps',
    description: 'You can move with such speed and silence that your footsteps echo faintly. You gain advantage on Stealth checks, and creatures within 10 feet of you have disadvantage on Wisdom (Perception) checks to hear you. This effect lasts for 10 minutes.',
    tier: 'adept',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_adept_thunderstep',
    name: 'Thunderstep',
    description: 'You can use a bonus action to make a sudden, loud noise, creating a brief but intense thunderclap that can be heard up to 300 feet away. Creatures within 30 feet of you must make a Constitution saving throw or be stunned until the end of your next turn. This ability’s range increases by 10 feet when you reach 9th Master level (40 feet), 11th Grandmaster level (50 feet), and 17th Great-Grandmaster level (60 feet).',
    tier: 'adept',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_adept_calm_breeze',
    name: 'Calm Breeze',
    description: 'You can use a bonus action to create a soothing breeze that relaxes and calms creatures within a 30-foot radius, providing them with advantage on saving throws against being frightened or charmed. This effect lasts for 10 minutes.',
    tier: 'adept',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
   {
    id: 'air_adept_whispering_winds',
    name: 'Whispering Winds',
    description: 'You can use your action to send a message carried by the wind to any creature within 1 mile of you. The message is heard as a whisper by the intended recipient. This ability allows for secret communications or covert information exchange.',
    tier: 'adept',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_adept_wind_barrier',
    name: 'Wind Barrier',
    description: 'As a reaction to being targeted by an attack or harmful spell, you can summon a barrier of wind around you. You gain a +2 bonus to AC and saving throws until the start of your next turn. Additionally, ranged weapon attacks against you have disadvantage.',
    tier: 'adept',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: 'air_adept_cyclone_step',
    name: 'Cyclone Step',
    description: 'When you use the Dash action, you can create a swirling vortex of wind around you. Creatures within 5 feet of your path must make a Strength saving throw or be knocked prone. The wind dissipates at the end of your movement.',
    tier: 'adept',
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
 ];

 export const airCantrips = [
  {
    id: 'air_cantrip_gust',
    name: 'Gust',
    description: 'https://5e.tools/spells.html#gust_xge',
    tier: 'cantrip',
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: 'air_cantrip_thunderclap',
    name: 'Thunderclap',
    description: 'https://5e.tools/spells.html#thunderclap_xge',
    tier: 'cantrip',
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
 ];

 export const airSpells = [
  {
    id: 'air_1st_level_fog_cloud',
    name: 'Fog Cloud',
    description: 'https://5e.tools/spells.html#fog%20cloud_xphb',
    tier: '1st',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_1st_level_feather_fall',
    name: 'Feather Fall',
    description: 'https://5e.tools/spells.html#feather%20fall_xphb',
    tier: '1st',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_1st_level_jump',
    name: 'Jump',
    description: 'https://5e.tools/spells.html#jump_xphb',
    tier: '1st',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_1st_level_thunderwave',
    name: 'Thunderwave',
    description: 'https://5e.tools/spells.html#thunderwave_xphb',
    tier: '1st',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_1st_level_warding_wind',
    name: 'Warding Wind',
    description: 'https://5e.tools/spells.html#warding%20wind_xge',
    tier: '1st',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_2nd_level_misty_step',
    name: 'Misty Step',
    description: 'https://5e.tools/spells.html#misty%20step_xphb',
    tier: '2nd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_2nd_level_dust_devil',
    name: 'Dust Devil',
    description: 'https://5e.tools/spells.html#dust%20devil_xge',
    tier: '2nd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_2nd_level_gust_of_wind',
    name: 'Gust of Wind',
    description: 'https://5e.tools/spells.html#gust%20of%20wind_xphb',
    tier: '2nd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_2nd_level_shatter',
    name: 'Shatter',
    description: 'https://5e.tools/spells.html#shatter_xphb',
    tier: '2nd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_2nd_level_silence',
    name: 'Silence',
    description: 'https://5e.tools/spells.html#silence_xphb',
    tier: '2nd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_3rd_level_fly',
    name: 'Fly',
    description: 'https://5e.tools/spells.html#fly_xphb',
    tier: '3rd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_3rd_level_gaseous_form',
    name: 'Gaseous Form',
    description: 'https://5e.tools/spells.html#gaseous%20form_xphb',
    tier: '3rd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_3rd_level_stinking_cloud',
    name: 'Stinking Cloud',
    description: 'https://5e.tools/spells.html#stinking%20cloud_xphb',
    tier: '3rd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_3rd_level_wind_wall',
    name: 'Wind Wall',
    description: 'https://5e.tools/spells.html#wind%20wall_xphb',
    tier: '3rd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: 'air_3rd_level_haste',
    name: 'Haste',
    description: 'https://5e.tools/spells.html#haste_xphb',
    tier: '3rd',
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
 ];
