export const earthAbilities = [
    {
      id: 'earth_initiate_stonecunning',
      name: 'Stonecunning',
      description: 'Gain proficiency in History. If already proficient, add double your proficiency bonus to History checks related to the origin of stonework.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_initiate_miners_touch',
      name: 'Miner\'s Touch',
      description: 'Gain proficiency with mason’s tools and miner’s tools.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_initiate_rock_whisperer',
      name: 'Rock Whisperer',
      description: 'You can communicate simple ideas with earth elementals and creatures of stone.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_initiate_earth_sense',
      name: 'Earth Sense',
      description: 'You have advantage on Survival and Perception checks to navigate underground or in rocky terrain.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_initiate_stone_fist',
      name: 'Stone Fist',
      description: 'Your unarmed strikes deal 1d6 bludgeoning damage and count as magical for overcoming resistance and immunity. The damage dice increase to 1d8 at 5th Adept level, 1d10 at 9th Master level, and 1d12 at 11th Grandmaster level.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_initiate_pebble_barrage',
      name: 'Pebble Barrage',
      description: 'As an action, you hurl a handful of pebbles at creatures within 30 feet. Make a ranged spell attack for each pebble (up to 3 pebbles), each targeting any creature of your choice within range. Each hit deals 1d4 bludgeoning damage. If the same target is hit by three consecutive pebbles in the same turn, it must succeed on a Strength saving throw or be knocked prone. The number of pebbles you can hurl increases by 1 when you reach 5th Adept level (4 pebbles), 9th Master level (5 pebbles), 13th Grandmaster level (6 pebbles), and 17th Great-grandmaster level (7 pebbles).',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_adept_earthen_resilience',
      name: 'Earthen Resilience',
      description: 'Gain proficiency in Constitution saving throws.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_adept_terramancer',
      name: 'Terramancer',
      description: 'Gain expertise (double proficiency bonus) in Athletics when performing tasks involving lifting, pushing, or pulling heavy objects made of stone or earth.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_adept_stone_camouflage',
      name: 'Stone Camouflage',
      description: 'You have advantage on Stealth checks to hide in rocky terrain or against stone surfaces.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_adept_earthen_grasp',
      name: 'Earthen Grasp',
      description: 'As an action to cause the ground to grasp a creature within 30 feet, restraining it for 1 minute. The target can make a Strength saving throw at the end of each of its turns to break free.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_adept_stone_armor',
      name: 'Stone Armor',
      description: 'As a bonus action, you can encase yourself in a layer of stone, granting you resistance to bludgeoning, piercing, and slashing damage for 1 minute.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'earth_adept_sandstorm',
      name: 'Sandstorm',
      description: 'As an action, you create a swirling storm of sand in a 20-foot radius centred on you. Each creature in the area must make a Constitution saving throw, taking 3d6 slashing damage on a failed save and becoming blinded until the end of their next turn, or half as much damage on a successful save. The storm lasts for 1 minute. The area is difficult terrain, any creature that starts its turn within the storm takes 1d6 damage. This ability’s range increases by 10-foot when you reach 9th Master level (30-foot radius), 13th Grandmaster level (40-foot radius) and 17th Great-grandmaster level (50-foot radius).',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
   ];
  
   export const earthCantrips = [
    {
      id: 'earth_cantrip_magic_stone',
      name: 'Magic Stone',
      description: 'https://5e.tools/spells.html#magic%20stone_xge',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'earth_cantrip_mold_earth',
      name: 'Mold Earth',
      description: 'https://5e.tools/spells.html#mold%20earth_xge',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
   ];
  
   export const earthSpells = [
    {
      id: 'earth_1st_level_earth_tremor',
      name: 'Earth Tremor',
      description: 'https://5e.tools/spells.html#earth%20tremor_xge',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'earth_2nd_level_earthbind',
      name: 'Earthbind',
      description: 'https://5e.tools/spells.html#earthbind_xge',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'earth_2nd_level_maximilians_earthen_grasp',
      name: 'Maximilian\'s Earthen Grasp',
      description: 'https://5e.tools/spells.html#maximilian\'s%20earthen%20grasp_xge',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'earth_3rd_level_erupting_earth',
      name: 'Erupting Earth',
      description: 'https://5e.tools/spells.html#erupting%20earth_xge',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'earth_3rd_level_wall_of_sand',
      name: 'Wall of Sand',
      description: 'https://5e.tools/spells.html#wall%20of%20sand_xge',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'earth_3rd_level_meld_into_stone',
      name: 'Meld into Stone',
      description: 'https://5e.tools/spells.html#meld%20into%20stone_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'earth_4th_level_stone_shape',
      name: 'Stone Shape',
      description: 'https://5e.tools/spells.html#stone%20shape_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'earth_4th_level_stoneskin',
      name: 'Stoneskin',
      description: 'https://5e.tools/spells.html#stoneskin_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
   ];
