export const metalAbilities = [
  {
    id: "metal_initiate_metalcrafting",
    name: "Metalcrafting",
    description: "You gain proficiency with smith's tools.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_initiate_magnetic_attraction",
    name: "Magnetic Attraction",
    description: "As a bonus action, you can pull or push a metal object weighing up to 10 pounds within 60 feet, moving it up to 10 feet toward or away from you. If the object is carried or worn by a creature, that creature must succeed on a Strength saving throw against your spell save DC. On a failed save, you can choose to either move the creature along with the object or detach the object from the creature. For objects heavier or larger than the base limit, you can attempt to move them by making an Intelligence (Arcana) check against a DC determined by the object’s weight and size. Objects far beyond your power are immovable.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_initiate_metal_sense",
    name: "Metal Sense",
    description: "You can detect the presence of metal within 30 feet of you. You sense the type and general location of metal objects, including hidden compartments or concealed weapons.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_initiate_keen_edge",
    name: "Keen Edge",
    description: "As a bonus action, you can temporarily sharpen a weapon or ammunition, granting it a +1 bonus to attack and damage rolls for the next hour.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_initiate_magnetic_focus",
    name: "Magnetic Focus",
    description: "As a reaction, you can magnetically attract a metal weapon you can see within 30 feet of you to your hand, provided it's not being worn or carried by another creature.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_initiate_metallic_echo",
    name: "Metallic Echo",
    description: "When you strike a metallic object with a melee weapon, you can create a ringing sound that echoes in a 10-foot radius. Creatures in the area must succeed on a Constitution saving throw or be deafened until the end of their next turn.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_adept_enhanced_armor",
    name: "Enhanced Armor",
    description: "You can spend 10 minutes to reinforce any armor. For the next hour, you gain resistance to one type of damage (chosen when you use this ability) while wearing armor.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_adept_gemsight",
    name: "Gemsight",
    description: "You gain expertise in Perception checks to locate hidden gemstones or precious minerals. When you find such items, you can appraise their value with a successful Intelligence (Investigation) check.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_adept_magnetic_shield",
    name: "Magnetic Shield",
    description: "As a reaction when you are hit by an attack, you can create a magnetic field that reduces the damage by 1d10 + your Constitution modifier. If the attacker is wielding a metal weapon, they must make a Strength saving throw or be disarmed.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_adept_steel_tornado",
    name: "Steel Tornado",
    description: "As an action, you can create a whirlwind of metallic shards in a 30-foot radius around you. Creatures within the cylinder must make a Dexterity saving throw. On a failed save, a creature takes 7d6 slashing damage, or half as much damage on a successful save.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "metal_master_weight_of_lives",
    name: "Weight of Lives",
    description: "As an action, target a creature within 60 feet to make a Charisma saving throw. They take 2d8 force damage per karmic debt you discern (up to 18d8). On a failed save, they're restrained for rounds equal to debts discerned. On a success, they take half damage, have speed halved, and you gain temporary hit points equal to damage dealt.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  }
];

export const metalCantrips = [
  {
    id: "metal_cantrip_blade_ward",
    name: "Blade Ward",
    description: "https://5e.tools/spells.html#blade%20ward_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "metal_cantrip_sword_burst",
    name: "Sword Burst",
    description: "https://5e.tools/spells.html#sword%20burst_tce",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const metalSpells = [
  {
    id: "metal_2nd_level_cloud_of_daggers",
    name: "Cloud of Daggers",
    description: "https://5e.tools/spells.html#cloud%20of%20daggers_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_2nd_level_heat_metal",
    name: "Heat Metal",
    description: "https://5e.tools/spells.html#heat%20metal_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_4th_level_fabricate",
    name: "Fabricate",
    description: "https://5e.tools/spells.html#fabricate_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_5th_level_animate_objects",
    name: "Animate Objects",
    description: "https://5e.tools/spells.html#animate%20objects_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_6th_level_blade_barrier",
    name: "Blade Barrier",
    description: "https://5e.tools/spells.html#blade%20barrier_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_7th_level_mordenkainens_sword",
    name: "Mordenkainen's Sword",
    description: "https://5e.tools/spells.html#mordenkainen's%20sword_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_9th_level_foresight",
    name: "Foresight",
    description: "https://5e.tools/spells.html#foresight_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_1st_level_arcane_aegis",
    name: "Arcane Aegis",
    description: "https://5e.tools/spells.html#arcane%20aegis_obojimatallgrass",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_1st_level_whelm_weapon",
    name: "Whelm Weapon",
    description: "https://5e.tools/spells.html#whelm%20weapon_obojimatallgrass",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_3rd_level_enspelled_armament",
    name: "Enspelled Armament",
    description: "https://5e.tools/spells.html#enspelled%20armament_obojimatallgrass",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_5th_level_pillar_of_force",
    name: "Pillar of Force",
    description: "https://5e.tools/spells.html#pillar%20of%20force_obojimatallgrass",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_9th_level_pogmos_pot",
    name: "Pogmo's Pot",
    description: "https://5e.tools/spells.html#pogmo's%20pot_obojimatallgrass",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  }
];
