export const poisonAbilities = [
  {
    id: "poison_initiate_venomous_touch",
    name: "Venomous Touch",
    description: "As an action, you can imbue your touch with a mild poison. A creature you touch must make a Constitution saving throw against your spell save DC or become poisoned for 1 minute. While poisoned this way, the creature takes 1d6 poison damage at the start of each of its turns until it succeeds a saving throw. The poison ends early if the creature receives any kind of healing.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_herbalists_knowledge",
    name: "Herbalist’s Knowledge",
    description: "You gain proficiency with the Medicine skill and advantage on checks to identify or use medicinal herbs and poisons.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_strength_booster",
    name: "Strength Booster",
    description: "As a bonus action, you can drink a mutagen to gain advantage on Strength-based ability checks for 10 minutes. Additionally, you gain a +2 bonus to Strength-based attack rolls during this time.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_quickening_draught",
    name: "Quickening Draught",
    description: "As a bonus action, by drinking a specially prepared potion, you gain an additional 10 feet of movement speed for 10 minutes and advantage on Dexterity-based ability checks.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_enchanting_perfume",
    name: "Enchanting Perfume",
    description: "As an action, you can apply a specially crafted perfume that enhances your charm and charisma. For the next hour, you gain a 1d4 bonus to Charisma (Persuasion) and Charisma (Deception) checks against humanoids.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_venomous_bite",
    name: "Venomous Bite (Gio)",
    description: "When you take the Attack action, you can replace one of your attacks with a bite attack, imbuing it with a potent venom. Make a melee weapon attack against a creature within your reach. On a hit, the target takes 1d12 piercing damage and must succeed on a Constitution saving throw against your spell save DC or become poisoned for 1 minute. The bite attack is considered magical for the purposes of overcoming resistance and immunity to nonmagical attacks.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_vital_essence_sublimation_i",
    name: "Vital Essence Sublimation I (Nilo)",
    description: "When you harvest the blood of a fallen creature with a Challenge Rating (CR) of 4 or lower, you can store its essence, preserving a fragment of its power. You can retain the essence of up to one creature at a time. For each stored essence, you can use one ability the creature possessed, provided it is an action, reaction, or bonus action and does not require spell slots or legendary actions. Once used, an essence is expended and must be replenished by harvesting fresh blood. Stored essences do not expire until used.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_venomous_strike",
    name: "Venomous Strike",
    description: "As a bonus action, you can coat a weapon with a potent poison. The next attack you make with that weapon deals an additional 3d6 poison damage on a hit. The target must also succeed on a Constitution saving throw or be poisoned for 1 minute.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_hallucinogenic_trance",
    name: "Hallucinogenic Trance",
    description: "As an action, you can force a creature within 30 feet to make a Wisdom saving throw. On a failed save, the creature is subjected to vivid hallucinations for 1 minute, during which it has disadvantage on attack rolls, ability checks and mental saving throws. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_enhanced_mutagen",
    name: "Enhanced Mutagen",
    description: "As a bonus action, when you drink a mutagen, you can choose one ability score (Strength, Dexterity, or Constitution) to gain a +2 bonus for 10 minutes.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_pill_of_focus",
    name: "Pill of Focus",
    description: "As a bonus action, you can consume a pill to gain advantage on concentration checks for the next hour.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_venomous_precision",
    name: "Venomous Precision",
    description: "When attacking a creature that is poisoned, you have advantage on attack rolls against that creature.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_vital_essence_sublimation_ii",
    name: "Vital Essence Sublimation II (Nilo)",
    description: "Harvest essence from fallen creatures of CR 8 or lower. Store up to 2 essences at a time.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  }
];

export const poisonCantrips = [
  {
    id: "poison_cantrip_poison_spray",
    name: "Poison Spray",
    description: "https://5e.tools/spells.html#poison%20spray_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "poison_cantrip_infestation",
    name: "Infestation",
    description: "https://5e.tools/spells.html#infestation_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const poisonSpells = [
  {
    id: "poison_1st_level_ray_of_sickness",
    name: "Ray of Sickness",
    description: "https://5e.tools/spells.html#ray%20of%20sickness_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_1st_level_purify_food_and_drink",
    name: "Purify Food and Drink",
    description: "https://5e.tools/spells.html#purify%20food%20and%20drink_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_2nd_level_enlarge_reduce",
    name: "Enlarge/Reduce",
    description: "https://5e.tools/spells.html#enlarge%2freduce_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_2nd_level_protection_from_poison",
    name: "Protection from Poison",
    description: "https://5e.tools/spells.html#protection%20from%20poison_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_3rd_level_bestow_curse",
    name: "Bestow Curse",
    description: "https://5e.tools/spells.html#bestow%20curse_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_5th_level_cloudkill",
    name: "Cloudkill",
    description: "https://5e.tools/spells.html#cloudkill_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_5th_level_contagion",
    name: "Contagion",
    description: "https://5e.tools/spells.html#contagion_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_6th_level_circle_of_death",
    name: "Circle of Death",
    description: "https://5e.tools/spells.html#circle%20of%20death_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_7th_level_prismatic_spray",
    name: "Prismatic Spray",
    description: "https://5e.tools/spells.html#prismatic%20spray_phb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_9th_level_prismatic_wall",
    name: "Prismatic Wall",
    description: "https://5e.tools/spells.html#prismatic%20wall_phb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  }
];
