export const poisonAbilities = [
  {
    id: "poison_initiate_venomous_touch",
    name: "Venomous Touch",
    description: "As an action, you can imbue your touch with a mild poison. A creature you touch must make a Constitution saving throw against your spell save DC or become poisoned for 1 minute. While poisoned this way, the creature takes 1d6 poison damage at the start of each of its turns until it succeeds a saving throw. The poison ends early if the creature receives any kind of healing.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_herbalists_knowledge",
    name: "Herbalist’s Knowledge",
    description: "You gain proficiency with the Medicine skill and advantage on checks to identify or use medicinal herbs and poisons.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_strength_booster",
    name: "Strength Booster",
    description: "As a bonus action, you can drink a mutagen to gain a 1d4 bonus to strength based ability checks for 10 minutes.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_quickening_draught",
    name: "Quickening Draught",
    description: "As a bonus action, by drinking a specially prepared potion, you gain an additional 10 feet of movement speed for 10 minutes.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_enchanting_perfume",
    name: "Enchanting Perfume",
    description: "As an action, you can apply a specially crafted perfume that enhances your charm and charisma. For the next hour, you gain a 1d4 bonus to Charisma (Persuasion) and Charisma (Deception) checks.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_venomous_bite",
    name: "Venomous Bite (Gio)",
    description: "When you take the Attack action, you can replace one of your attacks with a bite attack, imbuing it with a potent venom. Make a melee weapon attack against a creature within your reach. On a hit, the target takes 1d12 piercing damage and must succeed on a Constitution saving throw against your spell save DC or become poisoned for 1 minute. The bite attack is considered magical for the purposes of overcoming resistance and immunity to nonmagical attacks.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_initiate_vital_essence_sublimation_i",
    name: "Vital Essence Sublimation I (Nilo)",
    description: "When you harvest the blood of a fallen creature, you can distill its essence into a single potion. You may either extract one of its abilities (action, bonus action, or reaction) and bottle it as a potion, or create a potion whose rarity depends on the creature’s level. Roll a d100; on a failure, the attempt is wasted.\n\n- Initiate: Common (no failure chance)\n- Adept: Uncommon (20% failure)\n- Master: Rare (40% failure)\n- Grandmaster: Very Rare (80% failure)\n- Great Grandmaster: Legendary (100% failure)\n\nYou can hold only one distilled essence at a time. Potions do not expire.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_toxic_skin_secretion_1",
    name: "Toxic Skin Secretion I",
    description: "Once per turn, when a creature hits you with a melee attack, that creature must succeed on a Constitution saving throw against your spell save DC or become poisoned until the end of its next turn.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_venomous_strike",
    name: "Venomous Strike",
    description: "As a bonus action, you can coat a weapon with a potent poison. The next attack you make with that weapon deals an additional 2d6 poison damage on a hit. The target must also succeed on a Constitution saving throw or be poisoned for 1 minute.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_hallucinogenic_trance",
    name: "Hallucinogenic Trance",
    description: "As a bonus action, you can target one poisoned creature within 30 feet. The target must succeed on a Wisdom saving throw or be subjected to vivid hallucinations for the duration of its poisoned condition. While affected by these hallucinations, the creature has disadvantage on Intelligence, Wisdom, and Charisma saving throws and ability checks. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_vestibular_trance",
    name: "Vestibular Trance",
    description: "As a bonus action, you can target one poisoned creature within 30 feet. The target must succeed on a Constitution saving throw or be overwhelmed by distorted bodily sensations (nausea, vertigo, and loss of coordination) for the duration of its poisoned condition. While affected, the creature has disadvantage on Strength, Dexterity, and Constitution saving throws and ability checks. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_enhanced_mutagen",
    name: "Mutagen Formula (Strength)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Strength for 10 minutes, and you take a –2 penalty to Intelligence for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_enhanced_mutagen_dexterity",
    name: "Mutagen Formula (Dexterity)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Dexterity for 10 minutes, and you take a –2 penalty to Wisdom for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_enhanced_mutagen_constitution",
    name: "Mutagen Formula (Constitution)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Constitution for 10 minutes, and you take a –2 penalty to Charisma for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_enhanced_mutagen_intelligence",
    name: "Mutagen Formula (Intelligence)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Intelligence for 10 minutes, and you take a –2 penalty to Strength for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_enhanced_mutagen_wisdom",
    name: "Mutagen Formula (Wisdom)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Wisdom for 10 minutes, and you take a –2 penalty to Dexterity for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_enhanced_mutagen_charisma",
    name: "Mutagen Formula (Charisma)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Charisma for 10 minutes, and you take a –2 penalty to Constitution for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_pill_of_focus",
    name: "Pill of Focus",
    description: "As a bonus action, you can consume a pill to gain advantage on concentration checks for the next hour.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_venomous_precision",
    name: "Venomous Precision",
    description: "When attacking a creature that is poisoned, you have advantage on attack rolls against that creature.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_moonlit_verdant_beam",
    name: "Moonlit Verdant Beam",
    description: "As an action, you fire a beam of toxic moonlight at a creature within 60 feet. Make a ranged spell attack. On a hit, the target takes 3d6 radiant damage + 3d6 poison damage and must make a Constitution saving throw against your spell save DC. On a failed save, the target is blinded and poisoned until the end of your next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_vital_essence_sublimation_ii",
    name: "Vital Essence Sublimation II (Nilo)",
    description: "Your failure chances are reduced: Common and Uncommon potions no longer fail, while higher rarity failure rates decrease (Rare 20%, Very Rare 60%, Legendary 80%).\nYou can now hold up to two distilled essences at a time.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_toxic_skin_secretion_2",
    name: "Toxic Skin Secretion II",
    description: "Once per turn, when a creature hits you with a melee attack, that creature must succeed on a Constitution saving throw against your spell save DC or become poisoned for 1 minute. On a failed save, the creature also takes poison damage equal to your proficiency bonus.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_toxic_skin_secretion_3",
    name: "Toxic Skin Secretion III",
    description: "Once per turn, when a creature hits you with a melee attack, that creature must succeed on a Constitution saving throw against your spell save DC. On a failed save, the creature becomes poisoned for 1 hour, takes poison damage equal to twice your proficiency bonus, and has its movement speed halved while poisoned this way.",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_master_vital_essence_sublimation_iii",
    name: "Vital Essence Sublimation III (Nilo)",
    description: "Your success improves further: Common, Uncommon, and Rare potions no longer fail; only Very Rare (40%) and Legendary (60%) can fail.\nYou can now hold up to three distilled essences at a time.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_master_essence_snake_horror",
    name: "Apex Toxinator",
    description: "As an Action, you channel the pure essence of poison to conjure a monstrous, hissing Snake Horror in an unoccupied space you can see within 30 feet. The creature is friendly to you and your companions, acts immediately after you in the initiative order, and remains for 1 hour, until it drops to 0 hit points, or until you dismiss it as an action.\nYou can now hold up to three distilled essences at a time.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  }
];

export const poisonCantrips = [
  {
    id: "poison_cantrip_infestation",
    name: "Infestation",
    description: "https://5e.tools/spells.html#infestation_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const poisonSpells = [
  {
    id: "poison_1st_level_ray_of_sickness",
    name: "Ray of Sickness",
    description: "https://5e.tools/spells.html#ray%20of%20sickness_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_1st_level_purify_food_and_drink",
    name: "Purify Food and Drink",
    description: "https://5e.tools/spells.html#purify%20food%20and%20drink_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_2nd_level_enlarge_reduce",
    name: "Enlarge/Reduce",
    description: "https://5e.tools/spells.html#enlarge%2freduce_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_2nd_level_protection_from_poison",
    name: "Protection from Poison",
    description: "https://5e.tools/spells.html#protection%20from%20poison_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_3rd_level_bestow_curse",
    name: "Bestow Curse",
    description: "https://5e.tools/spells.html#bestow%20curse_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_5th_level_cloudkill",
    name: "Cloudkill",
    description: "https://5e.tools/spells.html#cloudkill_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_5th_level_contagion",
    name: "Contagion",
    description: "https://5e.tools/spells.html#contagion_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_6th_level_circle_of_death",
    name: "Circle of Death",
    description: "https://5e.tools/spells.html#circle%20of%20death_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_7th_level_prismatic_spray",
    name: "Prismatic Spray",
    description: "https://5e.tools/spells.html#prismatic%20spray_phb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_9th_level_prismatic_wall",
    name: "Prismatic Wall",
    description: "https://5e.tools/spells.html#prismatic%20wall_phb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_2nd_level_swallow_magic",
    name: "Swallow Magic",
    description: "https://5e.tools/spells.html#swallow%20magic_obojimatallgrass",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_3rd_level_sylunes_viper",
    name: "Syluné's Viper",
    description: "https://5e.tools/spells.html#syluné's%20viper_frhof",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "poison_6th_level_investiture_of_venom",
    name: "Investiture of Venom",
    description: "https://5e.tools/spells.html#investiture%20of%20venom_obojimatallgrass",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  }
];
