export const waterAbilities = [
  {
    id: "water_initiate_echoes_of_the_deep",
    name: "Echoes of the Deep",
    description: "You can communicate with aquatic creatures or spirits of water, allowing you to understand their language and gain information about underwater locations or hidden treasures.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_initiate_ice_form",
    name: "Ice Form",
    description: "As a bonus action, you can turn your body into ice for 1 minute. You gain resistance to cold and fire damage and your movement speed is reduced by 10 feet.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_initiate_raincaller",
    name: "Raincaller",
    description: "You can call forth a light rain within a 30-foot radius centered on you for 10 minutes. This rain lightly obscures the area, granting disadvantage on Perception checks relying on sight and extinguishing fires.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_initiate_restorative_rain",
    name: "Restorative Rain",
    description: "As an action, you create a 20-foot radius of gentle rain centered on you that lasts for a number of rounds equal to your maximum Water essences. At the start of each of their turns while in the rain, they regain 1 hit point.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_initiate_frozen_insight",
    name: "Frozen Insight",
    description: "You can temporarily turn your thoughts into ice, allowing you to gain deep insight into a complex problem or puzzle. For 1 hour, you gain advantage on Intelligence checks related to solving mysteries or understanding arcane knowledge.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_tides_reflection_art_i",
    name: "Tide's Reflection Art I (Thalassios)",
    description: "As a bonus action, you summon a Water Clone in an unoccupied space you can see within 30 feet. The clone lasts for 1 minute or until destroyed. The clone is linked to your senses, allowing you to cast spells through it as if you were in its space. The clone has the following stats: Armor Class: Your spell save DC (8 + proficiency bonus + spellcasting modifier). Hit Points: Equal to half your hit point maximum. Speed: Equal to your swimming speed. Immunity: Cold damage. Resistance: Fire damage. Vulnerability: Lightning damage. As a bonus action, you can command the clone to move and take one of the following actions: Melee Spell Attack: Range 10 feet, dealing 1d8 + your spellcasting modifier cold damage. Ranged Spell Attack: Range 60 feet, dealing 1d6 + your spellcasting modifier cold damage. Take the Dash, Dodge, or Disengage action.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_aqua_agility",
    name: "Aqua Agility",
    description: "Your swimming speed equals your walking speed. Additionally, you gain the ability to breathe underwater and move through water at your normal speed without penalty.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_tide_of_emotions",
    name: "Tide of Emotions",
    description: "By channelling the ebb and flow of water, you can influence the emotions of others within a 30-foot radius. Choose one emotion (calm, fear, or joy); affected creatures must succeed on a Wisdom saving throw or be overwhelmed by that emotion for 1 hour.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_tidal_surge",
    name: "Tidal Surge",
    description: "You can summon a powerful wave of water that heals and revitalizes. As an action, you create a wave that washes over allies in a 30-foot radius, restoring hit points equal to 3d8 + your spellcasting ability modifier.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_rain_of_revelation",
    name: "Rain of Revelation",
    description: "You can summon a gentle, magical rain that grants clarity and insight to those who stand in it. Allies within a 20-foot radius can ask one question about their future or destiny, and you provide a vague but helpful answer based on your understanding of the world.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_glacial_shield",
    name: "Glacial Shield",
    description: "As a reaction, you can spend one spell slot and encase yourself in a barrier of ice, granting you temporary hit points equal to ten times the spell level used plus your spell casting modifier. This lasts for 1 hour.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_hydroportation",
    name: "Hydroportation",
    description: "As a bonus action, you can teleport up to 60 feet to a space you can see within a body of water or mist. You must be in contact with the water or mist to use this ability.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_tides_reflection_art_ii",
    name: "Tide's Reflection Art II (Thalassios)",
    description: "As a reaction, you can cause your one of your Water Clones to detonate, dealing cold damage equal to half of its maximum hit points in a 10-foot radius. Creatures in range must succeed on a Dexterity saving throw or take full damage, or half as much on a success. You can now summon two Water Clones at the same time, increasing the damage by one damage dice when they attack together.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_moonlit_verdant_beam",
    name: "Moonlit Verdant Beam",
    description: "As an action, you fire a beam of toxic moonlight at a creature within 60 feet. Make a ranged spell attack. On a hit, the target takes 3d6 radiant damage + 3d6 poison damage and must make a Constitution saving throw against your spell save DC. On a failed save, the target is blinded and poisoned until the end of your next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "poison_adept_draconic_regeneration_emerald_moon",
    name: "Draconic Regeneration of the Emerald Moon",
    description: "While under direct moonlight, you regain 1 hit point at the start of each of your turns. You can extend this regeneration to any creature within 60 feet by spending 1 essence point per creature at the start of your turn.",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_adept_tides_reflection_art_iii",
    name: "Tide's Reflection Art III (Thalassios)",
    description: "As a bonus action, you can instantly swap places with one of your Water Clones without provoking opportunity attacks. Additinonally, you can now summon three Water Clones at the same time, and they last for 10 minutes.",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_master_lunar_tide",
    name: "Lunar Tide",
    description: "As a reaction when you or creatures within 30 feet are subjected to a Dexterity saving throw against an ability that deals damage, you summon a protective wave of water guided by lunar force. All affected creatures reduce the damage taken by 2d8 + your spellcasting modifier. The water then dissipates harmlessly.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  },
  {
    id: "water_master_moonfall_condemnation",
    name: "Moonfall Condemnation",
    description: "As an Action, you target one creature within 120 feet. A pillar of concentrated moonlight descends, requiring a Dexterity saving throw against your essence ability save DC. On a failed save, the target takes 6d8 Radiant damage and 3d8 Cold damage, and is Restrained until the end of their next turn as lunar energy begins to calcify their limbs. On a successful save, they take half damage and are not Restrained. If this damage reduces the target to 50 hit points or fewer, they must immediately make a Constitution saving throw against your essence ability save DC. On a failed Constitution save, the creature is Petrified into moonstone",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
  }
];

export const waterCantrips = [
  {
    id: "water_cantrip_frostbite",
    name: "Frostbite",
    description: "https://5e.tools/spells.html#frostbite_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "water_cantrip_ray_of_frost",
    name: "Ray of Frost",
    description: "https://5e.tools/spells.html#ray%20of%20frost_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "water_cantrip_shape_water",
    name: "Shape Water",
    description: "https://5e.tools/spells.html#shape%20water_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const waterSpells = [
  {
    id: "water_1st_level_create_or_destroy_water",
    name: "Create or Destroy Water",
    description: "https://5e.tools/spells.html#create%20or%20destroy%20water_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_detect_poison_and_disease",
    name: "Detect Poison and Disease",
    description: "https://5e.tools/spells.html#detect%20poison%20and%20disease_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_fog_cloud",
    name: "Fog Cloud",
    description: "https://5e.tools/spells.html#fog%20cloud_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_grease",
    name: "Grease",
    description: "https://5e.tools/spells.html#grease_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_ice_knife",
    name: "Ice Knife",
    description: "https://5e.tools/spells.html#ice%20knife_xge",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_2nd_level_protection_from_poison",
    name: "Protection from Poison",
    description: "https://5e.tools/spells.html#protection%20from%20poison_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_2nd_level_snillocs_snowball_swarm",
    name: "Snilloc's Snowball Swarm",
    description: "https://5e.tools/spells.html#snilloc's%20snowball%20swarm_xge",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_2nd_level_misty_step",
    name: "Misty Step",
    description: "https://5e.tools/spells.html#misty%20step_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_sleet_storm",
    name: "Sleet Storm",
    description: "https://5e.tools/spells.html#sleet%20storm_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_tidal_wave",
    name: "Tidal Wave",
    description: "https://5e.tools/spells.html#tidal%20wave_xge",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_wall_of_water",
    name: "Wall of Water",
    description: "https://5e.tools/spells.html#wall%20of%20water_xge",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_water_breathing",
    name: "Water Breathing",
    description: "https://5e.tools/spells.html#water%20breathing_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_water_walk",
    name: "Water Walk",
    description: "https://5e.tools/spells.html#water%20walk_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_4th_level_control_water",
    name: "Control Water",
    description: "https://5e.tools/spells.html#control%20water_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_4th_level_ice_storm",
    name: "Ice Storm",
    description: "https://5e.tools/spells.html#ice%20storm_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_4th_level_vitriolic_sphere",
    name: "Vitriolic Sphere",
    description: "https://5e.tools/spells.html#vitriolic%20sphere_xge",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_4th_level_watery_sphere",
    name: "Watery Sphere",
    description: "https://5e.tools/spells.html#watery%20sphere_xge",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_5th_level_maelstrom",
    name: "Maelstrom",
    description: "https://5e.tools/spells.html#maelstrom_xge",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_6th_level_investiture_of_ice",
    name: "Investiture of Ice",
    description: "https://5e.tools/spells.html#investiture%20of%20ice_xge",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_6th_level_wall_of_ice",
    name: "Wall of Ice",
    description: "https://5e.tools/spells.html#wall%20of%20ice_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_8th_level_tsunami",
    name: "Tsunami",
    description: "https://5e.tools/spells.html#tsunami_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_9th_level_time_stop",
    name: "Time Stop",
    description: "https://5e.tools/spells.html#time%20stop_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_bubble_lift",
    name: "Bubble Lift",
    description: "https://5e.tools/spells.html#bubble%20lift_obojimatallgrass",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_frost_fingers",
    name: "Frost Fingers",
    description: "https://5e.tools/spells.html#frost%20fingers_idrotf",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_water_bullet",
    name: "Water Bullet",
    description: "https://5e.tools/spells.html#water%20bullet_obojimatallgrass",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_whelm_weapon",
    name: "Whelm Weapon",
    description: "https://5e.tools/spells.html#whelm%20weapon_obojimatallgrass",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_2nd_level_rimes_binding_ice",
    name: "Rime's Binding Ice",
    description: "https://5e.tools/spells.html#rime's%20binding%20ice_ftd",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_conjure_ocean",
    name: "Conjure Ocean",
    description: "https://5e.tools/spells.html#conjure%20ocean_obojimatallgrass",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_freedom_of_the_waves",
    name: "Freedom of the Waves",
    description: "https://5e.tools/spells.html#freedom%20of%20the%20waves_tdcsr",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_5th_level_alustriels_mooncloak",
    name: "Alustriel's Mooncloak",
    description: "https://5e.tools/spells.html#alustriel's%20mooncloak_frhof",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_6th_level_crustacean_form",
    name: "Crustacean Form",
    description: "https://5e.tools/spells.html#crustacean%20form_obojimatallgrass",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  }
];
