export const woodAbilities = [
    {
      id: 'wood_initiate_vine_manipulation',
      name: 'Vine Manipulation',
      description: 'You gain the ability to manipulate vines and roots within 30 feet of you. As an action, you can cause vines to emerge from the ground or surrounding vegetation to ensnare a creature or create barriers. The vines can grapple or restrain a creature (Strength saving throw) or create difficult terrain in a 10-foot square area for 1 minute.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_initiate_fertile_ground_resilience',
      name: 'Fertile Ground Resilience',
      description: 'When you are standing on or above fertile soil (such as grasslands, forests, or similar natural terrain), you can use your reaction to gain immunity to effects that would knock you prone or push you away. Additionally, while on such terrain, you gain advantage on saving throws against being grappled or restrained.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_initiate_thorny_defence',
      name: 'Thorny Defence',
      description: 'When a creature hits you with a melee attack, you can use your reaction to cause thorns to erupt from your skin. The attacker takes 4d4 piercing damage.',
      tier: 'initiate',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_initiate_woodcraft',
      name: 'Woodcraft',
      description: 'You gain proficiency with woodcarver’s tools and the ability to craft simple wooden items. You can create small wooden objects (e.g., a carved figurine, a simple tool) in 1 hour, provided you have access to suitable materials. You can also use your tools to make minor repairs to wooden objects.',
      tier: 'initiate',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_adept_plant_bond',
      name: 'Plant Bond',
      description: 'You can communicate with plants in a basic way. You understand their emotions and can ask simple questions (e.g., \"Where is the nearest source of water?\"). Plants can also provide you with basic information about their immediate surroundings.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_adept_woodland_stride',
      name: 'Woodland Stride',
      description: 'Moving through nonmagical plant life, such as undergrowth or vines, costs you no extra movement. You can also move through difficult terrain caused by plant life without penalty.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_adept_natures_insight',
      name: 'Nature’s Insight',
      description: 'You gain proficiency in Nature and Survival skills. If you are already proficient in either of these skills, you gain expertise, doubling your proficiency bonus for those skills.',
      tier: 'adept',
      isActive: false,
      isPassive: true,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_adept_verdant_armor',
      name: 'Verdant Armor',
      description: 'As a bonus action, you encase yourself in a layer of living wood and leaves for 1 minute. At the start of each of your turns while this armor is active, you regain hit points equal to 1d6.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_adept_needle_barrage',
      name: 'Needle Barrage',
      description: 'You unleash a torrent of wooden needles that streak toward one creature you can see within range. The target makes a Dexterity saving throw. On a failure: 8d4 piercing damage and is riddled with needles, reducing its speed by half until the end of your next turn. On a success: half damage and no speed reduction.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
    {
      id: 'wood_adept_tree_form',
      name: 'Tree Form',
      description: 'You can use your action to transform into a treelike creature. While in this form, you gain the following benefits:  - AC 17: Your skin becomes as tough as bark. - Hit Points: You gain temporary hit points equal to twice your level. - Attacks: You can make a slam attack with +6 to hit, dealing 2d6+4 bludgeoning damage. - Rooted: You can root yourself to the ground. While rooted, you cannot move, but you have advantage on Strength and Constitution saving throws, and any creature that starts its turn within 5 feet of you takes 1d6 bludgeoning damage. - This form lasts for 1 minute or until you use your action to revert to your normal form. You can use this feature once per long rest.',
      tier: 'adept',
      isActive: true,
      isPassive: false,
      isSpell: false,
      isCantrip: false,
    },
   ];
  
   export const woodCantrips = [
    {
      id: 'wood_cantrip_thorn_whip',
      name: 'Thorn Whip',
      description: 'https://5e.tools/spells.html#thorn%20whip_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'wood_cantrip_shillelagh',
      name: 'Shillelagh',
      description: 'https://5e.tools/spells.html#shillelagh_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
    {
      id: 'wood_cantrip_shillelagh_repeat',
      name: 'Shillelagh',
      description: 'https://5e.tools/spells.html#shillelagh_xphb',
      tier: 'cantrip',
      isActive: false,
      isPassive: false,
      isSpell: false,
      isCantrip: true,
    },
   ];
  
   export const woodSpells = [
    {
      id: 'wood_1st_level_purify_food_and_drink',
      name: 'Purify Food and Drink',
      description: 'https://5e.tools/spells.html#purify%20food%20and%20drink_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_1st_level_animal_friendship',
      name: 'Animal Friendship',
      description: 'https://5e.tools/spells.html#animal%20friendship_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_1st_level_entangle',
      name: 'Entangle',
      description: 'https://5e.tools/spells.html#entangle_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_1st_level_find_familiar',
      name: 'Find Familiar',
      description: 'https://5e.tools/spells.html#find%20familiar_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_1st_level_goodberry',
      name: 'Goodberry',
      description: 'https://5e.tools/spells.html#goodberry_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_1st_level_speak_with_animals',
      name: 'Speak with Animals',
      description: 'https://5e.tools/spells.html#speak%20with%20animals_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_1st_level_unseen_servant',
      name: 'Unseen Servant',
      description: 'https://5e.tools/spells.html#unseen%20servant_xphb',
      tier: '1st',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_2nd_level_pass_without_trace',
      name: 'Pass without Trace',
      description: 'https://5e.tools/spells.html#pass%20without%20trace_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_2nd_level_lesser_restoration',
      name: 'Lesser Restoration',
      description: 'https://5e.tools/spells.html#lesser%20restoration_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_2nd_level_animal_friendship_repeat',
      name: 'Animal Friendship',
      description: 'https://5e.tools/spells.html#animal%20friendship_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_2nd_level_barkskin',
      name: 'Barkskin',
      description: 'https://5e.tools/spells.html#barkskin_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_2nd_level_barkskin_repeat',
      name: 'Barkskin',
      description: 'https://5e.tools/spells.html#barkskin_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_2nd_level_locate_animals_or_plants',
      name: 'Locate Animals or Plants',
      description: 'https://5e.tools/spells.html#locate%20animals%20or%20plants_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_2nd_level_spike_growth',
      name: 'Spike Growth',
      description: 'https://5e.tools/spells.html#spike%20growth_xphb',
      tier: '2nd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_3rd_level_leomunds_tiny_hut',
      name: 'Leomund\'s Tiny Hut',
      description: 'https://5e.tools/spells.html#leomund\'s%20tiny%20hut_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_3rd_level_leomunds_tiny_hut_repeat',
      name: 'Leomund\'s Tiny Hut',
      description: 'https://5e.tools/spells.html#leomund\'s%20tiny%20hut_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_3rd_level_phantom_steed',
      name: 'Phantom Steed',
      description: 'https://5e.tools/spells.html#phantom%20steed_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_3rd_level_plant_growth',
      name: 'Plant Growth',
      description: 'https://5e.tools/spells.html#plant%20growth_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_3rd_level_speak_with_dead',
      name: 'Speak with Dead',
      description: 'https://5e.tools/spells.html#speak%20with%20dead_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_3rd_level_speak_with_plants',
      name: 'Speak with Plants',
      description: 'https://5e.tools/spells.html#speak%20with%20plants_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_3rd_level_spirit_guardians',
      name: 'Spirit Guardians',
      description: 'https://5e.tools/spells.html#spirit%20guardians_xphb',
      tier: '3rd',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_4th_level_conjure_woodland_beings',
      name: 'Conjure Woodland Beings',
      description: 'https://5e.tools/spells.html#conjure%20woodland%20beings_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_4th_level_dominate_beast',
      name: 'Dominate Beast',
      description: 'https://5e.tools/spells.html#dominate%20beast_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_4th_level_faithful_hound',
      name: 'Faithful hound',
      description: 'https://www.dandwiki.com/wiki/Faithful_Hound_(5e_Spell) \"Faithful Hound (5e Spell)\"',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_4th_level_grasping_vine',
      name: 'Grasping Vine',
      description: 'https://5e.tools/spells.html#grasping%20vine_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
      id: 'wood_4th_level_giant_insect',
      name: 'Giant Insect',
      description: 'https://5e.tools/spells.html#giant%20insect_xphb',
      tier: '4th',
      isActive: false,
      isPassive: false,
      isSpell: true,
      isCantrip: false,
    },
    {
        id: 'wood_4th_level_guardian_of_faith',
        name: 'Guardian of Faith',
        description: 'https://5e.tools/spells.html#guardian%20of%20faith_xphb',
        tier: '4th',
        isActive: false,
        isPassive: false,
        isSpell: true,
        isCantrip: false,
    },
    {
        id: 'wood_4th_level_locate_creature',
        name: 'Locate Creature',
        description: 'https://5e.tools/spells.html#locate%20creature_xphb',
        tier: '4th',
        isActive: false,
        isPassive: false,
        isSpell: true,
        isCantrip: false,
    },
];
