export const alchemyAbilities = [
  {
    id: "acid_initiate_caustic_bomb",
    name: "Caustic Bomb",
    description: "As an action, you can create a powerful, improvised explosive from available materials. Each creature in a 10-foot radius must make a Dexterity saving throw, taking 4d6 acid damage on a failed save, or half as much on a successful save.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_initiate_acidic_insight",
    name: "Acidic Insight",
    description: "You have developed a keen understanding of acidic substances and their effects. You gain advantage on Intelligence (Arcana) and Wisdom (Nature) checks related to acids, alchemical reactions, and chemical processes. This knowledge allows you to identify and analyse unknown substances or toxins with ease.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_initiate_alchemy_proficiency",
    name: "Alchemy Proficiency",
    description: "Gain proficiency in Alchemist’s Supplies. You can craft basic alchemical substances, such as acid flasks, potions of healing, and other simple concoctions.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_explosive_savant",
    name: "Explosive Savant",
    description: "When you use an explosive device or alchemical flask, its damage increases by an additional damage dice. Additionally, you can use such devices as a bonus action instead of an action.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_expanded_explosion",
    name: "Expanded Explosion",
    description: "Your expertise in crafting explosives has improved the effectiveness of your bombs. When you create or use an explosive device, you increase its radius by 10 feet. For example, a bomb that normally affects a 10-foot radius now affects a 20-foot radius. This increased radius applies to all explosive effects you create, including those from your Improvised Explosives and any similar abilities.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_miasmic_cloud",
    name: "Miasmic Cloud",
    description: "You can create a cloud of acidic mist in a 10-foot radius around you. Any creature that starts its turn within the cloud must make a Constitution saving throw or take 6d6 acid damage and be blinded until the end of its next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_acidic_embrace",
    name: "Acidic Embrace",
    description: "You can magically coat a weapon or object in a layer of corrosive acid. The weapon deals an additional 2d4 acid damage on a successful hit, and the object corrodes any non-magical material it touches. This effect lasts for 1 minute.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "alchemy_adept_mutagen_formula",
    name: "Mutagen Formula",
    description: "When you learn this talent, choose one mutagen formula: Strength (+2 Strength, −2 Intelligence), Dexterity (+2 Dexterity, −2 Wisdom), Constitution (+2 Constitution, −2 Charisma), Intelligence (+2 Intelligence, −2 Strength), Wisdom (+2 Wisdom, −2 Dexterity), or Charisma (+2 Charisma, −2 Constitution). As a bonus action, when you drink a mutagen, you gain the chosen +2 ability score bonus and its paired −2 penalty for 10 minutes.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    location: "Sirius",
  },
  {
    id: "acid_adept_chemical_expertise",
    name: "Chemical Expertise",
    description: "You can create more advanced alchemical mixtures, such as potent acid flasks or alchemical fire. You gain a +2 bonus to checks involving Alchemist’s Supplies and can create these mixtures in half the usual time.\n\n## Master Tier",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_initiate_quickening_draught",
    name: "Quickening Draught",
    description: "As a bonus action, by drinking a specially prepared potion, you gain an additional 10 feet of movement speed for 10 minutes.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_initiate_vital_essence_sublimation_i",
    name: "Vital Essence Sublimation I (Nilo)",
    description: "When you harvest the blood of a fallen creature, you can distill its essence into a single potion. You may either extract one of its abilities (action, bonus action, or reaction) and bottle it as a potion, or create a potion whose rarity depends on the creature’s level.\n\nRoll a d100 to determine if the distillation succeeds; on a failure, the attempt is wasted.\n\n| Creature Cultivation Tier | Potion Rarity | Failure Rate |\n|---|---|---|\n| Initiate | Common | 0% (No failure) |\n| Adept | Uncommon | 20% |\n| Master | Rare | 40% |\n| Grandmaster | Very Rare | 80% |\n| Great Grandmaster | Legendary | 100% |\n\nYou can hold only one distilled essence at a time. Distilled potions do not expire.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Phudara's unknown inheritance",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_initiate_herbalists_knowledge",
    name: "Herbalist’s Knowledge",
    description: "You gain proficiency with the Medicine skill and advantage on checks to identify or use medicinal herbs and poisons.\n\n## Adept Tier",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_vital_essence_sublimation_ii",
    name: "Vital Essence Sublimation II (Nilo)",
    description: "Your distillation technique improves, reducing failure rates and expanding capacity:\n- You can now hold up to two distilled essences at a time.\n\n| Creature Cultivation Tier | Potion Rarity | Failure Rate |\n|---|---|---|\n| Initiate | Common | 0% |\n| Adept | Uncommon | 0% |\n| Master | Rare | 20% |\n| Grandmaster | Very Rare | 60% |\n| Great Grandmaster | Legendary | 80% |",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Phudara's unknown inheritance",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_master_vital_essence_sublimation_iii",
    name: "Vital Essence Sublimation III (Nilo)",
    description: "Your mastery over distillation reaches its zenith:\n- You can now hold up to three distilled essences at a time.\n\n| Creature Cultivation Tier | Potion Rarity | Failure Rate |\n|---|---|---|\n| Initiate | Common | 0% |\n| Adept | Uncommon | 0% |\n| Master | Rare | 0% |\n| Grandmaster | Very Rare | 40% |\n| Great Grandmaster | Legendary | 60% |\n\n**Instant Sublimation:**\nWhen you deal poison damage to a living creature, you can immediately distill one of its abilities into a potion. The essence cost depends on the creature's cultivation tier:\n\n| Creature Tier | Essence Cost |\n|---|---|\n| Initiate | 1 |\n| Adept | 2 |\n| Master | 3 |\n| Grandmaster | 4 |\n| Great Grandmaster | 5 |\n\nIf the creature dies from the triggering damage, the extraction costs no essence points.\n\n## Cantrips",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Phudara's unknown inheritance",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_master_erosion_of_being",
    name: "Erosion of Being",
    description: "As an action, target a creature within 60 feet to make a Constitution saving throw, taking 6d8 acid damage on a failed save or half as much on a success.\n\nOn a failed save, the creature begins dissolving into nothingness and is banished to a harmless demiplane for 1 minute. If reduced to 0 hit points by this damage, it dissolves completely and is permanently destroyed (no resurrection except by *Wish*).\n\nAt the end of each turn while banished, the creature takes 2d8 acid damage and can repeat the save, returning on a success.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Shadow Sect",
    location: "Sirius",
  }
];

export const alchemyCantrips = [
  {
    id: "acid_cantrip_acid_splash",
    name: "Acid Splash",
    description: "https://5e.tools/spells.html#acid%20splash_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "acid_cantrip_primal_savagery",
    name: "Primal Savagery",
    description: "https://5e.tools/spells.html#primal%20savagery_xge\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "v2_alchemy_mending",
    name: "Mending",
    description: "Repairs a single tear or break in an object, restoring it to working condition if the damage is small.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#mending_phb).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB)",
  }
];

export const alchemySpells = [
  {
    id: "pestilence_9th_true_polymorph",
    name: "True Polymorph",
    description: "Permamently warp the biological flesh of a creature or object into any plague beast or form.\n\nhttps://5e.tools/spells.html#true%20polymorph_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Transmutation / Viral Metamorphosis",
  },
  {
    id: "metal_4th_level_fabricate",
    name: "Fabricate",
    description: "https://5e.tools/spells.html#fabricate_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_grease",
    name: "Grease",
    description: "https://5e.tools/spells.html#grease_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "v2_alchemy_tasha_s_caustic_brew",
    name: "Tasha’s Caustic Brew",
    description: "A stream of corrosive liquid coats creatures in a line, damaging them until they or an ally scrape it away.\n\nSource reference: [D&D 5e TCE on 5e.tools](https://5e.tools/spells.html#tasha%E2%80%99s%20caustic%20brew_tce).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (TCE)",
  },
  {
    id: "v2_alchemy_acid_arrow",
    name: "Acid Arrow",
    description: "A magical arrow of acid strikes one target, with lingering damage if the attack misses.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#acid%20arrow_phb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_alchemy_vitriolic_sphere",
    name: "Vitriolic Sphere",
    description: "A bubbling sphere bursts into a wide splash of acid that continues to burn after the initial impact.\n\nSource reference: [D&D 5e XGE on 5e.tools](https://5e.tools/spells.html#vitriolic%20sphere_xge).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  }
];
