export const alchemyAbilities = [
  {
    id: "acid_initiate_caustic_bomb",
    name: "Caustic Bomb",
    description: "As an action, you can create a powerful, improvised explosive from available materials. Each creature in a 10-foot radius must make a Dexterity saving throw, taking 4d6 acid damage on a failed save, or half as much on a successful save.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_initiate_acidic_insight",
    name: "Acidic Insight",
    description: "You have developed a keen understanding of acidic substances and their effects. You gain advantage on Intelligence (Arcana) and Wisdom (Nature) checks related to acids, alchemical reactions, and chemical processes. This knowledge allows you to identify and analyse unknown substances or toxins with ease.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_initiate_alchemy_proficiency",
    name: "Alchemy Proficiency",
    description: "Gain proficiency in Alchemist’s Supplies. You can craft basic alchemical substances, such as acid flasks, potions of healing, and other simple concoctions.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_explosive_savant",
    name: "Explosive Savant",
    description: "When you use an explosive device or alchemical flask, its damage increases by an additional damage dice. Additionally, you can use such devices as a bonus action instead of an action.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_expanded_explosion",
    name: "Expanded Explosion",
    description: "Your expertise in crafting explosives has improved the effectiveness of your bombs. When you create or use an explosive device, you increase its radius by 10 feet. For example, a bomb that normally affects a 10-foot radius now affects a 20-foot radius. This increased radius applies to all explosive effects you create, including those from your Improvised Explosives and any similar abilities.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_miasmic_cloud",
    name: "Miasmic Cloud",
    description: "You can create a cloud of acidic mist in a 10-foot radius around you. Any creature that starts its turn within the cloud must make a Constitution saving throw or take 6d6 acid damage and be blinded until the end of its next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_acidic_embrace",
    name: "Acidic Embrace",
    description: "You can magically coat a weapon or object in a layer of corrosive acid. The weapon deals an additional 2d4 acid damage on a successful hit, and the object corrodes any non-magical material it touches. This effect lasts for 1 minute.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_enhanced_mutagen",
    name: "Mutagen Formula (Strength)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Strength for 10 minutes, and you take a –2 penalty to Intelligence for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_enhanced_mutagen_dexterity",
    name: "Mutagen Formula (Dexterity)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Dexterity for 10 minutes, and you take a –2 penalty to Wisdom for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_enhanced_mutagen_constitution",
    name: "Mutagen Formula (Constitution)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Constitution for 10 minutes, and you take a –2 penalty to Charisma for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_enhanced_mutagen_intelligence",
    name: "Mutagen Formula (Intelligence)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Intelligence for 10 minutes, and you take a –2 penalty to Strength for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_enhanced_mutagen_wisdom",
    name: "Mutagen Formula (Wisdom)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Wisdom for 10 minutes, and you take a –2 penalty to Dexterity for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_enhanced_mutagen_charisma",
    name: "Mutagen Formula (Charisma)",
    description: "As a bonus action, when you drink a mutagen, you gain a +2 bonus to Charisma for 10 minutes, and you take a –2 penalty to Constitution for the same duration.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_chemical_expertise",
    name: "Chemical Expertise",
    description: "You can create more advanced alchemical mixtures, such as potent acid flasks or alchemical fire. You gain a +2 bonus to checks involving Alchemist’s Supplies and can create these mixtures in half the usual time.\n\n## Master Tier",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_initiate_quickening_draught",
    name: "Quickening Draught",
    description: "As a bonus action, by drinking a specially prepared potion, you gain an additional 10 feet of movement speed for 10 minutes.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_initiate_vital_essence_sublimation_i",
    name: "Vital Essence Sublimation I (Nilo)",
    description: "When you harvest the blood of a fallen creature, you can distill its essence into a single potion. You may either extract one of its abilities (action, bonus action, or reaction) and bottle it as a potion, or create a potion whose rarity depends on the creature’s level.\n\nRoll a d100 to determine if the distillation succeeds; on a failure, the attempt is wasted.\n\n| Creature Cultivation Tier | Potion Rarity | Failure Rate |\n|---|---|---|\n| Initiate | Common | 0% (No failure) |\n| Adept | Uncommon | 20% |\n| Master | Rare | 40% |\n| Grandmaster | Very Rare | 80% |\n| Great Grandmaster | Legendary | 100% |\n\nYou can hold only one distilled essence at a time. Distilled potions do not expire.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Phudara's unknown inheritance",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_initiate_herbalists_knowledge",
    name: "Herbalist’s Knowledge",
    description: "You gain proficiency with the Medicine skill and advantage on checks to identify or use medicinal herbs and poisons.\n\n## Adept Tier",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_vital_essence_sublimation_ii",
    name: "Vital Essence Sublimation II (Nilo)",
    description: "Your distillation technique improves, reducing failure rates and expanding capacity:\n- You can now hold up to two distilled essences at a time.\n\n| Creature Cultivation Tier | Potion Rarity | Failure Rate |\n|---|---|---|\n| Initiate | Common | 0% |\n| Adept | Uncommon | 0% |\n| Master | Rare | 20% |\n| Grandmaster | Very Rare | 60% |\n| Great Grandmaster | Legendary | 80% |",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Phudara's unknown inheritance",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_master_vital_essence_sublimation_iii",
    name: "Vital Essence Sublimation III (Nilo)",
    description: "Your mastery over distillation reaches its zenith:\n- You can now hold up to three distilled essences at a time.\n\n| Creature Cultivation Tier | Potion Rarity | Failure Rate |\n|---|---|---|\n| Initiate | Common | 0% |\n| Adept | Uncommon | 0% |\n| Master | Rare | 0% |\n| Grandmaster | Very Rare | 40% |\n| Great Grandmaster | Legendary | 60% |\n\n**Instant Sublimation:**\nWhen you deal poison damage to a living creature, you can immediately distill one of its abilities into a potion. The essence cost depends on the creature's cultivation tier:\n\n| Creature Tier | Essence Cost |\n|---|---|\n| Initiate | 1 |\n| Adept | 2 |\n| Master | 3 |\n| Grandmaster | 4 |\n| Great Grandmaster | 5 |\n\nIf the creature dies from the triggering damage, the extraction costs no essence points.\n\n## Cantrips",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Phudara's unknown inheritance",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_master_erosion_of_being",
    name: "Erosion of Being",
    description: "As an action, target a creature within 60 feet to make a Constitution saving throw, taking 6d8 acid damage on a failed save or half as much on a success.\n\nOn a failed save, the creature begins dissolving into nothingness and is banished to a harmless demiplane for 1 minute. If reduced to 0 hit points by this damage, it dissolves completely and is permanently destroyed (no resurrection except by *Wish*).\n\nAt the end of each turn while banished, the creature takes 2d8 acid damage and can repeat the save, returning on a success.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Shadow Sect",
    location: "Sirius",
  },
  {
    id: "acid_initiate_acidic_precision",
    name: "Acidic Precision",
    description: "Your expertise with corrosive substances has honed your skill in turning everyday objects into deadly weapons. You gain proficiency with all thrown weapons and improvised thrown weapons.\n\n---\n## Adept Tier",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_adept_extended_reach",
    name: "Extended Reach",
    description: "Your skill with explosive devices allows you to strike from farther away. When you create or use an explosive, its range to the target point is doubled. For example, a bomb that can normally be thrown or placed within 30 feet can now target a point up to 60 feet away.\n\n---\n## Master Tier",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "acid_seven_color_elixir",
    name: "Seven-Color Elixir",
    description: "As a bonus action, you drink one of your seven elixirs and roll 1d8 to determine the effect. On a 1–7, you gain the corresponding elixir’s effect. On an 8, you may choose any of the seven:\n\n1. **Crimson Veil** — *Greater Invisibility* for 1 minute.\n2. **Azure Sight** — *True Seeing* for 10 minutes.\n3. **Golden Mirage** — Four illusory duplicates (*Mirror Image*).\n4. **Emerald Phantasm** — *Hallucinatory Terrain* in a 150-foot radius.\n5. **Violet Confusion** — *Confusion* affecting all creatures within 30 feet.\n6. **Silver Displacement** — *Mislead* effect.\n7. **Obsidian Terror** — *Fear* in a 30-foot cone.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Fendral",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_initiate_strength_booster",
    name: "Strength Booster",
    description: "As a bonus action, you can drink a mutagen to gain a 1d4 bonus to strength based ability checks for 10 minutes.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_initiate_enchanting_perfume",
    name: "Enchanting Perfume",
    description: "As an action, you can apply a specially crafted perfume that enhances your charm and charisma. For the next hour, you gain a 1d4 bonus to Charisma (Persuasion) and Charisma (Deception) checks.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_adept_pill_of_focus",
    name: "Pill of Focus",
    description: "As a bonus action, you can consume a pill to gain advantage on concentration checks for the next hour.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "poison_master_essence_snake_horror",
    name: "Apex Toxinator",
    description: "As an Action, through concentrated biochemical reagents and alchemical cultivation, you conjure a monstrous, hissing Snake Horror homunculus in an unoccupied space you can see within 30 feet. The creature is friendly to you and your companions, acts immediately after you in the initiative order, and remains for 1 hour, until it drops to 0 hit points, or until you dismiss it as an action.\n\n---\n## Cantrips\n\n---\n\n## Spells restored from V1",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lord Kai (Shadow Sect)",
    location: "Sirius",
  }
];

export const alchemyCantrips = [
  {
    id: "acid_cantrip_acid_splash",
    name: "Acid Splash",
    description: "https://5e.tools/spells.html#acid%20splash_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "acid_cantrip_primal_savagery",
    name: "Primal Savagery",
    description: "https://5e.tools/spells.html#primal%20savagery_xge\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "v2_alchemy_mending",
    name: "Mending",
    description: "Repairs a single tear or break in an object, restoring it to working condition if the damage is small.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#mending_phb).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB)",
  }
];

export const alchemySpells = [
  {
    id: "pestilence_9th_true_polymorph",
    name: "True Polymorph",
    description: "Permamently warp the biological flesh of a creature or object into any plague beast or form.\n\nhttps://5e.tools/spells.html#true%20polymorph_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Transmutation / Viral Metamorphosis",
  },
  {
    id: "metal_4th_level_fabricate",
    name: "Fabricate",
    description: "https://5e.tools/spells.html#fabricate_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_grease",
    name: "Grease",
    description: "https://5e.tools/spells.html#grease_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "v2_alchemy_tasha_s_caustic_brew",
    name: "Tasha’s Caustic Brew",
    description: "A stream of corrosive liquid coats creatures in a line, damaging them until they or an ally scrape it away.\n\nSource reference: [D&D 5e TCE on 5e.tools](https://5e.tools/spells.html#tasha's%20caustic%20brew_tce).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (TCE)",
  },
  {
    id: "v2_alchemy_acid_arrow",
    name: "Acid Arrow",
    description: "A magical arrow of acid strikes one target, with lingering damage if the attack misses.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#melf's%20acid%20arrow_phb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_alchemy_vitriolic_sphere",
    name: "Vitriolic Sphere",
    description: "A bubbling sphere bursts into a wide splash of acid that continues to burn after the initial impact.\n\nSource reference: [D&D 5e XGE on 5e.tools](https://5e.tools/spells.html#vitriolic%20sphere_xge).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "acid_1st_level_chaos_bolt",
    name: "Chaos Bolt",
    description: "A mass of chaotic energy deals damage of a random type and can leap between targets on matching dice.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#chaos%20bolt_xge).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "acid_1st_level_chromatic_orb",
    name: "Chromatic Orb",
    description: "An orb of chosen elemental energy deals 3d8 damage and can leap to more targets on matching dice.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#chromatic%20orb_xphb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "poison_2nd_level_enlarge_reduce",
    name: "Enlarge/Reduce",
    description: "A creature or object grows or shrinks one size, changing its strength and weapon damage.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#enlarge%2Freduce_xphb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "acid_6th_level_disintegrate",
    name: "Disintegrate",
    description: "A green ray deals 10d6 + 40 force damage and reduces anything it kills to dust.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#disintegrate_xphb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_8th_level_animal_shapes",
    name: "Animal Shapes",
    description: "Any number of willing creatures take the forms of beasts, and you can reshape them on later turns.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#animal%20shapes_xphb).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "providence_2nd_lesser_restoration",
    name: "Lesser Restoration",
    description: "You end one disease or condition: blinded, deafened, paralyzed, or poisoned.\n\nhttps://5e.tools/spells.html#lesser%20restoration_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "providence_5th_greater_restoration",
    name: "Greater Restoration",
    description: "You end one debilitating effect: exhaustion levels, charmed/petrified, cursed, or ability reductions.\n\nhttps://5e.tools/spells.html#greater%20restoration_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Abjuration",
  },
  {
    id: "v2_alchemy_create_magen",
    name: "Create Magen",
    description: "You transform a quicksilver-filled doll into a magen construct that obeys your commands.\n\nSource reference: [D&D 5e (IDRotF) on 5e.tools](https://5e.tools/spells.html#create%20magen_idrotf).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (IDRotF)",
  },
  {
    id: "v2_alchemy_clone",
    name: "Clone",
    description: "An inert duplicate grows in a vessel over 120 days; if the original dies, its soul transfers to the clone.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#clone_xphb).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_alchemy_detonate",
    name: "Detonate",
    description: "An explosive seed inside a creature deals 10d10 fire damage, then erupts in a 60-foot blast that damages everyone around it.\n\nSource reference: [D&D 5e (Arcana Unleashed) on 5e.tools](https://5e.tools/spells.html#detonate_au).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Arcana Unleashed)",
  },
  {
    id: "v2_alchemy_mass_polymorph",
    name: "Mass Polymorph",
    description: "Up to ten creatures transform into beasts of your choice for up to an hour.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#mass%20polymorph_xge).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "v2_alchemy_steal_immortality",
    name: "Steal Immortality",
    description: "You take on a creature type’s immortal traits, gaining temporary hit points, resistances, and that type’s signature gifts.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#steal%20immortality_grimhollowpg24).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  }
];
