export const earthAbilities = [
  {
    id: "earth_initiate_stonecunning",
    name: "Stonecunning",
    description: "Gain proficiency in History. If already proficient, you gain expertise.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_initiate_miners_touch",
    name: "Miner's Touch",
    description: "Gain proficiency with mason’s tools and miner’s tools.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_initiate_rock_whisperer",
    name: "Rock Whisperer",
    description: "You can communicate simple ideas with earth elementals and creatures of stone.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_initiate_earth_sense",
    name: "Earth Sense",
    description: "You have advantage on Survival and Perception checks to navigate underground or in rocky terrain.\n\n---",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_initiate_pebble_barrage",
    name: "Pebble Barrage",
    description: "As an action, you hurl a barrage of pebbles at a creature within 30 feet. The target must make a Dexterity saving throw. On a failed save, the creature takes 4d4 bludgeoning damage and is knocked prone.\n\n## Adept Tier",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_adept_earthen_resilience",
    name: "Earthen Resilience",
    description: "Gain proficiency in Constitution saving throws.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_adept_terramancer",
    name: "Terramancer",
    description: "Gain expertise in Athletics when performing tasks involving lifting, pushing, or pulling heavy objects made of stone or earth.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_adept_stone_camouflage",
    name: "Stone Camouflage",
    description: "You have expertise on Stealth checks to hide in rocky terrain or against stone surfaces.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_adept_earthen_grasp",
    name: "Earthen Grasp",
    description: "As a bonus action, you cause hands of compacted earth to grasp a creature within 30 feet, restraining it for 1 minute. The restrained creature can make a Strength saving throw at the end of each of its turns, ending the effect on a success.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_adept_stone_armor",
    name: "Stone Armor",
    description: "As a bonus action, you can encase yourself in a layer of stone, granting you resistance to bludgeoning, piercing, and slashing damage for 1 minute.\n\n---",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_adept_sandstorm",
    name: "Sandstorm",
    description: "As an action, you create a swirling storm of sand in a 20-foot radius centered on you that lasts for 1 minute.\n\nEach creature in the area must make a Constitution saving throw, taking 3d6 slashing damage and becoming blinded until the end of its next turn on a failed save, or half as much damage on a successful one.\n\nThe area is difficult terrain, and any creature that starts its turn within the storm takes 1d6 slashing damage.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "earth_essence_immovable_mountain",
    name: "Immovable Mountain",
    description: "For 1 minute, you become an unyielding force:\n- You cannot be knocked prone, grappled, restrained, paralyzed, stunned, or moved against your will.\n- Whenever you hit a creature with a melee attack, you may push it 10 feet or knock it prone.\n- The ground cracks beneath your steady steps.\n\n---",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Shadow Sect",
    location: "Sirius",
  },
  {
    id: "earth_master_essence_moves_mountains",
    name: "Foolish Old Man Moves Mountains",
    description: "Each time you fail a saving throw against a hostile creature’s effect, your essence ability save DC increases by 1 until you complete a long rest. This increase can stack up to a maximum of +3.\n\n## Special Abilities",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Shadow Sect",
    location: "Sirius",
  },
  {
    id: "earth_active_earthen_ward",
    name: "Earthen Ward",
    description: "As a reaction, a surge of earth magic momentarily hardens your form. You gain temporary hit points equal to 1d10 + your Constitution modifier.\n\n## Cantrips",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_adept_gemsight",
    name: "Gemsight",
    description: "You gain expertise in Perception checks to locate hidden gemstones or precious minerals. When you find such items, you can appraise their value with a successful Intelligence (Investigation) check.\n\n---\n\n## Spells restored from V1",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  }
];

export const earthCantrips = [
  {
    id: "earth_cantrip_magic_stone",
    name: "Magic Stone",
    description: "https://5e.tools/spells.html#magic%20stone_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "earth_cantrip_mold_earth",
    name: "Mold Earth",
    description: "https://5e.tools/spells.html#mold%20earth_xge\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const earthSpells = [
  {
    id: "earth_1st_level_earth_tremor",
    name: "Earth Tremor",
    description: "https://5e.tools/spells.html#earth%20tremor_xge",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "earth_3rd_level_erupting_earth",
    name: "Erupting Earth",
    description: "https://5e.tools/spells.html#erupting%20earth_xge",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "earth_4th_level_stone_shape",
    name: "Stone Shape",
    description: "https://5e.tools/spells.html#stone%20shape_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "earth_4th_level_stoneskin",
    name: "Stoneskin",
    description: "https://5e.tools/spells.html#stoneskin_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "earth_5th_level_wall_of_stone",
    name: "Wall of Stone",
    description: "https://5e.tools/spells.html#wall%20of%20stone_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "earth_6th_level_move_earth",
    name: "Move Earth",
    description: "https://5e.tools/spells.html#move%20earth_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "earth_8th_level_earthquake",
    name: "Earthquake",
    description: "https://5e.tools/spells.html#earthquake_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "earth_1st_level_tremor",
    name: "Tremor",
    description: "The ground around you shakes, becoming difficult terrain and battering and toppling nearby creatures.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#tremor_grimhollowpg24).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "earth_2nd_level_earthbind",
    name: "Earthbind",
    description: "Magical strips drag a flying creature down, reducing its flying speed to 0.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#earthbind_xge).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "earth_2nd_level_maximilians_earthen_grasp",
    name: "Maximilian's Earthen Grasp",
    description: "A hand of compacted soil rises to grab and restrain a creature, and you can make it crush the target.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#maximilian's%20earthen%20grasp_xge).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "earth_3rd_level_meld_into_stone",
    name: "Meld into Stone",
    description: "You merge with a stone surface, hidden and protected until you step out.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#meld%20into%20stone_xphb).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "earth_3rd_level_wall_of_sand",
    name: "Wall of Sand",
    description: "A wall of swirling sand blocks sight, blinds those inside it, and slows movement through it.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#wall%20of%20sand_xge).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "wood_5th_level_conjure_elemental",
    name: "Conjure Elemental",
    description: "You call a Large elemental spirit whose element sets its damage and lets it restrain nearby creatures.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#conjure%20elemental_xphb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "earth_5th_level_transmute_rock",
    name: "Transmute Rock",
    description: "You turn a large area of rock to mud or mud to rock, bogging down or trapping creatures.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#transmute%20rock_xge).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "earth_6th_level_bones_of_the_earth",
    name: "Bones of the Earth",
    description: "Up to six stone pillars burst from the ground, lifting and possibly crushing creatures against ceilings.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#bones%20of%20the%20earth_xge).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "earth_6th_level_earth_worm",
    name: "Earth Worm",
    description: "The earth forms a worm-like maw that bites nearby creatures and can swallow them whole.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#earth%20worm_grimhollowpg24).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "earth_6th_level_flesh_to_stone",
    name: "Flesh to Stone",
    description: "A creature is restrained as its body hardens and, after repeated failed saves, turns permanently to stone.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#flesh%20to%20stone_xphb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "earth_6th_level_investiture_of_stone",
    name: "Investiture of Stone",
    description: "Rock spreads over you: resistance to weapon damage, the power to cause local earthquakes, and passage through stone.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#investiture%20of%20stone_xge).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "v2_earth_mighty_fortress",
    name: "Mighty Fortress",
    description: "A 120-foot stone fortress erupts from the ground, complete with towers, walls, and a keep staffed by invisible servants.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#mighty%20fortress_xge).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "v2_earth_invulnerability",
    name: "Invulnerability",
    description: "You are immune to all damage for up to 10 minutes.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#invulnerability_xge).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "v2_earth_rocks_fall",
    name: "Rocks Fall",
    description: "Boulders rain down in a 60-foot radius for 10d8 bludgeoning damage, burying creatures under the rubble.\n\nSource reference: [Valda's Spire of Secrets: Player Pack 2 on 5e.tools](https://5e.tools/spells.html#rocks%20fall_valdaplayerpack2).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Valda's Spire of Secrets: Player Pack 2",
  },
  {
    id: "v2_earth_jotun_form",
    name: "Jotun Form",
    description: "You shape-shift into a giant, taking its statistics and a pool of temporary hit points equal to its hit points.\n\nSource reference: [Kobold Press Northlands Worldbook on 5e.tools](https://5e.tools/spells.html#jotun%20form_northlandsworldbook).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Kobold Press Northlands Worldbook",
  }
];
