export const fireAbilities = [
  {
    id: "fire_initiate_flame_ward",
    name: "Flame Ward",
    description: "You have advantage on saving throws against being frightened or charmed while within 10 feet of a source of fire or heat.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_initiate_flame_kinship",
    name: "Flame Kinship",
    description: "You gain the ability to communicate with creatures of fire, such as Fire Elementals and Magmin, as if you shared a common language. This does not grant you the ability to control or command them but allows for basic communication and understanding.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_initiate_ember_strike",
    name: "Ember Strike",
    description: "When you hit a creature with a weapon attack, you can expend a spell slot to deal an additional 1d12 fire damage per level of the spell slot expended. Additionally, the target must succeed on a Wisdom saving throw against your spell save DC or become frightened of you until the end of its next turn.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_initiate_flame_lash",
    name: "Flame Lash",
    description: "You can use your action to create a whip-like tendril of fire that extends up to 15 feet. Make a melee spell attack against a creature within range. On a hit, the target takes fire damage equal to 4d6 + your spellcasting ability modifier. The intense heat also causes the target to become dazzled, giving them disadvantage on their next attack roll.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_initiate_inferno_disengage",
    name: "Inferno Disengage",
    description: "When you use the Disengage action, you create a burst of fire around you. Each creature within 5 feet of you takes 2d6 fire damage.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_adept_embers_resilience",
    name: "Ember's Resilience",
    description: "As a reaction when you fail a saving throw, you can reroll the saving throw die. If you do so, you take 2d6 fire damage.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_adept_blazing_trail",
    name: "Blazing Trail",
    description: "When you take the Dash action, you can leave a trail of fire in your wake. For the duration of your movement, any creature that enters or ends its turn within the 10-foot-wide line of fire you create takes fire damage equal to your total fire essences. The creature must make a Dexterity saving throw, taking half damage on a success. This trail lasts for 1 minute or until you choose to end it.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_adept_scorched_ground",
    name: "Scorched Ground",
    description: "As an action, you can cause a 20-foot radius area on the ground to become superheated within 120 feet of you for 1 minute. Creatures that start their turn in this area take fire damage equal to 4d6 + your spellcasting ability modifier. The area is difficult terrain, and the fire persists even if you move away from it.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_adept_burning_fury",
    name: "Burning Fury",
    description: "Immediately after you take fire damage, you gain advantage on attack rolls made before the end of your next turn.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  }
];

export const fireCantrips = [
  {
    id: "fire_cantrip_control_flames",
    name: "Control Flames",
    description: "https://5e.tools/spells.html#control%20flames_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "fire_cantrip_create_bonfire",
    name: "Create Bonfire",
    description: "https://5e.tools/spells.html#create%20bonfire_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "fire_cantrip_fire_bolt",
    name: "Fire Bolt",
    description: "https://5e.tools/spells.html#fire%20bolt_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "fire_cantrip_green_flame_blade",
    name: "Green-Flame Blade",
    description: "https://5e.tools/spells.html#green-flame%20blade_tce",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "fire_cantrip_produce_flame",
    name: "Produce Flame",
    description: "A harmless flame lights your hand; you can hurl it as a ranged spell attack that deals fire damage.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#produce%20flame_xphb).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB 2024)",
  }
];

export const fireSpells = [
  {
    id: "fire_9th_level_meteor_swarm",
    name: "Meteor Swarm",
    description: "https://5e.tools/spells.html#meteor%20swarm_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_1st_level_burning_hands",
    name: "Burning Hands",
    description: "https://5e.tools/spells.html#burning%20hands_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_2nd_level_aganazzars_scorcher",
    name: "Aganazzar's Scorcher",
    description: "https://5e.tools/spells.html#aganazzar's%20scorcher_xge",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_2nd_level_flame_blade",
    name: "Flame Blade",
    description: "https://5e.tools/spells.html#flame%20blade_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_3rd_level_fireball",
    name: "Fireball",
    description: "https://5e.tools/spells.html#fireball_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_4th_level_wall_of_fire",
    name: "Wall of Fire",
    description: "https://5e.tools/spells.html#wall%20of%20fire_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_5th_level_immolation",
    name: "Immolation",
    description: "https://5e.tools/spells.html#immolation_xge",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_7th_level_fire_storm",
    name: "Fire Storm",
    description: "https://5e.tools/spells.html#fire%20storm_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_5th_level_flame_strike",
    name: "Flame Strike",
    description: "https://5e.tools/spells.html#flame%20strike_xphb\n\n---\n\n## Spells restored from V1",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "fire_1st_level_spellfire_flare",
    name: "Spellfire Flare",
    description: "A blast of brilliant spellfire ignores cover and deals 2d10 radiant damage on a ranged spell attack.\n\nSource reference: [D&D 5e (Heroes of Faerûn) on 5e.tools](https://5e.tools/spells.html#spellfire%20flare_frhof).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Heroes of Faerûn)",
  },
  {
    id: "fire_2nd_level_continual_flame",
    name: "Continual Flame",
    description: "A heatless, fuel-free flame sheds light from an object you touch and cannot be smothered or quenched.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#continual%20flame_xphb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "fire_2nd_level_flaming_sphere",
    name: "Flaming Sphere",
    description: "A rolling 5-foot sphere of fire scorches creatures that end their turn near it; you can steer it as a bonus action.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#flaming%20sphere_xphb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "fire_2nd_level_scorching_ray",
    name: "Scorching Ray",
    description: "You hurl three fiery rays at one or more targets, each dealing 2d6 fire damage on a hit.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#scorching%20ray_xphb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "fire_3rd_level_ashardalons_stride",
    name: "Ashardalon's Stride",
    description: "Dragon flames blast from your feet: +20 feet of speed, no opportunity attacks, and fire damage to anything you pass.\n\nSource reference: [D&D 5e (FTD) on 5e.tools](https://5e.tools/spells.html#ashardalon's%20stride_ftd).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (FTD)",
  },
  {
    id: "fire_3rd_level_flame_arrows",
    name: "Flame Arrows",
    description: "Ammunition drawn from a touched quiver deals an extra 1d6 fire damage, for up to twelve shots.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#flame%20arrows_xge).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "fire_4th_level_fire_shield",
    name: "Fire Shield",
    description: "Flames wreathe you as a warm or chill shield, granting resistance and burning creatures that hit you in melee.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#fire%20shield_xphb).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "fire_4th_level_spellfire_storm",
    name: "Spellfire Storm",
    description: "A 20-foot pillar of spellfire deals 4d10 radiant damage to creatures inside it or entering it.\n\nSource reference: [D&D 5e (Heroes of Faerûn) on 5e.tools](https://5e.tools/spells.html#spellfire%20storm_frhof).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Heroes of Faerûn)",
  },
  {
    id: "fire_6th_level_investiture_of_flame",
    name: "Investiture of Flame",
    description: "Your body becomes wreathed in fire: immunity to fire, a burning aura, and a line of flame you can loose as an action.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#investiture%20of%20flame_xge).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "fire_7th_level_delayed_blast_fireball",
    name: "Delayed Blast Fireball",
    description: "A glowing bead grows stronger each round you hold it, then explodes in a 20-foot radius of fire.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#delayed%20blast%20fireball_xphb).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "fire_8th_level_incendiary_cloud",
    name: "Incendiary Cloud",
    description: "A roiling cloud of embers obscures a 20-foot radius and deals 10d8 fire damage, drifting away from you each turn.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#incendiary%20cloud_xphb).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  }
];
