export const loveAbilities = [
  {
    id: "ruin_initiate_attraction_disdain",
    name: "Attraction/Disdain",
    description: "**Casting Time:** 1 action  \n**Range:** Touch  \n**Components:** V, S, M (a holy symbol)  \n**Duration:** 1 hour  \n**Portfolio:** Emotional influence\n\nChoose attraction or disdain when you cast this spell:\n\n**Attraction.** You touch a creature, which must make a Charisma saving throw. On a failure, any negative emotions it has toward you become positive emotions (hatred becomes love, etc.). Your Charisma score increases by 1d4+2 for interactions with the target.\n\n**Disdain.** You touch a creature and name another creature it knows. The target must make a Charisma saving throw. On a failure, any positive emotions it has toward the named creature become negative emotions. The named creature's Charisma score is reduced by 1d4+2 for interactions with the target.\n\nIf the target's emotions are extremely intense, the DM can impose a +1 to +5 bonus to the saving throw.\n\n## Cantrips",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Cyric (source technique; emotional manipulation)",
    location: "Leatrux",
  },
  {
    id: "water_adept_tide_of_emotions",
    name: "Tide of Emotions",
    description: "By channelling the ebb and flow of water, you can influence the emotions of others within a 30-foot radius. Choose one emotion (calm, fear, or joy); affected creatures must succeed on a Wisdom saving throw or be overwhelmed by that emotion for 1 hour.\n\n---\n\n## Spells restored from V1",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  }
];

export const loveCantrips = [
  {
    id: "love_cantrip_friends",
    name: "Friends",
    description: "For a brief time, you gain advantage on Charisma checks directed at one creature that is not hostile to you. When the magic ends, the creature recognizes that its feelings were influenced.\n\nhttps://5e.tools/spells.html#friends_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Enchantment / Emotional influence",
  },
  {
    id: "torment_cantrip_vicious_mockery",
    name: "Vicious Mockery",
    description: "Unleash strings of barbed insults and psychic cruelty, dealing 1d4 psychic damage and giving disadvantage on its next attack.\n\nhttps://5e.tools/spells.html#vicious%20mockery_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Enchantment / Torment",
  }
];

export const loveSpells = [
  {
    id: "providence_2nd_calm_emotions",
    name: "Calm Emotions",
    description: "You suppress strong emotions, suppressing charmed or frightened conditions or making hostile creatures indifferent.\n\nhttps://5e.tools/spells.html#calm%20emotions_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Peace Domain",
  },
  {
    id: "love_1st_charm_person",
    name: "Charm Person",
    description: "You attempt to charm a humanoid you can see. On a failed Wisdom save, it regards you as a friendly acquaintance for the duration; it knows it was charmed when the effect ends.\n\nhttps://5e.tools/spells.html#charm%20person_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "love_2nd_enthrall",
    name: "Enthrall",
    description: "You weave a compelling presence that draws the attention of creatures of your choice, distracting them from others while you speak or perform.\n\nhttps://5e.tools/spells.html#enthrall_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "love_2nd_suggestion",
    name: "Suggestion",
    description: "You influence a creature with a brief course of action that sounds reasonable to it. A creature that fails its Wisdom save follows the suggestion unless the action is harmful.\n\nhttps://5e.tools/spells.html#suggestion_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "love_4th_charm_monster",
    name: "Charm Monster",
    description: "You attempt to charm a creature you can see. On a failed Wisdom save, it regards you as a friendly acquaintance for the duration and knows it was charmed when the effect ends.\n\nhttps://5e.tools/spells.html#charm%20monster_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "love_8th_antipathy_sympathy",
    name: "Antipathy/Sympathy",
    description: "You imbue an area or object with either irresistible attraction or repulsion, drawing creatures toward it or compelling them to avoid it.\n\nhttps://5e.tools/spells.html#antipathy%2fsympathy_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "v2_love_compulsion",
    name: "Compulsion",
    description: "A compelling rhythm draws creatures of your choice to move in a direction you set.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#compulsion_phb).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_love_dominate_person",
    name: "Dominate Person",
    description: "You exert sustained influence over a humanoid’s actions and choices.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#dominate%20person_phb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_love_geas",
    name: "Geas",
    description: "You place a magical command on a creature and punish it for defying the order.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#geas_phb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_love_mass_suggestion",
    name: "Mass Suggestion",
    description: "You influence several creatures with a brief course of action that sounds reasonable.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#mass%20suggestion_phb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "wood_1st_level_animal_friendship",
    name: "Animal Friendship",
    description: "A beast is charmed by you unless you or your allies harm it.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#animal%20friendship_xphb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_1st_level_speak_with_animals",
    name: "Speak with Animals",
    description: "You can understand and speak with beasts and use Influence with them.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#speak%20with%20animals_xphb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_4th_level_dominate_beast",
    name: "Dominate Beast",
    description: "A beast is charmed and telepathically commanded by you.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#dominate%20beast_xphb).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_love_transfix",
    name: "Transfix",
    description: "Your appearance becomes otherworldly and alluring; one creature that fails a Charisma save is charmed and incapacitated, drawn toward you.\n\nSource reference: [D&D 5e (Arcana Unleashed) on 5e.tools](https://5e.tools/spells.html#transfix_au).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Arcana Unleashed)",
  },
  {
    id: "v2_love_tether_essence",
    name: "Tether Essence",
    description: "Two creatures are magically linked so that damage and healing dealt to one is also dealt to the other, and when one drops to 0 hit points, so does the other.\n\nSource reference: [D&D 5e (EGW) on 5e.tools](https://5e.tools/spells.html#tether%20essence_egw).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (EGW)",
  },
  {
    id: "v2_love_dominate_monster",
    name: "Dominate Monster",
    description: "A creature that fails a Wisdom save is charmed and follows your telepathic commands for up to 1 hour.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#dominate%20monster_xphb).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_love_telepathy",
    name: "Telepathy",
    description: "You share a telepathic link with a willing, familiar creature anywhere on the same plane, exchanging words, images, and sensations for 24 hours.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#telepathy_xphb).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_love_obsession",
    name: "Obsession",
    description: "You ignite a creature’s passion and direct it at a chosen person; it deepens over the weeks and can become permanent, though true love’s kiss ends it.\n\nSource reference: [Abi-Dalzim's Abhorrent Adventurers on 5e.tools](https://5e.tools/spells.html#obsession_abidalzims).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Abi-Dalzim's Abhorrent Adventurers",
  },
  {
    id: "v2_love_virus_charm",
    name: "Virus Charm",
    description: "Up to five creatures are charmed into treating you as a friend, and each spreads the charm by touch to others.\n\nSource reference: [Blackstaff's Book of 1000 Spells on 5e.tools](https://5e.tools/spells.html#virus%20charm_bb1000s).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Blackstaff's Book of 1000 Spells",
  }
];
