export const loveAbilities = [
  {
    id: "wood_master_heart_exchange",
    name: "Heart Exchange",
    description: "As an action, choose a willing creature within 60 feet. You exchange hearts—roots of life intertwining your essences in profound gratitude.\n\nFor the next hour, you and the target share an unbreakable bond regardless of distance:\n- Whenever one of you takes damage, both take half that damage.\n- Whenever one regains hit points, both regain the same amount.\n- You both gain advantage on all saving throws.\n\nYou can maintain only one heart exchange at a time.\n\n## Cantrips",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    location: "Sirius",
  },
  {
    id: "ruin_initiate_attraction_disdain",
    name: "Attraction/Disdain",
    description: "**Casting Time:** 1 action  \n**Range:** Touch  \n**Components:** V, S, M (a holy symbol)  \n**Duration:** 1 hour  \n**Portfolio:** Emotional influence\n\nChoose attraction or disdain when you cast this spell:\n\n**Attraction.** You touch a creature, which must make a Charisma saving throw. On a failure, any negative emotions it has toward you become positive emotions (hatred becomes love, etc.). Your Charisma score increases by 1d4+2 for interactions with the target.\n\n**Disdain.** You touch a creature and name another creature it knows. The target must make a Charisma saving throw. On a failure, any positive emotions it has toward the named creature become negative emotions. The named creature's Charisma score is reduced by 1d4+2 for interactions with the target.\n\nIf the target's emotions are extremely intense, the DM can impose a +1 to +5 bonus to the saving throw.\n\n## Cantrips",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Cyric (source technique; emotional manipulation)",
  }
];

export const loveCantrips = [
  {
    id: "love_cantrip_friends",
    name: "Friends",
    description: "For a brief time, you gain advantage on Charisma checks directed at one creature that is not hostile to you. When the magic ends, the creature recognizes that its feelings were influenced.\n\nhttps://5e.tools/spells.html#friends_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Enchantment / Emotional influence",
  }
];

export const loveSpells = [
  {
    id: "providence_2nd_calm_emotions",
    name: "Calm Emotions",
    description: "You suppress strong emotions, suppressing charmed or frightened conditions or making hostile creatures indifferent.\n\nhttps://5e.tools/spells.html#calm%20emotions_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Peace Domain",
  },
  {
    id: "love_1st_charm_person",
    name: "Charm Person",
    description: "You attempt to charm a humanoid you can see. On a failed Wisdom save, it regards you as a friendly acquaintance for the duration; it knows it was charmed when the effect ends.\n\nhttps://5e.tools/spells.html#charm%20person_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "love_2nd_enthrall",
    name: "Enthrall",
    description: "You weave a compelling presence that draws the attention of creatures of your choice, distracting them from others while you speak or perform.\n\nhttps://5e.tools/spells.html#enthrall_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "love_2nd_suggestion",
    name: "Suggestion",
    description: "You influence a creature with a brief course of action that sounds reasonable to it. A creature that fails its Wisdom save follows the suggestion unless the action is harmful.\n\nhttps://5e.tools/spells.html#suggestion_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "love_4th_charm_monster",
    name: "Charm Monster",
    description: "You attempt to charm a creature you can see. On a failed Wisdom save, it regards you as a friendly acquaintance for the duration and knows it was charmed when the effect ends.\n\nhttps://5e.tools/spells.html#charm%20monster_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "love_8th_antipathy_sympathy",
    name: "Antipathy/Sympathy",
    description: "You imbue an area or object with either irresistible attraction or repulsion, drawing creatures toward it or compelling them to avoid it.\n\nhttps://5e.tools/spells.html#antipathy%20sympathy_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Love and emotional influence",
  },
  {
    id: "providence_1st_heroism",
    name: "Heroism",
    description: "A willing creature is imbued with bravery: immune to being frightened, and gains temporary HP at the start of each turn.\n\nhttps://5e.tools/spells.html#heroism_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Paladin / Cleric (Peace Domain)",
  },
  {
    id: "v2_love_compulsion",
    name: "Compulsion",
    description: "A compelling rhythm draws creatures of your choice to move in a direction you set.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#compulsion_phb).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_love_dominate_person",
    name: "Dominate Person",
    description: "You exert sustained influence over a humanoid’s actions and choices.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#dominate%20person_phb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_love_geas",
    name: "Geas",
    description: "You place a magical command on a creature and punish it for defying the order.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#geas_phb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_love_mass_suggestion",
    name: "Mass Suggestion",
    description: "You influence several creatures with a brief course of action that sounds reasonable.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#mass%20suggestion_phb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  }
];
