export const lunarAbilities = [
  {
    id: "water_adept_moonlit_verdant_beam",
    name: "Moonlit Verdant Beam",
    description: "As an action, you fire a beam of toxic moonlight at a creature within 60 feet. Make a ranged spell attack:\n- **On a hit:** The target takes 3d6 radiant damage + 3d6 poison damage and must make a Constitution saving throw against your spell save DC.\n- **On a failed save:** The target is blinded and poisoned until the end of your next turn.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lesbian Dragons",
    location: "Leatrux",
  },
  {
    id: "water_master_lunar_tide",
    name: "Lunar Tide",
    description: "As a reaction when you or creatures within 30 feet are subjected to a Dexterity saving throw against an ability that deals damage, you summon a protective wave of water guided by lunar force. All affected creatures reduce the damage taken by 2d8 + your spellcasting modifier. The water then dissipates harmlessly.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Shadow Sect",
    location: "Sirius",
  },
  {
    id: "water_master_moonfall_condemnation",
    name: "Moonfall Condemnation",
    description: "As an action, you target one creature within 120 feet. A pillar of concentrated moonlight descends, requiring a Dexterity saving throw against your essence ability save DC:\n- **On a failed save:** The target takes 6d8 radiant damage and 3d8 cold damage, and is restrained until the end of its next turn as lunar energy begins to calcify its limbs.\n- **On a successful save:** The target takes half damage and is not restrained.\n\n**Lunar Petrification:**\nIf this damage reduces the target to 50 hit points or fewer, it must immediately make a Constitution saving throw against your essence ability save DC. On a failed save, the creature is petrified into moonstone.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Yuji (Shadow Sect)",
    location: "Leatrux",
  },
  {
    id: "wind_master_essence_lunar_wind_spiral",
    name: "Lunar Wind Spiral",
    description: "As an action, you target a point within 150 feet. A cylinder of swirling, moonlight-infused winds erupts in a 30-foot radius and 60-foot height for 1 minute.\n\n**Initial Eruption:**\nWhen the spiral appears, each creature in the area must make a Constitution saving throw against your essence ability save DC:\n- **On a failed save:** The creature takes 6d8 radiant damage and is lifted 20 feet into the air until the start of its next turn.\n- **On a successful save:** The creature takes half damage and is not lifted.\n\n**Ongoing Hazard:**\nAny creature that starts its turn in the area or enters it for the first time on a turn must make a Constitution saving throw, taking 3d6 radiant damage on a failed save, or half as much on a successful one (it is not lifted).\n\n**Repositioning:**\nYou can use a bonus action on a subsequent turn to move the cylinder up to 30 feet.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Yuji (Shadow Sect)",
    location: "Leatrux",
  },
  {
    id: "wind_master_essence_waning_moon_sabers",
    name: "Waning Moon Sabers",
    description: "As a bonus action, launch up to three crescent-shaped energy blades that travel up to 150 feet. The sabers curve around cover, ignoring half and three-quarters cover.\n\nMake a ranged spell attack for each saber:\n- **On a hit:** The target takes 1d4 + 1 radiant damage and must make a Constitution saving throw or be blinded until the end of its next turn as moonlight sears its vision.\n- **Critical Hit:** The target automatically fails the saving throw.\n\n## Cantrips\n\n## Spells",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Yuji (Shadow Sect)",
    location: "Leatrux",
  }
];

export const lunarCantrips = [
  {
    id: "v2_moon_dancing_lights",
    name: "Dancing Lights",
    description: "You create up to four small lights that hover, move, and change position at your direction.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#dancing%20lights_phb).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB)",
  },
  {
    id: "moon_cantrip_light",
    name: "Light",
    description: "You touch one object. Until the spell ends, the object sheds bright sunlight in a 20-foot radius and dim light for an additional 20 feet.\n\nhttps://5e.tools/spells.html#light_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Evocation",
  }
];

export const lunarSpells = [
  {
    id: "moon_1st_faerie_fire",
    name: "Faerie Fire",
    description: "Each object in a 20-foot cube is outlined in blue, green, or violet lunar light. Creatures fail a Dexterity save or are illuminated, granting advantage on attack rolls against them.\n\nhttps://5e.tools/spells.html#faerie%20fire_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Twilight Domain) / Druid",
  },
  {
    id: "moon_2nd_moonbeam",
    name: "Moonbeam",
    description: "A silvery beam of pale light shines down in a 5-foot-radius cylinder. A creature entering the area or starting its turn there must make a Constitution saving throw or take 2d10 radiant damage.\n\nhttps://5e.tools/spells.html#moonbeam_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Twilight Domain) / Paladin (Ancients)",
  },
  {
    id: "moon_2nd_see_invisibility",
    name: "See Invisibility",
    description: "For the duration, you see invisible creatures and objects as if they were visible, and can perceive into the Ethereal Plane.\n\nhttps://5e.tools/spells.html#see%20invisibility_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Twilight Domain) / Divination",
  },
  {
    id: "moon_5th_alustriels_mooncloak",
    name: "Alustriel's Mooncloak",
    description: "https://5e.tools/spells.html#alustriel's%20mooncloak_frhof",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Alustriel / Selûne",
  },
  {
    id: "moon_6th_true_seeing",
    name: "True Seeing",
    description: "You give a willing creature the ability to see things as they actually are out to 120 feet: see in darkness, notice secret doors, see invisible creatures, and see into the Ethereal Plane.\n\nhttps://5e.tools/spells.html#true%20seeing_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Divination",
  },
  {
    id: "v2_moon_mirror_image",
    name: "Mirror Image",
    description: "Several illusory reflections surround you, confusing attacks aimed at your true form.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#mirror%20image_phb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_moon_blur",
    name: "Blur",
    description: "Your outline shifts and shimmers, making your position difficult to read.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#blur_phb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_moon_shapechange",
    name: "Shapechange",
    description: "You take the form of another creature while retaining your own mind and abilities.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#shapechange_phb).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "moon_9th_foresight",
    name: "Foresight",
    description: "You bestow supreme celestial foresight. The target cannot be surprised and has advantage on attack rolls, ability checks, and saving throws for 8 hours.\n\nhttps://5e.tools/spells.html#foresight_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Divination",
  },
  {
    id: "moon_4th_divination",
    name: "Divination",
    description: "Your magic puts you in direct contact with Selûne or her celestial servants. You ask a single question concerning a specific goal or event within 7 days, receiving a truthful cryptic reply.\n\nhttps://5e.tools/spells.html#divination_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Divination",
  },
  {
    id: "moon_5th_dream",
    name: "Dream",
    description: "This spell shapes a creature's dreams through the silver veil of Selûne, acting as a celestial messenger across any distance or plane.\n\nhttps://5e.tools/spells.html#dream_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Twilight Domain) / Illusion",
  },
  {
    id: "moon_1st_guiding_bolt",
    name: "Guiding Bolt",
    description: "A flash of sunlight streaks toward a creature of your choice within range. On a hit, the target takes 4d6 radiant damage, and the next attack roll against it has advantage.\n\nhttps://5e.tools/spells.html#guiding%20bolt_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Evocation",
  },
  {
    id: "v2_sun_crown_of_stars",
    name: "Crown of Stars",
    description: "Seven motes of starlight orbit you and can be hurled as radiant projectiles.\n\nSource reference: [D&D 5e XGE on 5e.tools](https://5e.tools/spells.html#crown%20of%20stars_xge).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  }
];
