export const metalAbilities = [
  {
    id: "metal_initiate_metalcrafting",
    name: "Metalcrafting",
    description: "You gain proficiency with smith's tools.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_initiate_magnetic_attraction",
    name: "Magnetic Attraction",
    description: "As a bonus action, you can pull or push a metal object weighing up to 10 pounds within 60 feet, moving it up to 10 feet toward or away from you:\n- If the object is carried or worn by a creature, that creature must succeed on a Strength saving throw against your spell save DC. On a failed save, you can choose to either move the creature along with the object or detach the object from the creature.\n- For objects heavier or larger than 10 pounds, you can attempt to move them by making an Intelligence (Arcana) check against a DC determined by the object’s weight and size. Objects far beyond your power remain immovable.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_initiate_metal_sense",
    name: "Metal Sense",
    description: "You can detect the presence of metal within 30 feet of you. You sense the type and general location of metal objects, including hidden compartments or concealed weapons.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_initiate_keen_edge",
    name: "Keen Edge",
    description: "As a bonus action, you can temporarily sharpen a weapon or ammunition, granting it a +1 bonus to attack and damage rolls for the next hour.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_initiate_magnetic_focus",
    name: "Magnetic Focus",
    description: "As a reaction, you can magnetically attract a metal weapon you can see within 30 feet of you to your hand, provided it's not being worn or carried by another creature.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_initiate_metallic_echo",
    name: "Metallic Echo",
    description: "When you strike a metallic object with a melee weapon, you can create a ringing sound that echoes in a 10-foot radius. Creatures in the area must succeed on a Constitution saving throw or be deafened until the end of their next turn.\n\n## Adept Tier",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_adept_enhanced_armor",
    name: "Enhanced Armor",
    description: "You can spend 10 minutes to reinforce any armor. For the next hour, you gain resistance to one type of damage (chosen when you use this ability) while wearing armor.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_adept_magnetic_shield",
    name: "Magnetic Shield",
    description: "As a reaction when you are hit by an attack, you can create a magnetic field that reduces the damage by 1d10 + your Constitution modifier. If the attacker is wielding a metal weapon, they must make a Strength saving throw or be disarmed.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_adept_steel_tornado",
    name: "Steel Tornado",
    description: "As an action, you can create a whirlwind of metallic shards in a 30-foot radius around you. Each creature within the area must make a Dexterity saving throw, taking 7d6 slashing damage on a failed save, or half as much damage on a successful one.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Llamarada Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "metal_adept_gem_cocoon",
    name: "Gem Cocoon",
    description: "As an action, you lock yourself into an immovable, crystalline gem-like shell, gaining temporary hit points equal to 10 × your proficiency bonus + 10. While you possess any of these temporary hit points, your speed is 0, you cannot move or be moved by external forces, and you cannot take actions or reactions. You can dismiss this ability at will on your turn (no action required), losing any remaining temporary hit points. When this ability ends or when the temporary hit points are reduced to 0, you immediately regain normal movement and actions.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Min Gyu",
    location: "Sirius",
  },
  {
    id: "metal_master_weight_of_lives",
    name: "Weight of Lives",
    description: "As an action, target a creature within 60 feet to make a Charisma saving throw. The creature takes 2d8 force damage per karmic debt you discern (up to a maximum of 18d8):\n- **On a failed save:** The creature is restrained for a number of rounds equal to the debts discerned.\n- **On a successful save:** The creature takes half damage, and its speed is halved for 1 round.\n\nRegardless of the outcome, you gain temporary hit points equal to the total force damage dealt.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Shadow Sect",
    location: "Sirius",
  },
  {
    id: "metal_master_black_tortoise_iron_bulwark",
    name: "Black Tortoise Iron Bulwark",
    description: "As an action, you touch a construct, object, structure, or magical wall or barrier (such as a door, vehicle, fortification, or a wall or barrier created by a spell). The target gains temporary hit points equal to 10 × your proficiency bonus + 10. While the target possesses any of these temporary hit points, it gains resistance to all damage.\n\n## Cantrips",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Min Gyu",
    location: "Sirius",
  }
];

export const metalCantrips = [
  {
    id: "metal_cantrip_blade_ward",
    name: "Blade Ward",
    description: "https://5e.tools/spells.html#blade%20ward_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "metal_cantrip_sword_burst",
    name: "Sword Burst",
    description: "https://5e.tools/spells.html#sword%20burst_tce",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const metalSpells = [
  {
    id: "metal_2nd_level_cloud_of_daggers",
    name: "Cloud of Daggers",
    description: "https://5e.tools/spells.html#cloud%20of%20daggers_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_2nd_level_heat_metal",
    name: "Heat Metal",
    description: "https://5e.tools/spells.html#heat%20metal_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_5th_level_animate_objects",
    name: "Animate Objects",
    description: "https://5e.tools/spells.html#animate%20objects_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_6th_level_blade_barrier",
    name: "Blade Barrier",
    description: "https://5e.tools/spells.html#blade%20barrier_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "metal_7th_level_mordenkainens_sword",
    name: "Mordenkainen's Sword",
    description: "https://5e.tools/spells.html#mordenkainen's%20sword_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "v2_metal_magic_weapon",
    name: "Magic Weapon",
    description: "You imbue a weapon with a temporary magical enhancement.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#magic%20weapon_phb).\n\n---\n\n## Spells restored from V1",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "acid_3rd_level_elemental_weapon",
    name: "Elemental Weapon",
    description: "A touched weapon becomes magic, gaining +1 to attack rolls and extra elemental damage.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#elemental%20weapon_xphb).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "metal_3rd_level_enspelled_armament",
    name: "Enspelled Armament",
    description: "An iridescent weapon appears in your hands; you attack with it using your spellcasting ability.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#enspelled%20armament_grimhollowpg24).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "metal_5th_level_pillar_of_force",
    name: "Pillar of Force",
    description: "A pillar of wood or stone thrusts from beneath you, battering a creature and pushing it back.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#pillar%20of%20force_obojimatallgrass).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "acid_5th_level_wall_of_force",
    name: "Wall of Force",
    description: "An invisible, nearly indestructible wall or dome of force blocks everything that tries to pass.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#wall%20of%20force_xphb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "acid_9th_level_blade_of_disaster",
    name: "Blade of Disaster",
    description: "A blade-shaped planar rift strikes for 4d12 force damage and scores critical hits on 18 or higher.\n\nSource reference: [D&D 5e (TCE) on 5e.tools](https://5e.tools/spells.html#blade%20of%20disaster_tce).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (TCE)",
  },
  {
    id: "earth_9th_level_imprisonment",
    name: "Imprisonment",
    description: "You bind a creature in one of several magical prisons (burial, chaining, hedged prison, minimus, or slumber).\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#imprisonment_xphb).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "metal_9th_level_pogmos_pot",
    name: "Pogmo's Pot",
    description: "A cast-iron pot sucks nearby small loose objects into an extradimensional space until the spell ends.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#pogmo's%20pot_obojimatallgrass).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "v2_metal_forcecage",
    name: "Forcecage",
    description: "An invisible, immobile cage or box of magical force traps creatures within it.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#forcecage_xphb).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_metal_iron_body",
    name: "Iron Body",
    description: "A willing creature becomes living metal, gaining resistance to physical and fire damage and immunity to poison, paralysis, and petrification.\n\nSource reference: [D&D 5e (Arcana Unleashed) on 5e.tools](https://5e.tools/spells.html#iron%20body_au).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Arcana Unleashed)",
  }
];
