export const providenceAbilities = [
  {
    id: "water_master_draconic_regeneration_emerald_moon",
    name: "Draconic Regeneration of the Emerald Moon",
    description: "While under direct moonlight, you regain 1 hit point at the start of each of your turns. You can extend this regeneration to any creature within 60 feet by spending 1 essence point per creature at the start of your turn.",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lesbian Dragons",
    location: "Leatrux",
  },
  {
    id: "water_initiate_restorative_rain",
    name: "Restorative Rain",
    description: "As an action, you create a 20-foot radius of gentle rain centered on you that lasts for a number of rounds equal to your maximum Water essences. At the start of each of their turns while in the rain, they regain 1 hit point.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "providence_initiate_unbroken_spirit",
    name: "Unbroken Spirit",
    description: "Your resolve remains steadfast under trial. When you or an ally within 15 feet makes a saving throw against being frightened or charmed, or rolls a death saving throw, the creature adds a d4 to the result. Additionally, when you are below half your maximum hit points, your movement speed cannot be reduced by difficult terrain.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Order of the Broken Arrow (Ilmater)",
  },
  {
    id: "providence_initiate_touch_of_respite",
    name: "Touch of Respite",
    description: "**Casting Time:** 1 action \n**Range:** Touch \n**Components:** V, S \n**Duration:** Instantaneous \n**Portfolio:** Endurance\n\nYou touch a willing creature, granting it immediate relief from minor physical burdens. The target gains **1d4 temporary hit points** and can immediately repeat a saving throw against one condition affecting it: **poisoned** or **one level of exhaustion**. If the target succeeds, the condition or exhaustion level ends.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
  },
  {
    id: "providence_initiate_boon_of_fortitude",
    name: "Boon of Fortitude",
    description: "**Casting Time:** 1 action \n**Range:** 60 feet \n**Components:** V, S \n**Duration:** Concentration, up to 1 minute **Portfolio:** Endurance\n\nYou choose one creature you can see within range. For the duration, the target gains **advantage on saving throws against the frightened and charmed conditions**.\n\nAdditionally, the target becomes **immune to the stunned and incapacitated conditions** if the effect is caused by pain, torture, or physical trauma (such as damage that causes shock, not magical effects). The target is considered to be acting normally despite grievous physical wounds.\n\n## Adept Tier",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
  },
  {
    id: "providence_adept_gift_of_enduring_faith",
    name: "Gift of Enduring Faith",
    description: "**Casting Time:** 1 action \n**Range:** Touch \n**Components:** V, S \n**Duration:** Instantaneous \n**Portfolio:** Endurance\n\nYou touch a living, willing creature. The target instantly regains **10d10 hit points**. You take **necrotic damage equal to half the number of hit points restored**. If this damage reduces you to 0 hit points, you immediately stabilize, but you gain **one level of exhaustion**.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
  },
  {
    id: "providence_adept_endurance_of_ilmater",
    name: "Endurance of Ilmater",
    description: "**Casting Time:** 1 action \n**Range:** Touch \n**Components:** V, S \n**Duration:** Concentration, up to 1 minute **Portfolio:** Endurance\n\nOne willing creature you touch gains **40 temporary hit points**. While the target has these temporary hit points, it has **advantage on Strength and Constitution saving throws**, and **advantage on death saving throws**.\n\nAdditionally, the target **cannot be knocked prone, moved, or grappled** against its will by any nonmagical means.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
  },
  {
    id: "fire_essence_martyrs_flame_aura",
    name: "Martyr’s Flame Aura",
    description: "You wreathe yourself in holy fire for up to 1 minute (requires concentration), creating a 30-foot protective aura centered on you:\n- Friendly creatures within the aura gain resistance to fire damage.\n- When an ally enters the aura or starts its turn inside it, it gains temporary hit points equal to 2d6 + your Charisma modifier.\n\nThe flames warm and protect, never harming your allies.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Mario (Ilmater's Chosen)",
    location: "Leatrux",
  },
  {
    id: "wind_master_essence_liberations_gale",
    name: "Liberation’s Gale",
    description: "A cleansing wind sweeps from you to creatures within 60 feet. Choose up to six targets:\n- Each target immediately ends one of the following conditions affecting it: **Blinded**, **Charmed**, **Deafened**, **Frightened**, **Grappled**, **Paralyzed**, **Petrified**, **Poisoned**, **Restrained**, or **Stunned**.\n- For 1 minute, those creatures also have advantage on saving throws against those same conditions.\n\nIn addition, for 1 minute, you become an unyielding force:\n- You cannot be knocked prone, grappled, restrained, paralyzed, stunned, or moved against your will.\n- Whenever you hit a creature with a melee attack, you may push it 10 feet or knock it prone.\n\n## Cantrips",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Mario (Ilmater's Chosen)",
    location: "Leatrux",
  },
  {
    id: "providence_master_agony_of_the_martyr",
    name: "Agony of the Martyr",
    description: "**Casting Time:** 1 action \n**Range:** 120 feet \n**Components:** V, S \n**Duration:** Concentration, up to 4 rounds **Portfolio:** Endurance\n\nA beam of gray energy strikes one creature you can see. The target makes a **Wisdom saving throw with disadvantage**. On a failed save, the target takes **4d10 necrotic damage** and is **stunned by blinding pain** until the start of your next turn. On a successful save, the target takes half damage and is not stunned, and the spell ends.\n\nAt the start of each of your subsequent turns for the duration, the target must repeat the Wisdom saving throw, this time **without disadvantage**. On a failure, the target takes **4d10 necrotic damage** and remains stunned until the start of your next turn. On a success, the target takes half damage, and the spell ends.\n\n## Cantrips",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
  }
];

export const providenceCantrips = [
  {
    id: "providence_cantrip_spare_the_dying",
    name: "Spare the Dying",
    description: "You touch a living creature that has 0 hit points. The creature becomes stable immediately.\n\nhttps://5e.tools/spells.html#spare%20the%20dying_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Necromancy",
  },
  {
    id: "providence_cantrip_guidance",
    name: "Guidance",
    description: "You touch one willing creature. The target can add 1d4 to one ability check of its choice.\n\nhttps://5e.tools/spells.html#guidance_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Divination",
  },
  {
    id: "providence_cantrip_resistance",
    name: "Resistance",
    description: "You touch one willing creature, granting perseverance. Once before the spell ends, the target can roll a d4 and add it to one saving throw.\n\nhttps://5e.tools/spells.html#resistance_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Abjuration",
  },
  {
    id: "moon_cantrip_sacred_flame",
    name: "Sacred Flame",
    description: "Flame-like solar radiance descends on a creature you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage with no benefit from cover.\n\nhttps://5e.tools/spells.html#sacred%20flame_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Evocation",
  }
];

export const providenceSpells = [
  {
    id: "providence_2nd_lesser_restoration",
    name: "Lesser Restoration",
    description: "You end one disease or condition: blinded, deafened, paralyzed, or poisoned.\n\nhttps://5e.tools/spells.html#lesser%20restoration_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "providence_5th_greater_restoration",
    name: "Greater Restoration",
    description: "You end one debilitating effect: exhaustion levels, charmed/petrified, cursed, or ability reductions.\n\nhttps://5e.tools/spells.html#greater%20restoration_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Abjuration",
  },
  {
    id: "providence_6th_heal",
    name: "Heal",
    description: "A surge of positive energy washes through a creature you touch, restoring 70 hit points and ending all blindness, deafness, and diseases.\n\nhttps://5e.tools/spells.html#heal_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Life Domain)",
  },
  {
    id: "providence_1st_cure_wounds",
    name: "Cure Wounds",
    description: "A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier.\n\nhttps://5e.tools/spells.html#cure%20wounds_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "providence_3rd_revivify",
    name: "Revivify",
    description: "You touch a creature that has died within the last minute, returning it to life with 1 hit point.\n\nhttps://5e.tools/spells.html#revivify_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "v2_life_healing_word",
    name: "Healing Word",
    description: "A spoken prayer restores a small amount of vitality to a creature within range.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#healing%20word_phb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "providence_3rd_beacon_of_hope",
    name: "Beacon of Hope",
    description: "Targets have advantage on Wisdom saves and death saves, and receive the maximum possible healing from any source.\n\nhttps://5e.tools/spells.html#beacon%20of%20hope_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Life & Peace)",
  },
  {
    id: "providence_4th_death_ward",
    name: "Death Ward",
    description: "The first time the target would drop to 0 hit points as a result of taking damage, it instead drops to 1 hit point.\n\nhttps://5e.tools/spells.html#death%20ward_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "providence_2nd_aid",
    name: "Aid",
    description: "Bolster up to three creatures with resolve. Each target's current and maximum hit points increase by 5 for 8 hours.\n\nhttps://5e.tools/spells.html#aid_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "providence_2nd_warding_bond",
    name: "Warding Bond",
    description: "You ward an ally: +1 AC, +1 to saves, resistance to all damage. Whenever the ally takes damage, you take an equal amount of damage.\n\nhttps://5e.tools/spells.html#warding%20bond_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Peace Domain",
  },
  {
    id: "providence_4th_freedom_of_movement",
    name: "Freedom of Movement",
    description: "Target's movement is unaffected by difficult terrain, and spells cannot reduce speed or paralyze/restrain it.\n\nhttps://5e.tools/spells.html#freedom%20of%20movement_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "v2_providence_bless",
    name: "Bless",
    description: "Several creatures gain a small measure of divine aid on attacks and saving throws.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#bless_phb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  }
];
