export const providenceAbilities = [
  {
    id: "providence_initiate_unbroken_spirit",
    name: "Unbroken Spirit",
    description: "Your resolve remains steadfast under trial. When you or an ally within 15 feet makes a saving throw against being frightened or charmed, or rolls a death saving throw, the creature adds a d4 to the result. Additionally, when you are below half your maximum hit points, your movement speed cannot be reduced by difficult terrain.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Order of the Broken Arrow (Ilmater)",
    location: "Leatrux",
  },
  {
    id: "providence_initiate_touch_of_respite",
    name: "Touch of Respite",
    description: "**Casting Time:** 1 action \n**Range:** Touch \n**Components:** V, S \n**Duration:** Instantaneous \n**Portfolio:** Endurance\n\nYou touch a willing creature, granting it immediate relief from minor physical burdens. The target gains **1d4 temporary hit points** and can immediately repeat a saving throw against one condition affecting it: **poisoned** or **one level of exhaustion**. If the target succeeds, the condition or exhaustion level ends.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
    location: "Leatrux",
  },
  {
    id: "providence_initiate_boon_of_fortitude",
    name: "Boon of Fortitude",
    description: "**Casting Time:** 1 action \n**Range:** 60 feet \n**Components:** V, S \n**Duration:** Concentration, up to 1 minute **Portfolio:** Endurance\n\nYou choose one creature you can see within range. For the duration, the target gains **advantage on saving throws against the frightened and charmed conditions**.\n\nAdditionally, the target becomes **immune to the stunned and incapacitated conditions** if the effect is caused by pain, torture, or physical trauma (such as damage that causes shock, not magical effects). The target is considered to be acting normally despite grievous physical wounds.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
    location: "Leatrux",
  },
  {
    id: "providence_adept_gift_of_enduring_faith",
    name: "Gift of Enduring Faith",
    description: "**Casting Time:** 1 action \n**Range:** Touch \n**Components:** V, S \n**Duration:** Instantaneous \n**Portfolio:** Endurance\n\nYou touch a living, willing creature. The target instantly regains **10d10 hit points**. You take **necrotic damage equal to half the number of hit points restored**. If this damage reduces you to 0 hit points, you immediately stabilize, but you gain **one level of exhaustion**.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
    location: "Leatrux",
  },
  {
    id: "providence_adept_endurance_of_ilmater",
    name: "Endurance of Ilmater",
    description: "**Casting Time:** 1 action \n**Range:** Touch \n**Components:** V, S \n**Duration:** Concentration, up to 1 minute **Portfolio:** Endurance\n\nOne willing creature you touch gains **40 temporary hit points**. While the target has these temporary hit points, it has **advantage on Strength and Constitution saving throws**, and **advantage on death saving throws**.\n\nAdditionally, the target **cannot be knocked prone, moved, or grappled** against its will by any nonmagical means.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
    location: "Leatrux",
  },
  {
    id: "fire_essence_martyrs_flame_aura",
    name: "Martyr’s Flame Aura",
    description: "You wreathe yourself in holy fire for up to 1 minute (requires concentration), creating a 30-foot protective aura centered on you:\n- Friendly creatures within the aura gain resistance to fire damage.\n- When an ally enters the aura or starts its turn inside it, it gains temporary hit points equal to 2d6 + your Charisma modifier.\n\nThe flames warm and protect, never harming your allies.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Mario (Ilmater's Chosen)",
    location: "Leatrux",
  },
  {
    id: "wind_master_essence_liberations_gale",
    name: "Liberation’s Gale",
    description: "A cleansing wind sweeps from you to creatures within 60 feet. Choose up to six targets:\n- Each target immediately ends one of the following conditions affecting it: **Blinded**, **Charmed**, **Deafened**, **Frightened**, **Grappled**, **Paralyzed**, **Petrified**, **Poisoned**, **Restrained**, or **Stunned**.\n- For 1 minute, those creatures also have advantage on saving throws against those same conditions.\n\nIn addition, for 1 minute, you become an unyielding force:\n- You cannot be knocked prone, grappled, restrained, paralyzed, stunned, or moved against your will.\n- Whenever you hit a creature with a melee attack, you may push it 10 feet or knock it prone.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Mario (Ilmater's Chosen)",
    location: "Leatrux",
  },
  {
    id: "providence_master_agony_of_the_martyr",
    name: "Agony of the Martyr",
    description: "**Casting Time:** 1 action \n**Range:** 120 feet \n**Components:** V, S \n**Duration:** Concentration, up to 4 rounds **Portfolio:** Endurance\n\nA beam of gray energy strikes one creature you can see. The target makes a **Wisdom saving throw with disadvantage**. On a failed save, the target takes **4d10 necrotic damage** and is **stunned by blinding pain** until the start of your next turn. On a successful save, the target takes half damage and is not stunned, and the spell ends.\n\nAt the start of each of your subsequent turns for the duration, the target must repeat the Wisdom saving throw, this time **without disadvantage**. On a failure, the target takes **4d10 necrotic damage** and remains stunned until the start of your next turn. On a success, the target takes half damage, and the spell ends.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Ilmater / Portfolio (Endurance)",
    location: "Leatrux",
  },
  {
    id: "wind_adept_fortune_favors_the_swift",
    name: "Fortune Favors the Swift",
    description: "Whenever you expend a spell slot, you gain a d6 “wind die”. You can add it to one d20 roll before the end of your next turn.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Wang Dabao",
    location: "Phudara / Isle of Whispers",
  }
];

export const providenceCantrips = [
  {
    id: "providence_cantrip_spare_the_dying",
    name: "Spare the Dying",
    description: "You touch a living creature that has 0 hit points. The creature becomes stable immediately.\n\nhttps://5e.tools/spells.html#spare%20the%20dying_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Necromancy",
  },
  {
    id: "providence_cantrip_guidance",
    name: "Guidance",
    description: "You touch one willing creature. The target can add 1d4 to one ability check of its choice.\n\nhttps://5e.tools/spells.html#guidance_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Divination",
  },
  {
    id: "providence_cantrip_resistance",
    name: "Resistance",
    description: "You touch one willing creature, granting perseverance. Once before the spell ends, the target can roll a d4 and add it to one saving throw.\n\nhttps://5e.tools/spells.html#resistance_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Abjuration",
  }
];

export const providenceSpells = [
  {
    id: "providence_3rd_beacon_of_hope",
    name: "Beacon of Hope",
    description: "Targets have advantage on Wisdom saves and death saves, and receive the maximum possible healing from any source.\n\nhttps://5e.tools/spells.html#beacon%20of%20hope_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Life & Peace)",
  },
  {
    id: "providence_4th_death_ward",
    name: "Death Ward",
    description: "The first time the target would drop to 0 hit points as a result of taking damage, it instead drops to 1 hit point.\n\nhttps://5e.tools/spells.html#death%20ward_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "providence_2nd_aid",
    name: "Aid",
    description: "Bolster up to three creatures with resolve. Each target's current and maximum hit points increase by 5 for 8 hours.\n\nhttps://5e.tools/spells.html#aid_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "providence_2nd_warding_bond",
    name: "Warding Bond",
    description: "You ward an ally: +1 AC, +1 to saves, resistance to all damage. Whenever the ally takes damage, you take an equal amount of damage.\n\nhttps://5e.tools/spells.html#warding%20bond_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Peace Domain",
  },
  {
    id: "providence_4th_freedom_of_movement",
    name: "Freedom of Movement",
    description: "Target's movement is unaffected by difficult terrain, and spells cannot reduce speed or paralyze/restrain it.\n\nhttps://5e.tools/spells.html#freedom%20of%20movement_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Paladin",
  },
  {
    id: "v2_providence_bless",
    name: "Bless",
    description: "Several creatures gain a small measure of divine aid on attacks and saving throws.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#bless_phb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "providence_1st_heroism",
    name: "Heroism",
    description: "A willing creature is imbued with bravery: immune to being frightened, and gains temporary HP at the start of each turn.\n\nhttps://5e.tools/spells.html#heroism_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Paladin / Cleric (Peace Domain)",
  },
  {
    id: "acid_1st_level_absorb_elements",
    name: "Absorb Elements",
    description: "As a reaction you gain resistance to incoming elemental damage and add it to your next melee hit.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#absorb%20elements_xge).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "acid_3rd_level_glyph_of_warding",
    name: "Glyph of Warding",
    description: "You inscribe a hidden glyph that releases an explosion or a stored spell when triggered.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#glyph%20of%20warding_xphb).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_3rd_level_leomunds_tiny_hut",
    name: "Leomund's Tiny Hut",
    description: "A dome of force shelters you and your companions and keeps others and outside magic out.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#leomund's%20tiny%20hut_xphb).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_3rd_level_spirit_guardians",
    name: "Spirit Guardians",
    description: "Protective spirits circle you, slowing enemies and dealing radiant or necrotic damage to them.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#spirit%20guardians_xphb).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_4th_level_guardian_of_faith",
    name: "Guardian of Faith",
    description: "A spectral guardian of your deity damages each enemy that comes near it, until it has dealt 60 damage.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#guardian%20of%20faith_xphb).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_6th_level_planar_ally",
    name: "Planar Ally",
    description: "You beseech a powerful being, who sends a celestial, elemental, or fiend to aid you in exchange for payment.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#planar%20ally_xphb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_providence_circle_of_power",
    name: "Circle of Power",
    description: "A 30-foot aura gives you and your allies advantage on saves against magic, and successful saves against half-damage effects deal no damage.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#circle%20of%20power_xphb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_providence_holy_weapon",
    name: "Holy Weapon",
    description: "A weapon you touch shines with holy light and deals an extra 2d8 radiant damage; you can dismiss it in a radiant burst that blinds foes.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#holy%20weapon_xge).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "v2_providence_heroes_feast",
    name: "Heroes' Feast",
    description: "Up to twelve creatures share a feast that cures poison and disease and grants poison immunity, fear immunity, advantage on Wisdom saves, and extra hit points for 24 hours.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#heroes'%20feast_xphb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_providence_power_word_fortify",
    name: "Power Word Fortify",
    description: "Up to six creatures you can see share 120 temporary hit points.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#power%20word%20fortify_xphb).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_providence_holy_aura",
    name: "Holy Aura",
    description: "A 30-foot aura gives allies advantage on all saves and imposes disadvantage on attacks against them; fiends and undead that strike them are blinded.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#holy%20aura_xphb).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_providence_perfection",
    name: "Perfection",
    description: "A holy word remakes a creature in an Arch Seraph’s image: fully healed, curses suppressed, ability scores below 18 raised to 18, and a seraph’s blessing.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#perfection_grimhollowpg24).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "v2_providence_phoenix_flames",
    name: "Phoenix Flames",
    description: "You die in a burst of holy fire that deals 30d6 radiant damage around you, then rise from the ashes 10 minutes later.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#phoenix%20flames_grimhollowpg24).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "v2_providence_power_word_shield",
    name: "Power Word Shield",
    description: "A word shields a creature: until the end of its next turn it is immune to all but psychic damage and has advantage on saves.\n\nSource reference: [Heliana's Guide to Monster Hunting on 5e.tools](https://5e.tools/spells.html#power%20word%20shield_helianasguidetomonsterhunting).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Heliana's Guide to Monster Hunting",
  },
  {
    id: "wood_7th_level_conjure_celestial",
    name: "Conjure Celestial",
    description: "A pillar of celestial light heals allies and sears enemies within it; you can move it each turn.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#conjure%20celestial_xphb).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  }
];
