export const ruinAbilities = [
  {
    id: "ruin_adept_decay",
    name: "Decay",
    description: "**Casting Time:** 1 action  \n**Range:** Touch  \n**Components:** V, S, M (a holy symbol)  \n**Duration:** Permanent  \n**Portfolio:** Murder\n\nYou touch nonliving material up to 1 cubic foot per caster level and accelerate its aging process. For every hour that passes, the affected material ages 1 day. Additionally, any stress or strain on the material is magnified twentyfold.\n\nAfter sufficient time, most objects break, rust, corrode, decay into powder, or otherwise become useless. A _dispel magic_ spell halts the accelerated decay but cannot reverse aging that has already occurred.\n\nNormal items receive no saving throw. Magic items must make a Constitution saving throw against your spell DC with disadvantage or be affected. Artifacts and legendary items are immune to this effect.\n\nTo affect an item being worn or carried by an unwilling creature, you must make a melee spell attack against the creature.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Bhaal / Portfolio (Murder)",
  },
  {
    id: "ruin_initiate_blood_scent",
    name: "Blood Scent",
    description: "You instinctively track the scent of open wounds. You have advantage on Wisdom (Perception) and Wisdom (Survival) checks to detect or track any creature that is below its hit point maximum. In addition, your weapon attacks deal an extra 1d4 damage against targets below half their maximum hit points.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Cult of the Lord of Murder",
  },
  {
    id: "ruin_initiate_bhaal_s_tribute",
    name: "Bhaal's Tribute",
    description: "**Casting Time:** 10 minutes  \n**Range:** Touch  \n**Components:** V, S, M (a corpse that died within the last 24 hours)  \n**Duration:** Instantaneous  \n**Portfolio:**  Murder\n\nYou perform a dark ritual using a recently deceased body to erase all evidence of a murder. When you cast this spell, you must touch a corpse that has died within the last 24 hours. The spell affects a 30-foot radius centered on the corpse.\n\nAll of the following evidence within the area is completely destroyed:\n- Blood stains, tracks, and other physical traces of violence\n- Scent trails that could be followed by creatures or magic\n- Divination magic targeting events that occurred in the area becomes unable to detect anything related to the murder\n- The corpse itself dissolves into ash that scatters on an unfelt wind\n\nAny creature that witnessed the events and is within the area when the spell is cast must make a Wisdom saving throw. On a failed save, their memories of the murder become hazy and unclear, as if viewed through fog (they remember something happened but cannot recall specific details).\n\n## Adept Tier",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Bhaal / Portfolio (Murder)",
  },
  {
    id: "ruin_adept_mark_for_death",
    name: "Mark for Death",
    description: "**Casting Time:** 1 bonus action  \n**Range:** 60 feet  \n**Components:** V, S, M (a black arrow or dagger)  \n**Duration:** 1 minute  \n**Portfolio:** Murder\n\nYou mark one creature you can see within range for assassination. The target must make a Wisdom saving throw. On a successful save, the spell fails. On a failed save, the target is doomed to die and gains the following effects for the duration:\n\n- You have advantage on attack rolls against the marked creature\n- When you hit the marked creature with an attack, it takes an additional 1d8 necrotic damage\n- The marked creature cannot benefit from temporary hit points or healing of any kind\n- The marked creature has disadvantage on death saving throws\n\nThe marked creature feels an overwhelming sense of impending doom.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Bhaal / Portfolio (Murder)",
  },
  {
    id: "ruin_master_mass_inflict_wounds",
    name: "Mass Inflict Wounds",
    description: "**Casting Time:** 1 action  \n**Range:** 60 feet  \n**Components:** V, S  \n**Duration:** Instantaneous  \n**Portfolio:**  Murder\n\nA wave of necromantic energy washes out from a point you can see within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target must make a Constitution saving throw. On a failed save, a creature takes 5d10 necrotic damage. On a successful save, the creature takes half as much damage.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Bhaal / Portfolio (Murder)",
  },
  {
    id: "wind_master_sky_piercing_execution",
    name: "Sky-Piercing Execution",
    description: "As a reaction when a creature within 60 feet is airborne or suspended, teleport to an adjacent empty space in the air. Make one piercing melee weapon attack against it. On a hit, the target suffers the attack's normal damage plus an extra 4d10 thunder damage, The target must succeed on a Strength saving throw against your essence ability save DC or fall up to 60 feet, land prone, and take the normal falling damage. On a successful save, it remains airborne.\n\n## Grandmaster Tier",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Yoo Tae-yang",
    location: "Sirius",
  },
  {
    id: "ruin_grandmaster_mark_of_doom",
    name: "Mark of Doom",
    description: "**Casting Time:** 1 bonus action  \n**Range:** Any distance (on same plane)  \n**Components:** V, S, M (an object belonging to the target or blood from a relative of the target)  \n**Duration:** 24 hours  \n**Portfolio:** Murder\n\nYou mark a single creature for death, targeting them through a personal connection. The target must make a Wisdom saving throw. On a successful save, the spell fails and the material component is consumed.\n\nOn a failed save, the target is marked for death and suffers the following effects for the duration:\n\n- The target automatically fails all saving throws against divination spells and effects that would locate or track them\n- The target automatically fails all death saving throws\n- You have advantage on all attack rolls against the target\n\nThe marked creature feels a sense of impending doom but doesn't know the source. This spell can only affect one creature at a time per caster. If you cast this spell again while a creature is already marked, the previous mark ends.\n\n## Cantrips",
    tier: "grandmaster",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Bhaal / Portfolio (Murder)",
  },
  {
    id: "torment_initiate_whips_kiss",
    name: "Whip's Kiss",
    description: "You channel vitality through inflicting suffering. When you hit a creature with an attack, you can invoke barbed ethereal lashes to lacerate the foe, dealing an additional 1d6 piercing damage. The target must succeed on a Wisdom saving throw or have disadvantage on its next attack roll.\n\n## Adept Tier",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Maiden of Pain (Loviatar)",
  },
  {
    id: "fire_initiate_heart_crusher_grip",
    name: "Heart Crusher Grip (Nilo)",
    description: "As an action, you can target one bloodied creature you can see within 15 feet of you. The target must make a Constitution saving throw, taking 6d6 fire damage on a failed save, or half as much damage on a successful one. If this damage reduces the target to 0 hit points, its heart is crushed and it dies instantly.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Xu Ning (Lime's ancestor)",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "fire_adept_frightful_pursuit",
    name: "Frightful Pursuit",
    description: "You have advantage on attack rolls against any creature that is currently frightened.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    location: "Sirius",
  },
  {
    id: "torment_adept_blood_tithe",
    name: "Blood Tithe",
    description: "Whenever a creature within 30 feet takes damage from your attacks or spells, you convert their agony into physical resilience, gaining temporary hit points equal to your character level.\n\n## Master Tier",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Maiden of Pain (Loviatar)",
  },
  {
    id: "torment_master_crown_of_agony",
    name: "Crown of Agony",
    description: "You wreath yourself in a mantle of barbed needles and psychic torment for 1 minute. Any creature that hits you with a melee attack takes psychic damage equal to the damage dealt or 3d8 (whichever is lower), and cannot take reactions until the start of its next turn.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Maiden of Pain (Loviatar)",
  },
  {
    id: "ruin_adept_assassins_shroud",
    name: "Assassin's Shroud",
    description: "As a bonus action, you cloak yourself in deceptive shadows for 1 minute. While cloaked, you make no sound when moving and leave behind neither physical footprints nor forensic trace. The first attack you hit while cloaked deals an extra 2d6 necrotic damage and ends the cloak.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Cult of Cyric",
  }
];

export const ruinCantrips = [
  {
    id: "ruin_cantrip_toll_the_dead",
    name: "Toll the Dead",
    description: "You point at one creature. The sound of a dolorous death bell tolls, dealing 1d8 necrotic damage (or 1d12 if the target is injured).\n\nhttps://5e.tools/spells.html#toll%20the%20dead_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Necromancy",
  },
  {
    id: "ruin_cantrip_chill_touch",
    name: "Chill Touch",
    description: "Assail a foe with deadly chill, dealing 1d8 necrotic damage and stopping it from regaining hit points.\n\nhttps://5e.tools/spells.html#chill%20touch_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric (Death Domain) / Necromancy",
  },
  {
    id: "torment_cantrip_vicious_mockery",
    name: "Vicious Mockery",
    description: "Unleash strings of barbed insults and psychic cruelty, dealing 1d4 psychic damage and giving disadvantage on its next attack.\n\nhttps://5e.tools/spells.html#vicious%20mockery_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Enchantment / Torment",
  },
  {
    id: "torment_cantrip_mind_sliver",
    name: "Mind Sliver",
    description: "Drive a disorienting spike of psychic pain into a creature's mind: 1d6 psychic damage and -1d4 on its next saving throw.\n\nhttps://5e.tools/spells.html#mind%20sliver_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Enchantment / Psionic",
  },
  {
    id: "v2_mystery_mage_hand",
    name: "Mage Hand",
    description: "You create a small floating hand that can manipulate or carry light objects at a distance.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#mage%20hand_phb).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB)",
  }
];

export const ruinSpells = [
  {
    id: "ruin_3rd_vampiric_touch",
    name: "Vampiric Touch",
    description: "Siphon life from your victim. Melee spell attack deals 3d6 necrotic damage and heals you for half.\n\nhttps://5e.tools/spells.html#vampiric%20touch_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Death Domain) / Necromancy",
  },
  {
    id: "ruin_6th_circle_of_death",
    name: "Circle of Death",
    description: "A 60-foot-radius slaughter sphere deals 8d6 necrotic damage to all creatures caught within.\n\nhttps://5e.tools/spells.html#circle%20of%20death_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Death Domain) / Necromancy",
  },
  {
    id: "ruin_7th_finger_of_death",
    name: "Finger of Death",
    description: "Devastating murder decree deals 7d8 + 30 necrotic damage and rises humanoid slain as a permanent zombie servant.\n\nhttps://5e.tools/spells.html#finger%20of%20death_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Death Domain) / Necromancy",
  },
  {
    id: "ruin_1st_hunters_mark",
    name: "Hunter's Mark",
    description: "You mark a creature as your quarry. Deal an extra 1d6 damage whenever you hit it with a weapon attack.\n\nhttps://5e.tools/spells.html#hunter's%20mark_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Paladin (Oath of Vengeance)",
  },
  {
    id: "ruin_9th_power_word_kill",
    name: "Power Word Kill",
    description: "Utter a word of lethal demise to kill a creature instantly if it has 100 hit points or fewer.\n\nhttps://5e.tools/spells.html#power%20word%20kill_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Death",
  },
  {
    id: "torment_1st_inflict_wounds",
    name: "Inflict Wounds",
    description: "Deliver searing necrotizing pain through touch, dealing 3d10 necrotic damage on a melee spell attack.\n\nhttps://5e.tools/spells.html#inflict%20wounds_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Necromancy",
  },
  {
    id: "torment_6th_harm",
    name: "Harm",
    description: "The pinnacle of agonizing biological ruin: inflicts 14d6 necrotic damage and reduces hit point maximum.\n\nhttps://5e.tools/spells.html#harm_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Necromancy",
  },
  {
    id: "v2_moon_mislead",
    name: "Mislead",
    description: "You become invisible while leaving a convincing illusory double behind.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#mislead_phb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_moon_seeming",
    name: "Seeming",
    description: "You reshape the apparent appearance of a group of creatures for a long duration.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#seeming_phb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "torment_7th_power_word_pain",
    name: "Power Word Pain",
    description: "Utter a word of power that causes overwhelming physical suffering, reducing speed to 10 ft and giving disadvantage on attacks and checks.\n\nhttps://5e.tools/spells.html#power%20word%20pain_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Enchantment / Pure Agony",
  }
];
