export const shadowAbilities = [
  {
    id: "fire_master_essence_shadowflame_dream",
    name: "Shadowflame Dream",
    description: "As an action, you hurl a swirling torrent of flames laced with negative energy at one creature within 60 feet. The target must make a Charisma saving throw against your essence ability save DC:\n- **On a failed save:** The creature takes 5d10 fire damage and 5d10 necrotic damage, and falls unconscious until the start of your next turn.\n- **On a successful save:** The target takes only the fire damage and is not affected by the unconscious condition.",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Shadow Sect",
    location: "Sirius",
  },
  {
    id: "void_adept_netherdark_fist_ii",
    name: "Netherdark Fist II: Voidstride",
    description: "*Prerequisite: Netherdark Fist*\n\nWhen you use Netherdark Fist, you can spend **2 essences** instead of 1:\n\n- Your movement before the strike does not provoke opportunity attacks.\n- The damage increases to **4d10 force damage**.\n- On a failed save, the target's speed is reduced by 10 feet until the start of your next turn as shadowy tendrils latch onto them.\n\n## Master Tier",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Yuji",
    location: "Leatrux",
  },
  {
    id: "void_master_netherdark_fist_iii",
    name: "Netherdark Fist III: Gravitic Collapse",
    description: "*Prerequisite: Netherdark Fist II*\n\nWhen you use Netherdark Fist, you can spend **3 essences**:\n\n- You can move up to your full speed without provoking opportunity attacks before the strike.\n- The damage increases to **6d10 force damage**.\n- On a failed save, the target is knocked prone and cannot take reactions until the start of your next turn.\n\n## Grandmaster Tier",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Yuji",
    location: "Leatrux",
  },
  {
    id: "acid_grandmaster_ethereal_phase_barrier",
    name: "Ethereal Phase Barrier",
    description: "When you cast wall of force, the wall manifests on the Ethereal Plane rather than the Material Plane, appearing as a shimmering, translucent membrane of acidic essence. The spell no longer requires concentration.\n\nThe wall cannot be destroyed or dispelled by any attack, spell, or magical effect unless that effect originates from the Ethereal Plane or is capable of transcending planar boundaries.\n\n**Essence Refinement.** When you cast wall of force with this feature, you may imbue it with additional essences. For each essence spent, choose one of the following benefits:\n\n- Extend the wall's duration by 1 hour.\n- Increase the wall's size by an additional 10-foot radius (or equivalent panel area).",
    tier: "grandmaster",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Malzareth (Dryad Cyric Cultist)",
    location: "Sirius",
  },
  {
    id: "void_initiate_shadow_veil",
    name: "Shadow Veil",
    description: "You wrap yourself in the silence and obscurity of the Void. You gain darkvision out to 60 feet (or increase existing darkvision by 30 feet). While you are in dim light or darkness, you have advantage on Dexterity (Stealth) checks and can take the Hide action as a bonus action.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Shar's Shadow Disciple",
  },
  {
    id: "void_initiate_netherdark_fist",
    name: "Netherdark Fist",
    description: "**Action | Range:** Half your maximum speed\n\nYou can move up to half your maximum speed before making this strike. You channel the crushing emptiness of the void into a strike against a single creature within range. The target must make a Charisma saving throw against your essence ability save DC.\n\n- **Failed Save:** The creature takes 2d10 force damage.\n- **Successful Save:** The creature takes half damage.\n\n## Adept Tier",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Yuji",
    location: "Leatrux",
  },
  {
    id: "wind_adept_umbral_form",
    name: "Umbral Form",
    description: "As a bonus action, you flatten and dissolve your physical form into a living shadow for up to 10 minutes. You can dismiss this effect at any time at will (no action required). The effect ends immediately if you make an attack roll or cast a spell.\n\nWhile in this form, you gain the following benefits:\n- **Shadow Invisibility:** While you are in dim light, darkness, or within the shadow cast by an object or creature of your size or larger, you are invisible. If you step into bright light (outside of a shadow), you are exposed and visible until you enter shadow again.\n- **Shadow Leap:** While in a shadow, you can use a bonus action to teleport up to 30 feet to an unoccupied space you can see that is also in dim light, darkness, or within the shadow of an object or creature of your size or larger. This teleport allows you to cross illuminated areas without being exposed.\n- **Fluid Silhouette:** You can move through spaces as narrow as 1 inch wide without squeezing, and you can move through the spaces of other creatures.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Kwon Jae-Hwan",
    location: "Sirius",
  },
  {
    id: "void_adept_armor_of_darkness",
    name: "Armor of Darkness",
    description: "**Casting Time:** 1 action\n**Range:** Self \n**Components:** V, S, M (a shard of polished obsidian) \n**Duration:** 1 hour\n**Portfolio:**  Darkness\n\nYou summon a suit of armor woven from solidified shadow that wreathes your form. This armor provides a shadowy veil that grants you a **+2 bonus to your Armor Class** and resistance to **necrotic and radiant damage**.\n\nWhile you are in dim light or darkness, you gain partial concealment from the shadows. Attack rolls against you have disadvantage, and you have advantage on Dexterity (Stealth) checks.\n\nAdditionally, the first time you hit a creature with an attack while you are in dim light or darkness, the target takes an extra **2d6 necrotic damage**.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Portfolio (Darkness / Shar)",
  },
  {
    id: "void_adept_darkbolt",
    name: "Darkbolt",
    description: "**Casting Time:** 1 action\n**Range:** 120 feet\n**Components:** S\n**Duration:** Concentration, up to 1 minute\n**Portfolio:** Murder\n\nYou create a 4-inch beam of darkness that streaks toward a creature within range. Make a ranged spell attack. On a hit, the target takes **5d8 force damage** and must make a Constitution saving throw. On a failed save, the target is **silenced for the duration of the spell** and cannot speak or cast spells with verbal components. The target can repeat the saving throw at the end of each of its turns, ending the silence on a success.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Portfolio (Darkness / Shar)",
  },
  {
    id: "void_grandmaster_netherdark_fist_iv",
    name: "Netherdark Fist IV: Reality Rend",
    description: "*Prerequisite: Netherdark Fist III*\n\nWhen you use Netherdark Fist, you can spend **4 essences**:\n\n- The damage increases to **8d10 force damage**.\n- On a failed save, the target cannot regain hit points until the end of your next turn and subtracts 1d4 from the next saving throw it makes within 1 minute.\n\n## Greatgrandmaster Tier",
    tier: "grandmaster",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Yuji",
    location: "Leatrux",
  },
  {
    id: "void_greatgrandmaster_netherdark_fist_v",
    name: "Netherdark Fist V: Absolute Oblivion",
    description: "*Prerequisite: Netherdark Fist IV*\n\nWhen you use Netherdark Fist, you can spend **5 essences** to unleash the full devastating potential of the void:\n\n- The damage increases to **10d10 force damage**.\n- On a failed save, the target gains 1 level of exhaustion as reality itself buckles around them and the void tears at their very essence.\n\n## Cantrips",
    tier: "greatgrandmaster",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Yuji",
    location: "Leatrux",
  }
];

export const shadowCantrips = [
  {
    id: "void_cantrip_minor_illusion",
    name: "Minor Illusion",
    description: "You create a sound or an image of an object within range that lasts for the duration to deceive observers.\n\nhttps://5e.tools/spells.html#minor%20illusion_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric (Trickery) / Illusion",
  }
];

export const shadowSpells = [
  {
    id: "void_7th_etherealness",
    name: "Etherealness",
    description: "You step into the border regions of the Ethereal Plane, moving through objects and creatures on the Material Plane as a ghost.\n\nhttps://5e.tools/spells.html#etherealness_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Transmutation",
  },
  {
    id: "void_2nd_blindness_deafness",
    name: "Blindness/Deafness",
    description: "You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw or be blinded or deafened for the duration.\n\nhttps://5e.tools/spells.html#blindness%2Fdeafness_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Necromancy",
  },
  {
    id: "void_8th_antimagic_field",
    name: "Antimagic Field",
    description: "A 10-foot-radius invisible sphere of antimagic surrounds you. Spells cannot be cast and magical effects are utterly suppressed.\n\nhttps://5e.tools/spells.html#antimagic%20field_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Abjuration (Severance)",
  },
  {
    id: "void_2nd_pass_without_trace",
    name: "Pass without Trace",
    description: "A veil of shadows and silence radiates from you, giving each chosen creature within 30 feet a +10 bonus to Dexterity (Stealth) checks.\n\nhttps://5e.tools/spells.html#pass%20without%20trace_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Trickery Domain) / Abjuration",
  },
  {
    id: "void_2nd_darkness",
    name: "Darkness",
    description: "Magical darkness fills a 15-foot-radius sphere. Creatures with normal darkvision cannot see through it, and nonmagical light cannot illuminate it.\n\nhttps://5e.tools/spells.html#darkness_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Trickery Domain) / Evocation",
  },
  {
    id: "void_2nd_silence",
    name: "Silence",
    description: "No sound can be created within or pass through a 20-foot-radius sphere. Casting a spell with a verbal component is impossible there.\n\nhttps://5e.tools/spells.html#silence_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Illusion",
  },
  {
    id: "void_3rd_hunger_of_hadar",
    name: "Hunger of Hadar",
    description: "You open a gateway to the dark between the stars. A 20-foot-radius sphere of blackness and bitter cold appears, dealing cold and acid damage.\n\nhttps://5e.tools/spells.html#hunger%20of%20hadar_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Void / Conjuration",
  },
  {
    id: "void_3rd_nondetection",
    name: "Nondetection",
    description: "For the duration, you hide a target from divination magic and scrying sensors.\n\nhttps://5e.tools/spells.html#nondetection_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Trickery Domain) / Abjuration",
  },
  {
    id: "void_4th_greater_invisibility",
    name: "Greater Invisibility",
    description: "You or a creature you touch becomes invisible for 1 minute, even when attacking or casting spells.\n\nhttps://5e.tools/spells.html#greater%20invisibility_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Twilight/Trickery) / Illusion",
  },
  {
    id: "void_4th_shadow_of_moil",
    name: "Shadow of Moil",
    description: "Flame-like shadows wreathe your body, heavily obscuring you and dealing 2d8 necrotic damage to any creature within 10 feet that hits you.\n\nhttps://5e.tools/spells.html#shadow%20of%20moil_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Shadow Weave / Necromancy",
  },
  {
    id: "void_8th_maddening_darkness",
    name: "Maddening Darkness",
    description: "Darkness and screaming horrors fill a 60-foot-radius sphere. Creatures in the area take 8d8 psychic damage on a failed Wisdom save.\n\nhttps://5e.tools/spells.html#maddening%20darkness_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Shadow Weave / Evocation",
  }
];
