export const skyAbilities = [
  {
    id: "wind_initiate_thunderous_roar",
    name: "Thunderous Roar",
    description: "You can let out a powerful roar that creates a shockwave, forcing all creatures within 10 feet to make a Constitution saving throw or be pushed 10 feet away from you and become deafened for 1 minute.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_initiate_static_reflexes",
    name: "Static Reflexes",
    description: "You gain advantage on Dexterity saving throws against effects that deal lightning damage or require quick reflexes, such as traps or spells.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_initiate_mistbound_step",
    name: "Mistbound Step",
    description: "The Misty Step spell does not consume a spell slot if you begin or end your movement in a heavily obscured area.\n\n---\n\n## Adept Tier",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_adept_lightning_javelin",
    name: "Lightning Javelin",
    description: "You hurl a javelin of pure lightning at a target within 60 feet. Make a ranged spell attack:\n- **On a hit:** The target takes 5d12 lightning damage and cannot take reactions until the start of its next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_essence_arc_chain",
    name: "Arc Chain",
    description: "Choose a creature within 120 feet. The target must make a Dexterity saving throw, taking 3d8 lightning damage on a failed save, or half as much on a successful one.\n\nIf the target fails its saving throw, the arc leaps to another creature within 30 feet of it that hasn’t been struck yet, forcing the same saving throw. The chain continues jumping to new creatures until a target succeeds on its save or no valid targets remain within range.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Nethan (Nilo's Father)",
    location: "Leatrux",
  },
  {
    id: "lightning_adept_conductive_touch",
    name: "Conductive Touch",
    description: "When you hit a creature with a melee attack, you can choose to deal an extra 2d12 lightning damage.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_initiate_lightning_step",
    name: "Lightning Step",
    description: "As a bonus action, you can harness the power of lightning to enhance your movement. Your jump distance is tripled, and your movement does not provoke opportunity attacks until the end of your turn.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_adept_lightning_sense",
    name: "Lightning Sense",
    description: "You have developed a heightened sense of awareness in stormy or electrically charged environments. You gain advantage on Wisdom (Perception) checks to notice hidden details or track creatures in such conditions.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_essence_lightning_cage",
    name: "Lightning Cage",
    description: "You conjure a crackling triangular cage of lightning in a 30-foot area centered on a point within 90 feet, lasting for 1 minute:\n- Creatures inside have their speed halved and cannot take reactions.\n- Any creature that touches or attempts to pass through the cage's perimeter takes 4d10 lightning damage.\n- A creature trapped inside can use an action to make a Strength saving throw to break through: on a failed save, it remains trapped and takes 4d10 lightning damage; on a successful save, it escapes and takes half damage.\n\n## Spells",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Nethan (Nilo's Father)",
    location: "Leatrux",
  },
  {
    id: "wind_adept_calm_breeze",
    name: "Calm Breeze",
    description: "You can use a bonus action to create a soothing breeze that relaxes and calms creatures within a 30-foot radius, providing them with advantage on saving throws against being frightened or charmed. This effect lasts for 10 minutes.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_thunderstep",
    name: "Thunderstep",
    description: "You can use an action to make a sudden, loud noise, creating a brief but intense thunderclap that can be heard up to 300 feet away. Creatures within 30 feet of you must make a Constitution saving throw or be stunned until the end of your next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_wind_barrier",
    name: "Wind Barrier",
    description: "As a reaction to being targeted by an attack or harmful spell, you can summon a barrier of wind around you. You gain a +2 bonus to AC and saving throws until the start of your next turn. Additionally, attacks against you have disadvantage.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_whispering_winds",
    name: "Whispering Winds",
    description: "You can use your action to send a message carried by the wind to any creature within 1 mile of you. The message is heard as a whisper by the intended recipient. This ability allows for secret communications or covert information exchange.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_sound_analysis",
    name: "Sound Analysis",
    description: "You can accurately determine the source and direction of any sound within 300 feet of you. This ability can be used to track creatures or detect hidden enemies. It provides you advantage on Wisdom (Perception) checks related to sound.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_initiate_whispers_of_the_gale",
    name: "Whispers of the Gale (Laura)",
    description: "When you miss with a ranged attack roll (including spell attacks), you can use your reaction and expend a spell slot of 1st level or higher to reroll the attack. You must use the new roll, and the spell slot is expended regardless of the outcome.\n\n---\n## Adept Tier",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Faelara Rest of the Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_wind_sprint",
    name: "Wind Sprint",
    description: "You can double your movement speed for a number of rounds equal to your proficiency bonus.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_master_essence_just_passing_by",
    name: "Just Passing By",
    description: "As a reaction, you dissolve into wind until the start of your next turn, passing through solid objects, becoming immune to nonmagical slashing, piercing, and bludgeoning damage and resistant to magical slashing, piercing, and bludgeoning damage.\n\n---\n\n## Spells restored from V1",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Wang Tianbao (Shadow Sect)",
    location: "Sirius",
  }
];

export const skyCantrips = [
  {
    id: "tempest_cantrip_shocking_grasp",
    name: "Shocking Grasp",
    description: "Lightning springs from your hand to deliver a shock, dealing 1d8 lightning damage and preventing reactions.\n\nhttps://5e.tools/spells.html#shocking%20grasp_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Evocation / Tempest",
  },
  {
    id: "tempest_cantrip_gust",
    name: "Gust",
    description: "Seize air to push creatures 5 feet away or blow objects violently.\n\nhttps://5e.tools/spells.html#gust_xge\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Transmutation / Wind",
  },
  {
    id: "v2_sky_message",
    name: "Message",
    description: "You whisper a short message that travels to a creature at a distance.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#message_phb).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB)",
  },
  {
    id: "tempest_cantrip_thunderclap",
    name: "Thunderclap",
    description: "Create a burst of thunderous sound heard up to 100 feet away, dealing 1d6 thunder damage to all adjacent creatures.\n\nhttps://5e.tools/spells.html#thunderclap_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Evocation",
  }
];

export const skySpells = [
  {
    id: "tempest_3rd_lightning_bolt",
    name: "Lightning Bolt",
    description: "A 100-foot-long, 5-foot-wide stroke of lightning deals 8d6 lightning damage to all creatures in the line.\n\nhttps://5e.tools/spells.html#lightning%20bolt_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Lightning",
  },
  {
    id: "v2_lightning_witch_bolt",
    name: "Witch Bolt",
    description: "A crackling arc links you to one target, dealing lightning damage while you sustain the connection.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#witch%20bolt_phb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_lightning_chain_lightning",
    name: "Chain Lightning",
    description: "A powerful bolt leaps from one target to additional creatures within reach.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#chain%20lightning_phb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "tempest_5th_control_winds",
    name: "Control Winds",
    description: "Take command of the wind in a 100-foot cube: gusts, downdrafts, or updrafts that redirect missiles and topple fliers.\n\nhttps://5e.tools/spells.html#control%20winds_xge",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Transmutation",
  },
  {
    id: "wind_1st_level_feather_fall",
    name: "Feather Fall",
    description: "https://5e.tools/spells.html#feather%20fall_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_fly",
    name: "Fly",
    description: "https://5e.tools/spells.html#fly_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_wind_wall",
    name: "Wind Wall",
    description: "https://5e.tools/spells.html#wind%20wall_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_6th_level_wind_walk",
    name: "Wind Walk",
    description: "https://5e.tools/spells.html#wind%20walk_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "v2_metal_shatter",
    name: "Shatter",
    description: "A sudden resonant burst damages creatures and objects in an area.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#shatter_phb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "tempest_1st_thunderwave",
    name: "Thunderwave",
    description: "A wave of thunderous force deals 2d8 thunder damage and pushes creatures 10 feet away.\n\nhttps://5e.tools/spells.html#thunderwave_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Evocation",
  },
  {
    id: "wind_1st_level_jump",
    name: "Jump",
    description: "A touched creature can jump up to 30 feet by spending 10 feet of movement.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#jump_xphb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wind_1st_level_warding_wind",
    name: "Warding Wind",
    description: "A 10-foot wall of strong wind surrounds you, deafening, snuffing small flames, and giving ranged attacks disadvantage.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#warding%20wind_xge).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "wind_2nd_level_air_bubble",
    name: "Air Bubble",
    description: "A globe of fresh air surrounds a creature's head so it can breathe underwater or in a vacuum.\n\nSource reference: [D&D 5e (AAG) on 5e.tools](https://5e.tools/spells.html#air%20bubble_aag).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (AAG)",
  },
  {
    id: "wind_2nd_level_dust_devil",
    name: "Dust Devil",
    description: "A small whirlwind batters and pushes nearby creatures; you can move it and let it pick up debris to obscure the area.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#dust%20devil_xge).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "wind_2nd_level_gust_of_wind",
    name: "Gust of Wind",
    description: "A 60-foot line of strong wind pushes creatures back, halves movement toward you, and disperses gas.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#gust%20of%20wind_xphb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wind_2nd_level_misty_step",
    name: "Misty Step",
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#misty%20step_xphb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wind_3rd_level_cacophonic_shield",
    name: "Cacophonic Shield",
    description: "A 10-foot aura of thunder deals 3d6 thunder damage and deafens creatures that enter it or end their turn there.\n\nSource reference: [D&D 5e (Heroes of Faerûn) on 5e.tools](https://5e.tools/spells.html#cacophonic%20shield_frhof).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Heroes of Faerûn)",
  },
  {
    id: "wind_3rd_level_freedom_of_the_winds",
    name: "Freedom of the Winds",
    description: "Wind lifts you to a 60-foot flying speed, helps you slip grapples and restraints, and lets you teleport away from attacks.\n\nSource reference: [Tal'Dorei Campaign Setting Reborn on 5e.tools](https://5e.tools/spells.html#freedom%20of%20the%20winds_taldoreicampaignsettingreborn).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Tal'Dorei Campaign Setting Reborn",
  },
  {
    id: "wind_3rd_level_gaseous_form",
    name: "Gaseous Form",
    description: "A willing creature becomes a slow-flying misty cloud that can slip through small openings and resists damage.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#gaseous%20form_xphb).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wind_5th_level_mass_levitate",
    name: "Mass Levitate",
    description: "Up to six creatures or objects rise 20 feet and hang suspended, able to move only by pushing off surfaces.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#mass%20levitate_obojimatallgrass).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "wind_6th_level_investiture_of_wind",
    name: "Investiture of Wind",
    description: "Wind whirls around you: ranged attacks against you have disadvantage, you fly at 60 feet, and you can hurl cubes of wind.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#investiture%20of%20wind_xge).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "v2_sky_aura_of_evasion",
    name: "Aura of Evasion",
    description: "A 30-foot aura of alacrity gives you and your allies advantage on Dexterity saves and lets them take no damage on a successful save.\n\nSource reference: [D&D 5e (Arcana Unleashed) on 5e.tools](https://5e.tools/spells.html#aura%20of%20evasion_au).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Arcana Unleashed)",
  },
  {
    id: "v2_sky_lightning_ring",
    name: "Lightning Ring",
    description: "A 10-foot ring of crackling electricity moves with you, shocking creatures it touches with lightning and thunder damage.\n\nSource reference: [D&D 5e (Arcana Unleashed) on 5e.tools](https://5e.tools/spells.html#lightning%20ring_au).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Arcana Unleashed)",
  },
  {
    id: "v2_sky_heavenstorm",
    name: "Heavenstorm",
    description: "A primordial bolt of lightning strikes a foe for massive lightning and thunder damage, then chains through up to nine more creatures.\n\nSource reference: [Fragments of the Forbidden Tome on 5e.tools](https://5e.tools/spells.html#heavenstorm_fftforbiddentome).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Fragments of the Forbidden Tome",
  },
  {
    id: "v2_sky_wind_wake",
    name: "Wind Wake",
    description: "A hurricane-force wind follows you in a 200-foot cube, grounding fliers, deflecting ranged attacks, and pushing everything away from you.\n\nSource reference: [The Elements and Beyond on 5e.tools](https://5e.tools/spells.html#wind%20wake_teb).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "The Elements and Beyond",
  },
  {
    id: "v2_sky_hurricane",
    name: "Hurricane",
    description: "A hurricane lifts you into its flying eye, pulling nearby creatures up into the storm and hurling them away.\n\nSource reference: [The Harbinger on 5e.tools](https://5e.tools/spells.html#hurricane_theharbinger).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "The Harbinger",
  },
  {
    id: "v2_sky_arcanomagnetic_storm",
    name: "Arcanomagnetic Storm",
    description: "A reshapeable storm of lightning and magnetic winds shocks creatures inside and knocks them prone, dragging hardest at those wearing iron.\n\nSource reference: [Heliana's Guide to Monster Hunting on 5e.tools](https://5e.tools/spells.html#arcanomagnetic%20storm_helianasguidetomonsterhunting).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Heliana's Guide to Monster Hunting",
  },
  {
    id: "v2_sky_roaring_winds_of_limbo",
    name: "Roaring Winds of Limbo",
    description: "A breach to the planes of chaos unleashes a windstorm that deafens, blinds with debris, and hurls creatures in random directions.\n\nSource reference: [Kobold Press Deep Magic on 5e.tools](https://5e.tools/spells.html#roaring%20winds%20of%20limbo_kpdm).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Kobold Press Deep Magic",
  }
];
