export const skyAbilities = [
  {
    id: "wind_initiate_thunderous_roar",
    name: "Thunderous Roar",
    description: "You can let out a powerful roar that creates a shockwave, forcing all creatures within 10 feet to make a Constitution saving throw or be pushed 10 feet away from you and become deafened for 1 minute.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_initiate_static_reflexes",
    name: "Static Reflexes",
    description: "You gain advantage on Dexterity saving throws against effects that deal lightning damage or require quick reflexes, such as traps or spells.\n\n## Adept Tier",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_adept_lightning_javelin",
    name: "Lightning Javelin",
    description: "You hurl a javelin of pure lightning at a target within 60 feet. Make a ranged spell attack:\n- **On a hit:** The target takes 5d12 lightning damage and cannot take reactions until the start of its next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_essence_arc_chain",
    name: "Arc Chain",
    description: "Choose a creature within 120 feet. The target must make a Dexterity saving throw, taking 3d8 lightning damage on a failed save, or half as much on a successful one.\n\nIf the target fails its saving throw, the arc leaps to another creature within 30 feet of it that hasn’t been struck yet, forcing the same saving throw. The chain continues jumping to new creatures until a target succeeds on its save or no valid targets remain within range.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Nethan (Nilo's Father)",
    location: "Leatrux",
  },
  {
    id: "lightning_adept_conductive_touch",
    name: "Conductive Touch",
    description: "When you hit a creature with a melee attack, you can choose to deal an extra 2d12 lightning damage.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_initiate_lightning_step",
    name: "Lightning Step",
    description: "As a bonus action, you can harness the power of lightning to enhance your movement. Your jump distance is tripled, and your movement does not provoke opportunity attacks until the end of your turn.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_adept_lightning_sense",
    name: "Lightning Sense",
    description: "You have developed a heightened sense of awareness in stormy or electrically charged environments. You gain advantage on Wisdom (Perception) checks to notice hidden details or track creatures in such conditions.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_essence_lightning_cage",
    name: "Lightning Cage",
    description: "You conjure a crackling triangular cage of lightning in a 30-foot area centered on a point within 90 feet, lasting for 1 minute:\n- Creatures inside have their speed halved and cannot take reactions.\n- Any creature that touches or attempts to pass through the cage's perimeter takes 4d10 lightning damage.\n- A creature trapped inside can use an action to make a Strength saving throw to break through: on a failed save, it remains trapped and takes 4d10 lightning damage; on a successful save, it escapes and takes half damage.\n\n## Spells",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Nethan (Nilo's Father)",
    location: "Leatrux",
  },
  {
    id: "wind_adept_calm_breeze",
    name: "Calm Breeze",
    description: "You can use a bonus action to create a soothing breeze that relaxes and calms creatures within a 30-foot radius, providing them with advantage on saving throws against being frightened or charmed. This effect lasts for 10 minutes.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_thunderstep",
    name: "Thunderstep",
    description: "You can use an action to make a sudden, loud noise, creating a brief but intense thunderclap that can be heard up to 300 feet away. Creatures within 30 feet of you must make a Constitution saving throw or be stunned until the end of your next turn.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_wind_barrier",
    name: "Wind Barrier",
    description: "As a reaction to being targeted by an attack or harmful spell, you can summon a barrier of wind around you. You gain a +2 bonus to AC and saving throws until the start of your next turn. Additionally, attacks against you have disadvantage.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_whispering_winds",
    name: "Whispering Winds",
    description: "You can use your action to send a message carried by the wind to any creature within 1 mile of you. The message is heard as a whisper by the intended recipient. This ability allows for secret communications or covert information exchange.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_sound_analysis",
    name: "Sound Analysis",
    description: "You can accurately determine the source and direction of any sound within 300 feet of you. This ability can be used to track creatures or detect hidden enemies. It provides you advantage on Wisdom (Perception) checks related to sound.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  }
];

export const skyCantrips = [
  {
    id: "tempest_cantrip_shocking_grasp",
    name: "Shocking Grasp",
    description: "Lightning springs from your hand to deliver a shock, dealing 1d8 lightning damage and preventing reactions.\n\nhttps://5e.tools/spells.html#shocking%20grasp_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Evocation / Tempest",
  },
  {
    id: "v2_lightning_lightning_lure",
    name: "Lightning Lure",
    description: "A lash of lightning pulls a nearby creature toward you and shocks it if it comes close.\n\nSource reference: [D&D 5e TCE on 5e.tools](https://5e.tools/spells.html#lightning%20lure_tce).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (TCE)",
  },
  {
    id: "tempest_cantrip_gust",
    name: "Gust",
    description: "Seize air to push creatures 5 feet away or blow objects violently.\n\nhttps://5e.tools/spells.html#gust_xphb\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Transmutation / Wind",
  },
  {
    id: "v2_sky_message",
    name: "Message",
    description: "You whisper a short message that travels to a creature at a distance.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#message_phb).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB)",
  }
];

export const skySpells = [
  {
    id: "tempest_3rd_lightning_bolt",
    name: "Lightning Bolt",
    description: "A 100-foot-long, 5-foot-wide stroke of lightning deals 8d6 lightning damage to all creatures in the line.\n\nhttps://5e.tools/spells.html#lightning%20bolt_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Lightning",
  },
  {
    id: "v2_lightning_witch_bolt",
    name: "Witch Bolt",
    description: "A crackling arc links you to one target, dealing lightning damage while you sustain the connection.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#witch%20bolt_phb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_lightning_chain_lightning",
    name: "Chain Lightning",
    description: "A powerful bolt leaps from one target to additional creatures within reach.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#chain%20lightning_phb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "tempest_5th_control_winds",
    name: "Control Winds",
    description: "Take command of the wind in a 100-foot cube: gusts, downdrafts, or updrafts that redirect missiles and topple fliers.\n\nhttps://5e.tools/spells.html#control%20winds_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Transmutation",
  },
  {
    id: "wind_1st_level_feather_fall",
    name: "Feather Fall",
    description: "https://5e.tools/spells.html#feather%20fall_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_fly",
    name: "Fly",
    description: "https://5e.tools/spells.html#fly_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_3rd_level_wind_wall",
    name: "Wind Wall",
    description: "https://5e.tools/spells.html#wind%20wall_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wind_6th_level_wind_walk",
    name: "Wind Walk",
    description: "https://5e.tools/spells.html#wind%20walk_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  }
];
