export const tempestAbilities = [
  {
    id: "lightning_initiate_stormborn_presence",
    name: "Stormborn Presence",
    description: "When you make a Charisma (Persuasion) or Charisma (Intimidation) check to influence a group of people, you can invoke your stormy presence to gain advantage on the roll.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_initiate_storm_navigator",
    name: "Storm Navigator",
    description: "Your understanding of storms helps you predict their patterns and avoid hazards. You gain proficiency in Navigator’s Tools and have advantage on Wisdom (Survival) checks made to navigate or map out sea routes in stormy weather.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_initiate_raincaller",
    name: "Raincaller",
    description: "You can call forth a light rain within a 30-foot radius centered on you for 10 minutes. This rain lightly obscures the area, granting disadvantage on Perception checks relying on sight and extinguishing fires.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_initiate_lightning_insight",
    name: "Lightning Insight",
    description: "When on or near water, you can use your connection to lightning to sense changes in weather. You can use a bonus action to gain advantage on Wisdom (Perception) checks to spot distant ships, landmarks, or other navigation hazards.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_adept_thunderous_entrance",
    name: "Thunderous Entrance",
    description: "You can make a dramatic entrance by creating a booming thunderclap that announces your presence. This effect grants you expertise on Charisma (Performance) checks to make a memorable first impression.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_adept_thunderous_strike",
    name: "Thunderous Strike",
    description: "When you hit a creature with a melee weapon attack, you can channel the force of a thunderstorm into your strike. The target must succeed on a Constitution saving throw or be stunned until the end of your next turn. This ability can only be used once per turn, and once a creature is stunned by this ability, it cannot be stunned again by it for 1 minute.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_essence_extinguishing_lightning",
    name: "Extinguishing Lightning",
    description: "As an action, unleash consuming black lightning in a 60-foot cone. Each creature in the area must make a Dexterity saving throw, taking 6d12 lightning damage on a failed save, or half as much on a successful one.\n\nOn a failed save, one ongoing magical effect or spell on the creature immediately ends (your choice).",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Nethan (Nilo's Father)",
    location: "Leatrux",
  }
];

export const tempestCantrips = [
  {
    id: "v2_lightning_lightning_lure",
    name: "Lightning Lure",
    description: "A lash of lightning pulls a nearby creature toward you and shocks it if it comes close.\n\nSource reference: [D&D 5e TCE on 5e.tools](https://5e.tools/spells.html#lightning%20lure_tce).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (TCE)",
  }
];

export const tempestSpells = [
  {
    id: "tempest_1st_fog_cloud",
    name: "Fog Cloud",
    description: "You create a 20-foot-radius sphere of dense sea fog heavily obscuring the area.\n\nhttps://5e.tools/spells.html#fog%20cloud_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Conjuration",
  },
  {
    id: "tempest_7th_whirlwind",
    name: "Whirlwind",
    description: "A howling cyclone 10 feet wide and 30 feet tall sweeps across the field, sucking up creatures, hurling them, and dealing 10d6 bludgeoning damage.\n\nhttps://5e.tools/spells.html#whirlwind_xge",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Hurricane",
  },
  {
    id: "tempest_5th_destructive_wave",
    name: "Destructive Wave",
    description: "Strike the ground to unleash thunder and radiant/necrotic storm energy: 5d6 thunder + 5d6 damage, knocking enemies prone.\n\nhttps://5e.tools/spells.html#destructive%20wave_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Paladin",
  },
  {
    id: "tempest_9th_storm_of_vengeance",
    name: "Storm of Vengeance",
    description: "A churning storm cloud forms in a 360-foot radius, unleashing lightning bolts, acidic rain, hail, and howling hurricane winds.\n\nhttps://5e.tools/spells.html#storm%20of%20vengeance_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Conjuration",
  },
  {
    id: "tempest_3rd_call_lightning",
    name: "Call Lightning",
    description: "Storm cloud forms overhead; each round call down lightning bolts dealing 3d10 (or 4d10 in stormy weather) lightning damage.\n\nhttps://5e.tools/spells.html#call%20lightning_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Conjuration",
  },
  {
    id: "tempest_3rd_sleet_storm",
    name: "Sleet Storm",
    description: "Freezing rain and sleet create a 40-foot-radius squall: difficult terrain, extinguishes fires, and forces Dexterity saves to avoid falling prone.\n\nhttps://5e.tools/spells.html#sleet%20storm_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Conjuration",
  },
  {
    id: "tempest_3rd_tidal_wave",
    name: "Tidal Wave",
    description: "A crashing wave of seawater 30 ft long and 10 ft wide knocks creatures prone and deals 4d8 bludgeoning damage.\n\nhttps://5e.tools/spells.html#tidal%20wave_xge",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Conjuration",
  },
  {
    id: "tempest_4th_storm_sphere",
    name: "Storm Sphere",
    description: "A 20-foot-radius sphere of gale winds hampers movement, and as a bonus action each round zap a target for 4d6 lightning damage.\n\nhttps://5e.tools/spells.html#storm%20sphere_xge",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Tempest",
  },
  {
    id: "tempest_5th_maelstrom",
    name: "Maelstrom",
    description: "A 30-foot-radius swirling vortex of water drags creatures toward its center and deals 6d6 bludgeoning damage.\n\nhttps://5e.tools/spells.html#maelstrom_xge",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Umberlee",
  },
  {
    id: "tempest_8th_control_weather",
    name: "Control Weather",
    description: "Seize command of precipitation, temperature, and wind across a 5-mile radius, summoning hurricanes or calm skies.\n\nhttps://5e.tools/spells.html#control%20weather_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Transmutation",
  },
  {
    id: "tempest_8th_tsunami",
    name: "Tsunami",
    description: "A colossal wall of water up to 300 feet long, 300 feet high, and 50 feet thick crashes across the landscape, crushing everything in its path.\n\nhttps://5e.tools/spells.html#tsunami_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Conjuration",
  },
  {
    id: "v2_tempest_thunderous_smite",
    name: "Thunderous Smite",
    description: "Your next melee hit releases a concussive thunderclap that can drive the target back.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#thunderous%20smite_phb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_tempest_ice_storm",
    name: "Ice Storm",
    description: "Hail and freezing rain batter an area, turning the ground slick and difficult to cross.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#ice%20storm_phb).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "lightning_3rd_level_lightning_arrow",
    name: "Lightning Arrow",
    description: "Your next ranged weapon attack becomes a bolt of lightning that deals 4d8 lightning damage and bursts onto nearby creatures.\n\nSource reference: [D&D 5e (PHB) on 5e.tools](https://5e.tools/spells.html#lightning%20arrow_phb).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "lightning_5th_level_ride_the_lightning",
    name: "Ride the Lightning",
    description: "You become a bolt of lightning, damaging creatures along a 60-foot line before reappearing at its end.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#ride%20the%20lightning_grimhollowpg24).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "v2_tempest_red_rain",
    name: "Red Rain",
    description: "Blood rain falls within 5 miles, withering plants, frightening beasts, and draining exposed creatures with exhaustion and necrotic damage.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#red%20rain_grimhollowpg24).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "v2_tempest_beast_of_ragnarok",
    name: "Beast of Ragnarok",
    description: "Fenris’s aura darkens the sky with snow for a mile around you; you gain advantage on d20 tests and immunity to all damage but one random type.\n\nSource reference: [Kobold Press Northlands Worldbook on 5e.tools](https://5e.tools/spells.html#beast%20of%20ragnarok_northlandsworldbook).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Kobold Press Northlands Worldbook",
  }
];
