export const tempestAbilities = [
  {
    id: "lightning_initiate_stormborn_presence",
    name: "Stormborn Presence",
    description: "When you make a Charisma (Persuasion) or Charisma (Intimidation) check to influence a group of people, you can invoke your stormy presence to gain advantage on the roll.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "lightning_initiate_storm_navigator",
    name: "Storm Navigator",
    description: "Your understanding of storms helps you predict their patterns and avoid hazards. You gain proficiency in Navigator’s Tools and have advantage on Wisdom (Survival) checks made to navigate or map out sea routes in stormy weather.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lei Zhen",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_initiate_raincaller",
    name: "Raincaller",
    description: "You can call forth a light rain within a 30-foot radius centered on you for 10 minutes. This rain lightly obscures the area, granting disadvantage on Perception checks relying on sight and extinguishing fires.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  }
];

export const tempestCantrips = [
  {
    id: "tempest_cantrip_thunderclap",
    name: "Thunderclap",
    description: "Create a burst of thunderous sound heard up to 100 feet away, dealing 1d6 thunder damage to all adjacent creatures.\n\nhttps://5e.tools/spells.html#thunderclap_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "Cleric / Evocation",
  }
];

export const tempestSpells = [
  {
    id: "tempest_1st_fog_cloud",
    name: "Fog Cloud",
    description: "You create a 20-foot-radius sphere of dense sea fog heavily obscuring the area.\n\nhttps://5e.tools/spells.html#fog%20cloud_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Conjuration",
  },
  {
    id: "tempest_7th_whirlwind",
    name: "Whirlwind",
    description: "A howling cyclone 10 feet wide and 30 feet tall sweeps across the field, sucking up creatures, hurling them, and dealing 10d6 bludgeoning damage.\n\nhttps://5e.tools/spells.html#whirlwind_xphb",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Hurricane",
  },
  {
    id: "tempest_5th_destructive_wave",
    name: "Destructive Wave",
    description: "Strike the ground to unleash thunder and radiant/necrotic storm energy: 5d6 thunder + 5d6 damage, knocking enemies prone.\n\nhttps://5e.tools/spells.html#destructive%20wave_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Paladin",
  },
  {
    id: "tempest_9th_storm_of_vengeance",
    name: "Storm of Vengeance",
    description: "A churning storm cloud forms in a 360-foot radius, unleashing lightning bolts, acidic rain, hail, and howling hurricane winds.\n\nhttps://5e.tools/spells.html#storm%20of%20vengeance_xphb",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Conjuration",
  },
  {
    id: "tempest_1st_thunderwave",
    name: "Thunderwave",
    description: "A wave of thunderous force deals 2d8 thunder damage and pushes creatures 10 feet away.\n\nhttps://5e.tools/spells.html#thunderwave_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Evocation",
  },
  {
    id: "tempest_3rd_call_lightning",
    name: "Call Lightning",
    description: "Storm cloud forms overhead; each round call down lightning bolts dealing 3d10 (or 4d10 in stormy weather) lightning damage.\n\nhttps://5e.tools/spells.html#call%20lightning_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Conjuration",
  },
  {
    id: "tempest_3rd_sleet_storm",
    name: "Sleet Storm",
    description: "Freezing rain and sleet create a 40-foot-radius squall: difficult terrain, extinguishes fires, and forces Dexterity saves to avoid falling prone.\n\nhttps://5e.tools/spells.html#sleet%20storm_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Conjuration",
  },
  {
    id: "tempest_3rd_tidal_wave",
    name: "Tidal Wave",
    description: "A crashing wave of seawater 30 ft long and 10 ft wide knocks creatures prone and deals 4d8 bludgeoning damage.\n\nhttps://5e.tools/spells.html#tidal%20wave_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Conjuration",
  },
  {
    id: "tempest_4th_storm_sphere",
    name: "Storm Sphere",
    description: "A 20-foot-radius sphere of gale winds hampers movement, and as a bonus action each round zap a target for 4d6 lightning damage.\n\nhttps://5e.tools/spells.html#storm%20sphere_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Tempest",
  },
  {
    id: "tempest_5th_maelstrom",
    name: "Maelstrom",
    description: "A 30-foot-radius swirling vortex of water drags creatures toward its center and deals 6d6 bludgeoning damage.\n\nhttps://5e.tools/spells.html#maelstrom_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Umberlee",
  },
  {
    id: "tempest_8th_control_weather",
    name: "Control Weather",
    description: "Seize command of precipitation, temperature, and wind across a 5-mile radius, summoning hurricanes or calm skies.\n\nhttps://5e.tools/spells.html#control%20weather_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric (Tempest Domain) / Transmutation",
  },
  {
    id: "tempest_8th_tsunami",
    name: "Tsunami",
    description: "A colossal wall of water up to 300 feet long, 300 feet high, and 50 feet thick crashes across the landscape, crushing everything in its path.\n\nhttps://5e.tools/spells.html#tsunami_xphb",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Cleric / Conjuration",
  },
  {
    id: "v2_tempest_thunderous_smite",
    name: "Thunderous Smite",
    description: "Your next melee hit releases a concussive thunderclap that can drive the target back.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#thunderous%20smite_phb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  },
  {
    id: "v2_tempest_ice_storm",
    name: "Ice Storm",
    description: "Hail and freezing rain batter an area, turning the ground slick and difficult to cross.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#ice%20storm_phb).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  }
];
