export const waterAbilities = [
  {
    id: "water_initiate_echoes_of_the_deep",
    name: "Echoes of the Deep",
    description: "You can communicate with aquatic creatures or spirits of water, allowing you to understand their language and gain information about underwater locations or hidden treasures.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_initiate_ice_form",
    name: "Ice Form",
    description: "As a bonus action, you can turn your body into ice for 1 minute. You gain resistance to cold and fire damage and your movement speed is reduced by 10 feet.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_tides_reflection_art_i",
    name: "Tide's Reflection Art I (Thalassios)",
    description: "As a bonus action, you summon a Water Clone in an unoccupied space you can see within 30 feet. The clone lasts for 1 minute or until destroyed. The clone is linked to your senses, allowing you to cast spells through it as if you were in its space.\n\n**Clone Statistics:**\n- **Armor Class:** Your spell save DC (8 + proficiency bonus + spellcasting modifier)\n- **Hit Points:** Equal to half your hit point maximum\n- **Speed:** Equal to your swimming speed\n- **Damage Resistances:** Fire\n- **Damage Immunities:** Cold\n- **Damage Vulnerabilities:** Lightning\n\n**Commanding the Clone:**\nAs a bonus action, you can command the clone to move and take one of the following actions:\n- **Melee Spell Attack:** Reach 10 ft., dealing 1d8 + your spellcasting modifier cold damage.\n- **Ranged Spell Attack:** Range 60 ft., dealing 1d6 + your spellcasting modifier cold damage.\n- **Utility:** Take the Dash, Dodge, or Disengage action.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Selûne",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_initiate_restorative_rain",
    name: "Restorative Rain",
    description: "As an action, you create a 20-foot radius of gentle rain centered on you that lasts for a number of rounds equal to your maximum Water essences. At the start of each of their turns while in the rain, they regain 1 hit point.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_aqua_agility",
    name: "Aqua Agility",
    description: "Your swimming speed equals your walking speed. Additionally, you gain the ability to breathe underwater and move through water at your normal speed without penalty.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_tidal_surge",
    name: "Tidal Surge",
    description: "You can summon a powerful wave of water that heals and revitalizes. As an action, you create a wave that washes over allies in a 30-foot radius, restoring hit points equal to 3d8 + your spellcasting ability modifier.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_glacial_shield",
    name: "Glacial Shield",
    description: "As a reaction, you can spend one spell slot and encase yourself in a barrier of ice, granting you temporary hit points equal to ten times the spell level used plus your spell casting modifier. This lasts for 1 hour.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_hydroportation",
    name: "Hydroportation",
    description: "As a bonus action, you can teleport up to 60 feet to a space you can see within a body of water or mist. You must be in contact with the water or mist to use this ability.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_misty_escape",
    name: "Misty Escape",
    description: "When you take damage, you can use your reaction to turn into a cloud of mist, causing the attack to miss. You must spend a spell slot of 1st level or higher to use this ability.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_tides_reflection_art_ii",
    name: "Tide's Reflection Art II (Thalassios)",
    description: "As a reaction, you can spend 2 Essence to cause one of your Water Clones to detonate in a 10-foot radius burst of frigid water. Each creature in range must make a Dexterity saving throw, taking cold damage equal to half the clone's maximum hit points on a failed save, or half as much on a successful one.\n\nIn addition, you can now summon up to two Water Clones simultaneously. When they attack together, their attack damage increases by one damage die.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Selûne",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_master_aura_of_the_deep_bulwark",
    name: "Aura of the Deep Bulwark",
    description: "As an action, you radiate a massive, pressurized sphere of dampening aqueous vapor extending from you in a 120-foot radius for 1 minute.\n\nWhile inside this aura, you and friendly creatures gain resistance to fire damage and force damage. In addition, affected creatures have advantage on saving throws against spells, traps, munitions, and hazards that produce an explosion or concussive blast (such as *Fireball*, *Shatter*, explosive barrels, or demolition charges).",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Kwon Jae-Hwan",
    location: "Sirius",
  },
  {
    id: "water_adept_tides_reflection_art_iii",
    name: "Tide's Reflection Art III (Thalassios)",
    description: "As a bonus action, you can instantly swap places with one of your Water Clones without provoking opportunity attacks.\n\nIn addition, your mastery deepens:\n- You can now summon up to three Water Clones simultaneously.\n- Your Water Clones last for 10 minutes.\n- Your Water Clones emit dim moonlight in a 60-foot radius around them.",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Selûne",
    location: "Phudara / Isle of Whispers",
  }
];

export const waterCantrips = [
  {
    id: "water_cantrip_frostbite",
    name: "Frostbite",
    description: "https://5e.tools/spells.html#frostbite_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "water_cantrip_ray_of_frost",
    name: "Ray of Frost",
    description: "https://5e.tools/spells.html#ray%20of%20frost_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "water_cantrip_shape_water",
    name: "Shape Water",
    description: "https://5e.tools/spells.html#shape%20water_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const waterSpells = [
  {
    id: "water_1st_level_create_or_destroy_water",
    name: "Create or Destroy Water",
    description: "https://5e.tools/spells.html#create%20or%20destroy%20water_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_2nd_level_rimes_binding_ice",
    name: "Rime's Binding Ice",
    description: "https://5e.tools/spells.html#rime's%20binding%20ice_ftd",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_water_walk",
    name: "Water Walk",
    description: "https://5e.tools/spells.html#water%20walk_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_4th_level_control_water",
    name: "Control Water",
    description: "https://5e.tools/spells.html#control%20water_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "tempest_5th_cone_of_cold",
    name: "Cone of Cold",
    description: "A 60-foot cone of subzero sea squall blasts creatures for 8d8 cold damage, freezing corpses into statues.\n\nhttps://5e.tools/spells.html#cone%20of%20cold_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Glacial Squall",
  },
  {
    id: "water_3rd_level_wall_of_water",
    name: "Wall of Water",
    description: "https://5e.tools/spells.html#wall%20of%20water_xge",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_water_breathing",
    name: "Water Breathing",
    description: "https://5e.tools/spells.html#water%20breathing_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_conjure_ocean",
    name: "Conjure Ocean",
    description: "https://5e.tools/spells.html#conjure%20ocean_obojimatallgrass",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_1st_level_bubble_lift",
    name: "Bubble Lift",
    description: "You blow a bubble around an object of up to 500 pounds, making it float 4 feet off the ground and easy to push.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#bubble%20lift_obojimatallgrass).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "water_1st_level_frost_fingers",
    name: "Frost Fingers",
    description: "Freezing cold sprays from your fingertips in a 15-foot cone, dealing cold damage and freezing water in the area.\n\nSource reference: [D&D 5e (IDRotF) on 5e.tools](https://5e.tools/spells.html#frost%20fingers_idrotf).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (IDRotF)",
  },
  {
    id: "water_1st_level_ice_knife",
    name: "Ice Knife",
    description: "A shard of ice pierces one target, then explodes, dealing cold damage to creatures around it.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#ice%20knife_xge).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "water_1st_level_water_bullet",
    name: "Water Bullet",
    description: "A spinning sphere of water deals bludgeoning damage that is highest at close range.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#water%20bullet_obojimatallgrass).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "water_1st_level_whelm_weapon",
    name: "Whelm Weapon",
    description: "Water envelops up to three weapons, reducing all damage they deal by a d4 for the duration.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#whelm%20weapon_obojimatallgrass).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "water_2nd_level_snillocs_snowball_swarm",
    name: "Snilloc's Snowball Swarm",
    description: "A flurry of magic snowballs bursts in a 5-foot radius, dealing 3d6 cold damage.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#snilloc's%20snowball%20swarm_xge).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "water_3rd_level_freedom_of_the_waves",
    name: "Freedom of the Waves",
    description: "A deluge of seawater batters and knocks creatures prone in a 15-foot cylinder while sparing chosen allies.\n\nSource reference: [Tal'Dorei Campaign Setting Reborn on 5e.tools](https://5e.tools/spells.html#freedom%20of%20the%20waves_taldoreicampaignsettingreborn).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Tal'Dorei Campaign Setting Reborn",
  },
  {
    id: "water_4th_level_watery_sphere",
    name: "Watery Sphere",
    description: "A hovering sphere of water engulfs and restrains creatures, and you can roll it to sweep up more.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#watery%20sphere_xge).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "water_6th_level_crustacean_form",
    name: "Crustacean Form",
    description: "An ethereal crustacean shell sets your AC to 20 and grants swimming, blindsight, and claw attacks.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#crustacean%20form_obojimatallgrass).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "water_6th_level_investiture_of_ice",
    name: "Investiture of Ice",
    description: "Ice rimes your body: immunity to cold, icy ground around you, and a freezing cone you can unleash as an action.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#investiture%20of%20ice_xge).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "wind_6th_level_otilukes_freezing_sphere",
    name: "Otiluke's Freezing Sphere",
    description: "A frigid globe explodes in a 60-foot radius for 10d6 cold damage and freezes water; you can hold it as a grenade.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#otiluke's%20freezing%20sphere_xphb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "water_6th_level_wall_of_ice",
    name: "Wall of Ice",
    description: "You shape a wall or dome of ice that damages creatures it appears around and leaves a frigid sheet when broken.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#wall%20of%20ice_xphb).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_water_ice_soldiers",
    name: "Ice Soldiers",
    description: "Water poured from a vial forms two ice soldiers that obey your mental commands, each hunting its chosen foe until it dies, then melting away.\n\nSource reference: [Kobold Press Deep Magic on 5e.tools](https://5e.tools/spells.html#ice%20soldiers_kpdm).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Kobold Press Deep Magic",
  },
  {
    id: "v2_water_triumph_of_ice",
    name: "Triumph of Ice",
    description: "You turn one element to ice or snow in a 100-foot sphere: air becomes snowfall, earth becomes permafrost, fire becomes ice shards, or water freezes solid.\n\nSource reference: [Kobold Press Deep Magic on 5e.tools](https://5e.tools/spells.html#triumph%20of%20ice_kpdm).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Kobold Press Deep Magic",
  },
  {
    id: "v2_water_glacial_cascade",
    name: "Glacial Cascade",
    description: "Pure cold fills a 30-foot sphere around you for 10d8 cold damage; a creature killed by it turns to ice.\n\nSource reference: [Kobold Press Deep Magic on 5e.tools](https://5e.tools/spells.html#glacial%20cascade_kpdm).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Kobold Press Deep Magic",
  },
  {
    id: "v2_water_great_wave",
    name: "Great Wave",
    description: "A wall of water up to 300 feet long and high rolls across the battlefield, battering and carrying away the creatures in its path.\n\nSource reference: [Spells That Don't Suck on 5e.tools](https://5e.tools/spells.html#great%20wave_spellsthatdontsuck).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Spells That Don't Suck",
  },
  {
    id: "v2_water_grand_flood",
    name: "Grand Flood",
    description: "Water rises from the lowest ground around you, flooding the land 20 feet each round until it has dropped the equivalent of 20 feet of rain.\n\nSource reference: [The Elements and Beyond on 5e.tools](https://5e.tools/spells.html#grand%20flood_teb).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "The Elements and Beyond",
  },
  {
    id: "v2_water_glacial_tide",
    name: "Glacial Tide",
    description: "A 500-foot wave of ice and glacial water deals cold and force damage, hurling creatures back and knocking them prone.\n\nSource reference: [The Elements and Beyond: Spell Variants on 5e.tools](https://5e.tools/spells.html#glacial%20tide_teb:sv).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "The Elements and Beyond: Spell Variants",
  },
  {
    id: "v2_water_deep_freeze",
    name: "Deep Freeze",
    description: "You freeze the liquid inside a creature, paralyzing it and dealing 7d10 + 30 cold damage; a creature killed by it turns entirely to ice.\n\nSource reference: [The Elements and Beyond on 5e.tools](https://5e.tools/spells.html#deep%20freeze_teb).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "The Elements and Beyond",
  },
  {
    id: "v2_water_ice_mountain",
    name: "Ice Mountain",
    description: "A 200-foot mountain of glacial ice erupts from the ground, tossing creatures into the air and crushing anything flying above it.\n\nSource reference: [The Elemental Spellbook on 5e.tools](https://5e.tools/spells.html#ice%20mountain_theelementalspellbookspellsoficefireandlightning).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "The Elemental Spellbook",
  }
];
