export const waterAbilities = [
  {
    id: "water_initiate_echoes_of_the_deep",
    name: "Echoes of the Deep",
    description: "You can communicate with aquatic creatures or spirits of water, allowing you to understand their language and gain information about underwater locations or hidden treasures.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_initiate_ice_form",
    name: "Ice Form",
    description: "As a bonus action, you can turn your body into ice for 1 minute. You gain resistance to cold and fire damage and your movement speed is reduced by 10 feet.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_initiate_frozen_insight",
    name: "Frozen Insight",
    description: "You can temporarily turn your thoughts into ice, allowing you to gain deep insight into a complex problem or puzzle. For 1 hour, you gain advantage on Intelligence checks related to solving mysteries or understanding arcane knowledge.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_initiate_mistbound_step",
    name: "Mistbound Step",
    description: "The Misty Step spell does not consume a spell slot if you begin or end your movement in a heavily obscured area.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_tides_reflection_art_i",
    name: "Tide's Reflection Art I (Thalassios)",
    description: "As a bonus action, you summon a Water Clone in an unoccupied space you can see within 30 feet. The clone lasts for 1 minute or until destroyed. The clone is linked to your senses, allowing you to cast spells through it as if you were in its space.\n\n**Clone Statistics:**\n- **Armor Class:** Your spell save DC (8 + proficiency bonus + spellcasting modifier)\n- **Hit Points:** Equal to half your hit point maximum\n- **Speed:** Equal to your swimming speed\n- **Damage Resistances:** Fire\n- **Damage Immunities:** Cold\n- **Damage Vulnerabilities:** Lightning\n\n**Commanding the Clone:**\nAs a bonus action, you can command the clone to move and take one of the following actions:\n- **Melee Spell Attack:** Reach 10 ft., dealing 1d8 + your spellcasting modifier cold damage.\n- **Ranged Spell Attack:** Range 60 ft., dealing 1d6 + your spellcasting modifier cold damage.\n- **Utility:** Take the Dash, Dodge, or Disengage action.\n\n## Adept Tier",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Selune",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_aqua_agility",
    name: "Aqua Agility",
    description: "Your swimming speed equals your walking speed. Additionally, you gain the ability to breathe underwater and move through water at your normal speed without penalty.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_tide_of_emotions",
    name: "Tide of Emotions",
    description: "By channelling the ebb and flow of water, you can influence the emotions of others within a 30-foot radius. Choose one emotion (calm, fear, or joy); affected creatures must succeed on a Wisdom saving throw or be overwhelmed by that emotion for 1 hour.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_tidal_surge",
    name: "Tidal Surge",
    description: "You can summon a powerful wave of water that heals and revitalizes. As an action, you create a wave that washes over allies in a 30-foot radius, restoring hit points equal to 3d8 + your spellcasting ability modifier.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_rain_of_revelation",
    name: "Rain of Revelation",
    description: "You can summon a gentle, magical rain that grants clarity and insight to those who stand in it. Allies within a 20-foot radius can ask one question about their future or destiny, and you provide a vague but helpful answer based on your understanding of the world.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_glacial_shield",
    name: "Glacial Shield",
    description: "As a reaction, you can spend one spell slot and encase yourself in a barrier of ice, granting you temporary hit points equal to ten times the spell level used plus your spell casting modifier. This lasts for 1 hour.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_hydroportation",
    name: "Hydroportation",
    description: "As a bonus action, you can teleport up to 60 feet to a space you can see within a body of water or mist. You must be in contact with the water or mist to use this ability.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wind_adept_misty_escape",
    name: "Misty Escape",
    description: "When you take damage, you can use your reaction to turn into a cloud of mist, causing the attack to miss. You must spend a spell slot of 1st level or higher to use this ability.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Lluvia Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_adept_tides_reflection_art_ii",
    name: "Tide's Reflection Art II (Thalassios)",
    description: "As a reaction, you can cause one of your Water Clones to detonate in a 10-foot radius burst of frigid water. Each creature in range must make a Dexterity saving throw, taking cold damage equal to half the clone's maximum hit points on a failed save, or half as much on a successful one.\n\nIn addition, you can now summon up to two Water Clones simultaneously. When they attack together, their attack damage increases by one damage die.\n\n## Master Tier",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Selune",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "water_master_aura_of_the_deep_bulwark",
    name: "Aura of the Deep Bulwark",
    description: "As an action, you radiate a massive, pressurized sphere of dampening aqueous vapor extending from you in a 120-foot radius for 1 minute.\n\nWhile inside this aura, you and friendly creatures gain resistance to fire damage and force damage. In addition, affected creatures have advantage on saving throws against spells, traps, munitions, and hazards that produce an explosion or concussive blast (such as *Fireball*, *Shatter*, explosive barrels, or demolition charges).",
    tier: "master",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Kwon Jae-Hwan",
    location: "Sirius",
  },
  {
    id: "water_adept_tides_reflection_art_iii",
    name: "Tide's Reflection Art III (Thalassios)",
    description: "As a bonus action, you can instantly swap places with one of your Water Clones without provoking opportunity attacks.\n\nIn addition, your mastery deepens:\n- You can now summon up to three Water Clones simultaneously.\n- Your Water Clones last for 10 minutes.\n- Your Water Clones emit dim moonlight in a 60-foot radius around them.\n\n## Cantrips",
    tier: "master",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Selune",
    location: "Phudara / Isle of Whispers",
  }
];

export const waterCantrips = [
  {
    id: "water_cantrip_frostbite",
    name: "Frostbite",
    description: "https://5e.tools/spells.html#frostbite_xge",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "water_cantrip_ray_of_frost",
    name: "Ray of Frost",
    description: "https://5e.tools/spells.html#ray%20of%20frost_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "water_cantrip_shape_water",
    name: "Shape Water",
    description: "https://5e.tools/spells.html#shape%20water_xge\n\n## Spells",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  }
];

export const waterSpells = [
  {
    id: "water_1st_level_create_or_destroy_water",
    name: "Create or Destroy Water",
    description: "https://5e.tools/spells.html#create%20or%20destroy%20water_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_2nd_level_rimes_binding_ice",
    name: "Rime's Binding Ice",
    description: "https://5e.tools/spells.html#rime's%20binding%20ice_ftd",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_water_walk",
    name: "Water Walk",
    description: "https://5e.tools/spells.html#water%20walk_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_4th_level_control_water",
    name: "Control Water",
    description: "https://5e.tools/spells.html#control%20water_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "tempest_5th_cone_of_cold",
    name: "Cone of Cold",
    description: "A 60-foot cone of subzero sea squall blasts creatures for 8d8 cold damage, freezing corpses into statues.\n\nhttps://5e.tools/spells.html#cone%20of%20cold_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Evocation / Glacial Squall",
  },
  {
    id: "water_3rd_level_wall_of_water",
    name: "Wall of Water",
    description: "https://5e.tools/spells.html#wall%20of%20water_xge",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_water_breathing",
    name: "Water Breathing",
    description: "https://5e.tools/spells.html#water%20breathing_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "water_3rd_level_conjure_ocean",
    name: "Conjure Ocean",
    description: "https://5e.tools/spells.html#conjure%20ocean_obojimatallgrass",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  }
];
