export const woodAbilities = [
  {
    id: "wood_adept_natures_insight",
    name: "Nature’s Insight",
    description: "You gain proficiency in Nature and Survival skills. If you are already proficient in either of these skills, you gain expertise, doubling your proficiency bonus for those skills.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_initiate_vine_manipulation",
    name: "Vine Manipulation",
    description: "You gain the ability to manipulate vines and roots within 30 feet of you.\n\nAs an action, you can cause vines to emerge from the ground or surrounding vegetation to ensnare a creature or create barriers:\n- **Ensnare:** Force a creature to make a Strength saving throw; on a failed save, the creature is grappled or restrained (your choice) by the vines.\n- **Barriers:** Create difficult terrain in a 10-foot square area for 1 minute.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_initiate_fertile_ground_resilience",
    name: "Fertile Ground Resilience",
    description: "When you are standing on or above fertile soil (such as grasslands, forests, or similar natural terrain), you can use your reaction to gain immunity to effects that would knock you prone or push you away. Additionally, while on such terrain, you gain advantage on saving throws against being grappled or restrained.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_initiate_thorny_defence",
    name: "Thorny Defence",
    description: "When a creature hits you with a melee attack, you can use your reaction to cause thorns to erupt from your skin. The attacker takes 4d4 piercing damage.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_initiate_woodcraft",
    name: "Woodcraft",
    description: "You gain proficiency with woodcarver’s tools and the ability to craft simple wooden items. You can create small wooden objects (e.g., a carved figurine, a simple tool) in 1 hour, provided you have access to suitable materials. You can also use your tools to make minor repairs to wooden objects.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "vine_master_entangling_reach",
    name: "Entangling Reach",
    description: "As an action, you can target up to five creatures you can see within 120 feet, expending 1 point of Essence for each creature targeted. An unwilling target must make a Strength or Dexterity saving throw (your choice, DC determined by your abilities). On a failed save, the creature is grappled. This grapple ignores the creature's weight, unless the creature is one size larger than you.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    location: "Sirius",
  },
  {
    id: "vine_master_coiling_resilience",
    name: "Coiling Resilience",
    description: "You gain a +1 bonus to all saving throws for each creature you currently have grappled.\n\n## Adept Tier",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    location: "Sirius",
  },
  {
    id: "wood_adept_plant_bond",
    name: "Plant Bond",
    description: "You can communicate with plants in a basic way. You understand their emotions and can ask simple questions (e.g., \\\"Where is the nearest source of water?\\\"). Plants can also provide you with basic information about their immediate surroundings.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_woodland_stride",
    name: "Woodland Stride",
    description: "Moving through nonmagical plant life, such as undergrowth or vines, costs you no extra movement. You can also move through difficult terrain caused by plant life without penalty.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_verdant_armor",
    name: "Verdant Armor",
    description: "As a bonus action, you encase yourself in a layer of living wood and leaves for 1 minute. At the start of each of your turns while this armor is active, you regain hit points equal to 1d6.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_needle_barrage",
    name: "Needle Barrage",
    description: "You unleash a torrent of wooden needles that streak toward one creature you can see within range. The target must make a Dexterity saving throw:\n- **On a failed save:** The target takes 8d4 piercing damage and is riddled with needles, reducing its speed by half until the end of your next turn.\n- **On a successful save:** The target takes half damage and suffers no speed reduction.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_tree_form",
    name: "Tree Form",
    description: "You can use your action to transform into a treelike creature for 1 minute or until you use your action to revert to your normal form (usable once per long rest).\n\nWhile in this form, you gain the following benefits:\n- **Armor Class:** Your AC becomes 17 as your skin becomes as tough as bark.\n- **Hit Points:** You gain temporary hit points equal to twice your character level.\n- **Slam Attack:** You can make a slam melee attack with a +6 bonus to hit, dealing 2d6 + 4 bludgeoning damage.\n- **Rooted Stance:** You can root yourself to the ground. While rooted, you cannot move, but you have advantage on Strength and Constitution saving throws, and any creature that starts its turn within 5 feet of you takes 1d6 bludgeoning damage.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  }
];

export const woodCantrips = [
  {
    id: "wood_cantrip_thorn_whip",
    name: "Thorn Whip",
    description: "https://5e.tools/spells.html#thorn%20whip_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "wood_cantrip_shillelagh",
    name: "Shillelagh",
    description: "https://5e.tools/spells.html#shillelagh_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "wood_cantrip_root_grab",
    name: "Root Grab",
    description: "https://5e.tools/spells.html#root%20grab_obojimatallgrass",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "v2_wood_druidcraft",
    name: "Druidcraft",
    description: "You create a small natural sign or harmless effect that reflects the nearby environment.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#druidcraft_phb).",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB)",
  }
];

export const woodSpells = [
  {
    id: "wood_1st_level_goodberry",
    name: "Goodberry",
    description: "https://5e.tools/spells.html#goodberry_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_2nd_level_spike_growth",
    name: "Spike Growth",
    description: "https://5e.tools/spells.html#spike%20growth_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_1st_level_entangle",
    name: "Entangle",
    description: "https://5e.tools/spells.html#entangle_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_3rd_level_plant_growth",
    name: "Plant Growth",
    description: "https://5e.tools/spells.html#plant%20growth_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_3rd_level_speak_with_plants",
    name: "Speak with Plants",
    description: "https://5e.tools/spells.html#speak%20with%20plants_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_4th_level_grasping_vine",
    name: "Grasping Vine",
    description: "https://5e.tools/spells.html#grasping%20vine_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_5th_level_tree_stride",
    name: "Tree Stride",
    description: "https://5e.tools/spells.html#tree%20stride_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_6th_level_wall_of_thorns",
    name: "Wall of Thorns",
    description: "https://5e.tools/spells.html#wall%20of%20thorns_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_6th_level_transport_via_plants",
    name: "Transport via Plants",
    description: "https://5e.tools/spells.html#transport%20via%20plants_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  }
];
