export const woodAbilities = [
  {
    id: "wood_adept_natures_insight",
    name: "Nature’s Insight",
    description: "You gain proficiency in Nature and Survival skills. If you are already proficient in either of these skills, you gain expertise, doubling your proficiency bonus for those skills.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_initiate_vine_manipulation",
    name: "Vine Manipulation",
    description: "You gain the ability to manipulate vines and roots within 30 feet of you.\n\nAs an action, you can cause vines to emerge from the ground or surrounding vegetation to ensnare a creature or create barriers:\n- **Ensnare:** Force a creature to make a Strength saving throw; on a failed save, the creature is grappled or restrained (your choice) by the vines.\n- **Barriers:** Create difficult terrain in a 10-foot square area for 1 minute.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_initiate_fertile_ground_resilience",
    name: "Fertile Ground Resilience",
    description: "When you are standing on or above fertile soil (such as grasslands, forests, or similar natural terrain), you can use your reaction to gain immunity to effects that would knock you prone or push you away. Additionally, while on such terrain, you gain advantage on saving throws against being grappled or restrained.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_initiate_thorny_defence",
    name: "Thorny Defence",
    description: "When a creature hits you with a melee attack, you can use your reaction to cause thorns to erupt from your skin. The attacker takes 4d4 piercing damage.",
    tier: "initiate",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_initiate_woodcraft",
    name: "Woodcraft",
    description: "You gain proficiency with woodcarver’s tools and the ability to craft simple wooden items. You can create small wooden objects (e.g., a carved figurine, a simple tool) in 1 hour, provided you have access to suitable materials. You can also use your tools to make minor repairs to wooden objects.",
    tier: "initiate",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_plant_bond",
    name: "Plant Bond",
    description: "You can communicate with plants in a basic way. You understand their emotions and can ask simple questions (e.g., \\\"Where is the nearest source of water?\\\"). Plants can also provide you with basic information about their immediate surroundings.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_woodland_stride",
    name: "Woodland Stride",
    description: "Moving through nonmagical plant life, such as undergrowth or vines, costs you no extra movement. You can also move through difficult terrain caused by plant life without penalty.",
    tier: "adept",
    isActive: false,
    isPassive: true,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_verdant_armor",
    name: "Verdant Armor",
    description: "As a bonus action, you encase yourself in a layer of living wood and leaves for 1 minute. At the start of each of your turns while this armor is active, you regain hit points equal to 1d6.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_needle_barrage",
    name: "Needle Barrage",
    description: "You unleash a torrent of wooden needles that streak toward one creature you can see within range. The target must make a Dexterity saving throw:\n- **On a failed save:** The target takes 8d4 piercing damage and is riddled with needles, reducing its speed by half until the end of your next turn.\n- **On a successful save:** The target takes half damage and suffers no speed reduction.",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  },
  {
    id: "wood_adept_tree_form",
    name: "Tree Form",
    description: "You can use your action to transform into a treelike creature for 1 minute or until you use your action to revert to your normal form (usable once per long rest).\n\nWhile in this form, you gain the following benefits:\n- **Armor Class:** Your AC becomes 17 as your skin becomes as tough as bark.\n- **Hit Points:** You gain temporary hit points equal to twice your character level.\n- **Slam Attack:** You can make a slam melee attack with a +6 bonus to hit, dealing 2d6 + 4 bludgeoning damage.\n- **Rooted Stance:** You can root yourself to the ground. While rooted, you cannot move, but you have advantage on Strength and Constitution saving throws, and any creature that starts its turn within 5 feet of you takes 1d6 bludgeoning damage.\n\n## Master Tier",
    tier: "adept",
    isActive: true,
    isPassive: false,
    isSpell: false,
    isCantrip: false,
    author: "Espora Tribe",
    location: "Phudara / Isle of Whispers",
  }
];

export const woodCantrips = [
  {
    id: "wood_cantrip_thorn_whip",
    name: "Thorn Whip",
    description: "https://5e.tools/spells.html#thorn%20whip_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "wood_cantrip_shillelagh",
    name: "Shillelagh",
    description: "https://5e.tools/spells.html#shillelagh_xphb",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "wood_cantrip_root_grab",
    name: "Root Grab",
    description: "https://5e.tools/spells.html#root%20grab_obojimatallgrass",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
  },
  {
    id: "v2_wood_druidcraft",
    name: "Druidcraft",
    description: "You create a small natural sign or harmless effect that reflects the nearby environment.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#druidcraft_phb).\n\n---\n\n## Spells restored from V1",
    tier: "cantrip",
    isActive: false,
    isPassive: false,
    isSpell: false,
    isCantrip: true,
    author: "D&D 5e (PHB)",
  }
];

export const woodSpells = [
  {
    id: "wood_1st_level_goodberry",
    name: "Goodberry",
    description: "https://5e.tools/spells.html#goodberry_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_2nd_level_spike_growth",
    name: "Spike Growth",
    description: "https://5e.tools/spells.html#spike%20growth_xphb",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_1st_level_entangle",
    name: "Entangle",
    description: "https://5e.tools/spells.html#entangle_xphb",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_3rd_level_plant_growth",
    name: "Plant Growth",
    description: "https://5e.tools/spells.html#plant%20growth_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_3rd_level_speak_with_plants",
    name: "Speak with Plants",
    description: "https://5e.tools/spells.html#speak%20with%20plants_xphb",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_4th_level_grasping_vine",
    name: "Grasping Vine",
    description: "https://5e.tools/spells.html#grasping%20vine_xphb",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_5th_level_tree_stride",
    name: "Tree Stride",
    description: "https://5e.tools/spells.html#tree%20stride_xphb",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_6th_level_wall_of_thorns",
    name: "Wall of Thorns",
    description: "https://5e.tools/spells.html#wall%20of%20thorns_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_6th_level_transport_via_plants",
    name: "Transport via Plants",
    description: "https://5e.tools/spells.html#transport%20via%20plants_xphb",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
  },
  {
    id: "wood_1st_level_ensnaring_strike",
    name: "Ensnaring Strike",
    description: "Your weapon hit summons grasping vines that restrain the target and pierce it each turn.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#ensnaring%20strike_xphb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_1st_level_find_familiar",
    name: "Find Familiar",
    description: "You gain a spirit familiar in animal form that scouts for you and can deliver your touch spells.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#find%20familiar_xphb).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_1st_level_forest_guard",
    name: "Forest Guard",
    description: "An animated shrub grows from the ground and lashes hostile creatures that come near it.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#forest%20guard_obojimatallgrass).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "wood_1st_level_sprout_foliage",
    name: "Sprout Foliage",
    description: "Leafy foliage covers your body, letting you pass as a normal bush while prone and motionless.\n\nSource reference: [Obojima: Tales from the Tall Grass on 5e.tools](https://5e.tools/spells.html#sprout%20foliage_obojimatallgrass).",
    tier: "1st",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Obojima: Tales from the Tall Grass",
  },
  {
    id: "wood_2nd_level_barkskin",
    name: "Barkskin",
    description: "A touched creature's skin turns bark-like, giving it AC 17 if its AC is lower.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#barkskin_xphb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_2nd_level_locate_animals_or_plants",
    name: "Locate Animals or Plants",
    description: "You sense the direction and distance to the nearest named kind of beast or plant within 5 miles.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#locate%20animals%20or%20plants_xphb).",
    tier: "2nd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_3rd_level_thorn_armor",
    name: "Thorn Armor",
    description: "A thorny exoskeleton grants temporary hit points and pierces melee attackers for the hit points they strip away.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#thorn%20armor_grimhollowpg24).",
    tier: "3rd",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "wood_4th_level_conjure_woodland_beings",
    name: "Conjure Woodland Beings",
    description: "Nature spirits swirl around you, dealing force damage to creatures that enter or remain in their emanation.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#conjure%20woodland%20beings_xphb).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_4th_level_summon_plant",
    name: "Summon Plant",
    description: "You call a plant spirit with a blooming, oaken, or thorny feature that fights alongside you.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#summon%20plant_grimhollowpg24).",
    tier: "4th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "wood_5th_level_awaken",
    name: "Awaken",
    description: "A beast or plant gains an Intelligence of 10 and speech, and is charmed by you for a time.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#awaken_xphb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "wood_5th_level_commune_with_nature",
    name: "Commune with Nature",
    description: "Nature spirits reveal facts about the land within 3 miles, such as terrain, water, creatures, and settlements.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#commune%20with%20nature_xphb).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_wood_wrath_of_nature",
    name: "Wrath of Nature",
    description: "Trees, rocks, and grasses in a 60-foot cube animate against your enemies, grasping, lashing, and hurling stones.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#wrath%20of%20nature_xge).",
    tier: "5th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "v2_wood_druid_grove",
    name: "Druid Grove",
    description: "You ward an area with nature spirits: fog, grasping undergrowth, animated trees, and wind hinder intruders; it becomes permanent if cast there daily for a year.\n\nSource reference: [D&D 5e (XGE) on 5e.tools](https://5e.tools/spells.html#druid%20grove_xge).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (XGE)",
  },
  {
    id: "v2_wood_summon_dinosaur",
    name: "Summon Dinosaur",
    description: "You call forth a primeval dinosaur spirit, an ankylosaur, triceratops, or tyrannosaur, that fights at your side.\n\nSource reference: [D&D 5e (Arcana Unleashed) on 5e.tools](https://5e.tools/spells.html#summon%20dinosaur_au).",
    tier: "6th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (Arcana Unleashed)",
  },
  {
    id: "v2_wood_regenerate",
    name: "Regenerate",
    description: "A creature regains 4d8 + 15 hit points and 1 hit point each turn for an hour, and severed body parts regrow.\n\nSource reference: [D&D 5e (PHB 2024) on 5e.tools](https://5e.tools/spells.html#regenerate_xphb).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB 2024)",
  },
  {
    id: "v2_wood_forest_sanctuary",
    name: "Forest Sanctuary",
    description: "You shelter a 200-foot cube of forest from storms, winds, and floods, including magical ones; cast there daily for a year, it becomes permanent.\n\nSource reference: [Kobold Press Deep Magic on 5e.tools](https://5e.tools/spells.html#forest%20sanctuary_kpdm).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Kobold Press Deep Magic",
  },
  {
    id: "v2_wood_world_tree",
    name: "World Tree",
    description: "A seed grows into a colossal living tree up to 5 miles tall, with chambers, bridges, and roots that can house a whole civilization.\n\nSource reference: [Fragments of the Forbidden Tome on 5e.tools](https://5e.tools/spells.html#world%20tree_fftforbiddentome).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Fragments of the Forbidden Tome",
  },
  {
    id: "v2_wood_primordial_rainforest",
    name: "Primordial Rainforest",
    description: "A rainforest sprouts from a seed, overgrowing a 150-foot cube; within it you sense every creature and command lashing vines.\n\nSource reference: [Orana's Expanded Spellbook on 5e.tools](https://5e.tools/spells.html#primordial%20rainforest_oranasexpandedspellbook).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Orana's Expanded Spellbook",
  },
  {
    id: "v2_wood_arboreal_curse",
    name: "Arboreal Curse",
    description: "A creature’s flesh hardens into bark, restraining it; after three failed saves it becomes a tree, which turns permanent after a year and a day.\n\nSource reference: [Grim Hollow Player's Guide on 5e.tools](https://5e.tools/spells.html#arboreal%20curse_grimhollowpg24).",
    tier: "7th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Grim Hollow Player's Guide",
  },
  {
    id: "v2_wood_bloom",
    name: "Bloom",
    description: "A ritual that makes the land within a mile deeply fertile, instantly raising a forest, orchard, grassland, or ready field.\n\nSource reference: [Kobold Press Deep Magic on 5e.tools](https://5e.tools/spells.html#bloom_kpdm).",
    tier: "8th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "Kobold Press Deep Magic",
  },
  {
    id: "v2_moon_shapechange",
    name: "Shapechange",
    description: "You take the form of another creature while retaining your own mind and abilities.\n\nSource reference: [D&D 5e PHB on 5e.tools](https://5e.tools/spells.html#shapechange_phb).",
    tier: "9th",
    isActive: false,
    isPassive: false,
    isSpell: true,
    isCantrip: false,
    author: "D&D 5e (PHB)",
  }
];
